"""UserRole DTO Schemas - Generated by Code Generator v1.0.0

This module defines Pydantic schemas for UserRole API operations:
    - UserRoleBase: Base schema with common fields
    - UserRoleCreate: Schema for creating new UserRoles
    - UserRoleUpdate: Schema for updating existing UserRoles
    - UserRoleResponse: Schema for API responses

All schemas include OpenAPI examples for better Swagger UI documentation.
"""

from pydantic import BaseModel, Field, ConfigDict, UUID4
from datetime import datetime
from typing import Optional, List, Annotated
from uuid import UUID


class UserRoleBase(BaseModel):
    """
    Base schema for UserRole.

    Contains all common fields shared between create, update, and response schemas.
    This schema is used as a base class and should not be used directly in API operations.
    """

    user_id: str = Field(
        description="User assigned to this role",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    role_id: str = Field(
        description="Role assigned to user",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    tenant_id: str = Field(
        description="Tenant context",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "user_id": "550e8400-e29b-41d4-a716-446655440000",
                "role_id": "550e8400-e29b-41d4-a716-446655440000",
                "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class UserRoleCreate(BaseModel):
    """
    Schema for creating UserRole.

    Contains only required and optional user-provided fields.
    Auto-generated fields (id, created_at, updated_at) are excluded.

    Example:
        ```python
        data = UserRoleCreate(            user_id="550e8400-e29b-41d4-a716-446655440000",            role_id="550e8400-e29b-41d4-a716-446655440000",            tenant_id="550e8400-e29b-41d4-a716-446655440000",        )
        ```
    """

    user_id: str = Field(
        description="User assigned to this role",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    role_id: str = Field(
        description="Role assigned to user",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    tenant_id: str = Field(
        description="Tenant context",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "user_id": "550e8400-e29b-41d4-a716-446655440000",
                "role_id": "550e8400-e29b-41d4-a716-446655440000",
                "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class UserRoleUpdate(BaseModel):
    """
    Schema for updating UserRole.

    All fields are optional. Only include fields you want to update.
    Fields set to None will be ignored (not updated). To clear a field,
    use an explicit null value if the field is nullable.

    Example:
        ```python
        # Partial update - only update specific fields
        data = UserRoleUpdate(user_id="550e8400-e29b-41d4-a716-446655440000")
        ```
    """

    user_id: Optional[str] = Field(
        default=None,
        description="User assigned to this role",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    role_id: Optional[str] = Field(
        default=None,
        description="Role assigned to user",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    tenant_id: Optional[str] = Field(
        default=None,
        description="Tenant context",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "user_id": "550e8400-e29b-41d4-a716-446655440000",
                "role_id": "550e8400-e29b-41d4-a716-446655440000",
                "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class UserRoleResponse(UserRoleBase):
    """
    Schema for UserRole API responses.

    Extends UserRoleBase with auto-generated fields (id, timestamps).
    This is the schema returned by all GET, POST, and PUT operations.
    """

    id: UUID4 = Field(
        ...,
        description="Unique identifier for the UserRole",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    created_at: datetime = Field(
        ...,
        description="Timestamp when the UserRole was created",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )
    updated_at: datetime = Field(
        ...,
        description="Timestamp when the UserRole was last updated",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "user_id": "550e8400-e29b-41d4-a716-446655440000",
                "role_id": "550e8400-e29b-41d4-a716-446655440000",
                "tenant_id": "550e8400-e29b-41d4-a716-446655440000",
                "created_at": "2024-01-01T12:00:00Z",
                "updated_at": "2024-01-01T12:00:00Z",
            }
        },
    )
