"""InvestmentTerm DTO Schemas - Generated by Code Generator v1.0.0

This module defines Pydantic schemas for InvestmentTerm API operations:
    - InvestmentTermBase: Base schema with common fields
    - InvestmentTermCreate: Schema for creating new InvestmentTerms
    - InvestmentTermUpdate: Schema for updating existing InvestmentTerms
    - InvestmentTermResponse: Schema for API responses

All schemas include OpenAPI examples for better Swagger UI documentation.
"""

from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime, date
from typing import Any, Optional, List, Annotated
from uuid import UUID
from decimal import Decimal


class InvestmentTermBase(BaseModel):
    """
    Base schema for InvestmentTerm.

    Contains all common fields shared between create, update, and response schemas.
    This schema is used as a base class and should not be used directly in API operations.
    """

    legal_entity_id: str = Field(
        description="Company receiving the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_person_id: str = Field(
        description="Person making the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_id: Optional[str] = Field(
        default=None,
        description="Cross-service reference to investor-service Investor",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investment_amount: Decimal = Field(
        description="Investment amount (must be > 0)", json_schema_extra={"example": "123.45"}
    )
    currency: str = Field(
        default="USD", max_length=3, json_schema_extra={"example": "example_currency"}
    )
    valuation_cap: Optional[Decimal] = Field(
        default=None,
        description="SAFE valuation cap (null for uncapped)",
        json_schema_extra={"example": "123.45"},
    )
    discount_percentage: Optional[Decimal] = Field(
        default=None,
        description="Discount percentage 0-30 (null if no discount)",
        json_schema_extra={"example": "123.45"},
    )
    investment_date: date = Field(..., json_schema_extra={"example": "2024-01-01"})
    pro_rata_rights: bool = Field(default=False, json_schema_extra={"example": True})
    source_document_id: Optional[str] = Field(
        default=None,
        description="Reference to LegalDocument that defines these terms",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "legal_entity_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_person_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_id": "550e8400-e29b-41d4-a716-446655440000",
                "investment_amount": "123.45",
                "currency": "example_currency",
                "valuation_cap": "123.45",
                "discount_percentage": "123.45",
                "investment_date": "2024-01-01",
                "pro_rata_rights": True,
                "source_document_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class InvestmentTermCreate(BaseModel):
    """
    Schema for creating InvestmentTerm.

    Contains only required and optional user-provided fields.
    Auto-generated fields (id, created_at, updated_at) are excluded.

    Example:
        ```python
        data = InvestmentTermCreate(            legal_entity_id="550e8400-e29b-41d4-a716-446655440000",            investor_person_id="550e8400-e29b-41d4-a716-446655440000",            investment_amount="123.45",            investment_date="2024-01-01",        )
        ```
    """

    legal_entity_id: str = Field(
        description="Company receiving the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_person_id: str = Field(
        description="Person making the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_id: Optional[str] = Field(
        default=None,
        description="Cross-service reference to investor-service Investor",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investment_amount: Decimal = Field(
        description="Investment amount (must be > 0)", json_schema_extra={"example": "123.45"}
    )
    currency: str = Field(
        default="USD", max_length=3, json_schema_extra={"example": "example_currency"}
    )
    valuation_cap: Optional[Decimal] = Field(
        default=None,
        description="SAFE valuation cap (null for uncapped)",
        json_schema_extra={"example": "123.45"},
    )
    discount_percentage: Optional[Decimal] = Field(
        default=None,
        description="Discount percentage 0-30 (null if no discount)",
        json_schema_extra={"example": "123.45"},
    )
    investment_date: date = Field(..., json_schema_extra={"example": "2024-01-01"})
    pro_rata_rights: bool = Field(default=False, json_schema_extra={"example": True})
    source_document_id: Optional[str] = Field(
        default=None,
        description="Reference to LegalDocument that defines these terms",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "legal_entity_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_person_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_id": "550e8400-e29b-41d4-a716-446655440000",
                "investment_amount": "123.45",
                "currency": "example_currency",
                "valuation_cap": "123.45",
                "discount_percentage": "123.45",
                "investment_date": "2024-01-01",
                "pro_rata_rights": True,
                "source_document_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class InvestmentTermUpdate(BaseModel):
    """
    Schema for updating InvestmentTerm.

    All fields are optional. Only include fields you want to update.
    Fields set to None will be ignored (not updated). To clear a field,
    use an explicit null value if the field is nullable.

    Example:
        ```python
        # Partial update - only update specific fields
        data = InvestmentTermUpdate(legal_entity_id="550e8400-e29b-41d4-a716-446655440000")
        ```
    """

    legal_entity_id: Optional[str] = Field(
        default=None,
        description="Company receiving the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_person_id: Optional[str] = Field(
        default=None,
        description="Person making the investment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investor_id: Optional[str] = Field(
        default=None,
        description="Cross-service reference to investor-service Investor",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    investment_amount: Optional[Decimal] = Field(
        default=None,
        description="Investment amount (must be > 0)",
        json_schema_extra={"example": "123.45"},
    )
    currency: Optional[str] = Field(default=None, json_schema_extra={"example": "example_currency"})
    valuation_cap: Optional[Decimal] = Field(
        default=None,
        description="SAFE valuation cap (null for uncapped)",
        json_schema_extra={"example": "123.45"},
    )
    discount_percentage: Optional[Decimal] = Field(
        default=None,
        description="Discount percentage 0-30 (null if no discount)",
        json_schema_extra={"example": "123.45"},
    )
    investment_date: Optional[date] = Field(
        default=None, json_schema_extra={"example": "2024-01-01"}
    )
    pro_rata_rights: Optional[bool] = Field(default=None, json_schema_extra={"example": True})
    source_document_id: Optional[str] = Field(
        default=None,
        description="Reference to LegalDocument that defines these terms",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "legal_entity_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_person_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_id": "550e8400-e29b-41d4-a716-446655440000",
                "investment_amount": "123.45",
                "currency": "example_currency",
                "valuation_cap": "123.45",
                "discount_percentage": "123.45",
                "investment_date": "2024-01-01",
                "pro_rata_rights": True,
                "source_document_id": "550e8400-e29b-41d4-a716-446655440000",
            }
        },
    )


class InvestmentTermResponse(InvestmentTermBase):
    """
    Schema for InvestmentTerm API responses.

    Extends InvestmentTermBase with auto-generated fields (id, timestamps).
    This is the schema returned by all GET, POST, and PUT operations.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the InvestmentTerm",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the InvestmentTerm was created",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the InvestmentTerm was last updated",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "legal_entity_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_person_id": "550e8400-e29b-41d4-a716-446655440000",
                "investor_id": "550e8400-e29b-41d4-a716-446655440000",
                "investment_amount": "123.45",
                "currency": "example_currency",
                "valuation_cap": "123.45",
                "discount_percentage": "123.45",
                "investment_date": "2024-01-01",
                "pro_rata_rights": True,
                "source_document_id": "550e8400-e29b-41d4-a716-446655440000",
                "created_at": "2024-01-01T12:00:00Z",
                "updated_at": "2024-01-01T12:00:00Z",
            }
        },
    )
