/**
 * EmailTemplate Query Key Factory
 *
 * Centralized query key factory for React Query cache management.
 * Provides consistent, type-safe query keys for all email_template queries.
 *
 * Query keys follow a hierarchical structure for efficient cache invalidation:
 * - ['emailtemplates'] - All email_template queries
 * - ['emailtemplates', 'list'] - All list queries
 * - ['emailtemplates', 'list', { filters }] - Specific filtered list
 * - ['emailtemplates', 'detail', id] - Specific email_template by ID
 *
 * @example
 * ```typescript
 * import { email_templateKeys } from './queryKeys';
 *
 * // Use in useQuery
 * const { data } = useQuery({
 *   queryKey: email_templateKeys.list({ is_active: true }),
 *   queryFn: () => email_templateService.getAll({ is_active: true }),
 * });
 *
 * // Invalidate all email_template queries
 * queryClient.invalidateQueries({ queryKey: email_templateKeys.all });
 *
 * // Invalidate specific email_template
 * queryClient.invalidateQueries({ queryKey: email_templateKeys.detail('uuid') });
 * ```
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:40.251441Z
 */

import type { EmailTemplateFilterOptions } from '../types/email_template.types';

/**
 * Root query key for EmailTemplate entity
 * Used as namespace prefix for all email_template queries
 */
const EMAIL_TEMPLATE_ROOT = 'emailtemplates' as const;

/**
 * EmailTemplate Query Keys
 *
 * Hierarchical query key factory for email_template queries:
 * - all: Base key for all email_template queries
 * - lists: All list queries (for bulk invalidation)
 * - list(filters): Specific filtered list
 * - details: All detail queries
 * - detail(id): Specific email_template by ID
 * - dropdown(activeOnly): Dropdown options query
 *
 * @example
 * ```typescript
 * // List with filters
 * const key = email_templateKeys.list({ is_active: true });
 * // Result: ['emailtemplates', 'list', { is_active: true }]
 *
 * // Detail by ID
 * const key = email_templateKeys.detail('uuid-here');
 * // Result: ['emailtemplates', 'detail', 'uuid-here']
 *
 * // Invalidate all email_template data
 * queryClient.invalidateQueries({ queryKey: email_templateKeys.all });
 * ```
 */
export const email_templateKeys = {
  /**
   * Base key for all email_template queries
   * Use this to invalidate all email_template-related queries at once
   *
   * @example
   * ```typescript
   * // Invalidate everything after a major change
   * queryClient.invalidateQueries({ queryKey: email_templateKeys.all });
   * ```
   */
  all: [EMAIL_TEMPLATE_ROOT] as const,

  /**
   * Key for all list queries
   * Use this to invalidate all list queries without affecting detail queries
   *
   * @returns Query key tuple for list namespace
   *
   * @example
   * ```typescript
   * // Invalidate all list queries
   * queryClient.invalidateQueries({ queryKey: email_templateKeys.lists() });
   * ```
   */
  lists: () => [...email_templateKeys.all, 'list'] as const,

  /**
   * Key for a specific filtered list query
   * Include filters in the key to enable automatic re-fetching when filters change
   *
   * @param filters - Optional filter options for the query
   * @returns Query key tuple including filters
   *
   * @example
   * ```typescript
   * // List all active
   * const key = email_templateKeys.list({ is_active: true });
   *
   * // List with search
   * const key = email_templateKeys.list({ search: 'test' });
   *
   * // Unfiltered list
   * const key = email_templateKeys.list();
   * ```
   */
  list: (filters?: EmailTemplateFilterOptions) =>
    [...email_templateKeys.lists(), filters ?? {}] as const,

  /**
   * Key for all detail queries
   * Use this to invalidate all detail queries without affecting list queries
   *
   * @returns Query key tuple for detail namespace
   *
   * @example
   * ```typescript
   * // Invalidate all detail queries
   * queryClient.invalidateQueries({ queryKey: email_templateKeys.details() });
   * ```
   */
  details: () => [...email_templateKeys.all, 'detail'] as const,

  /**
   * Key for a specific email_template by ID
   * Use this for fetching and invalidating individual email_template records
   *
   * @param id - EmailTemplate ID (UUID)
   * @returns Query key tuple for specific email_template
   *
   * @example
   * ```typescript
   * // Fetch specific email_template
   * const { data } = useQuery({
   *   queryKey: email_templateKeys.detail('uuid-here'),
   *   queryFn: () => email_templateService.getById('uuid-here'),
   * });
   *
   * // Invalidate after update
   * queryClient.invalidateQueries({
   *   queryKey: email_templateKeys.detail('uuid-here')
   * });
   * ```
   */
  detail: (id: string) => [...email_templateKeys.details(), id] as const,

  /**
   * Key for dropdown options query
   * Separate key allows independent caching of dropdown data
   *
   * @param activeOnly - Whether to include only active email_templates (default: true)
   * @returns Query key tuple for dropdown query
   *
   * @example
   * ```typescript
   * // Active items only (default)
   * const key = email_templateKeys.dropdown();
   *
   * // Include inactive items
   * const key = email_templateKeys.dropdown(false);
   * ```
   */
  dropdown: (activeOnly: boolean = true) =>
    [...email_templateKeys.all, 'dropdown', { activeOnly }] as const,

  /**
   * EmailTemplates filtered by user ID
   *
   * @param userId - User ID (UUID)
   * @returns Query key tuple
   */
  byUser: (userId: string) =>
    [...email_templateKeys.all, 'by-user', userId] as const,
} as const;

/**
 * Type representing any valid EmailTemplate query key
 * Useful for typing query key arrays in generic contexts
 */
export type EmailTemplateQueryKey =
  | typeof email_templateKeys.all
  | ReturnType<typeof email_templateKeys.lists>
  | ReturnType<typeof email_templateKeys.list>
  | ReturnType<typeof email_templateKeys.details>
  | ReturnType<typeof email_templateKeys.detail>
  | ReturnType<typeof email_templateKeys.dropdown>
;

/**
 * Default export for convenience
 */
export default email_templateKeys;
