/**
 * ContactPersonList Component
 *
 * Displays a paginated, sortable table of contact_persons with:
 * - Search filter with debounce
 * - Pagination controls
 * - Sortable columns
 * - Loading skeleton
 * - Error handling
 * - Empty state
 * - CSV export
 * - Dark mode support
 *
 * Individual associated with a legal entity — founder, director, signatory, or counterparty
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:50.293172Z
 */

import React, { useState, useEffect, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Box,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TablePagination,
  TableSortLabel,
  TextField,
  Typography,
  Alert as MuiAlert,
  Skeleton,
  IconButton,
  Tooltip,
  Chip,
  InputAdornment,
} from '@mui/material';
import {
  Search as SearchIcon,
  Refresh as RefreshIcon,
  Download as DownloadIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Visibility as ViewIcon,
} from '@mui/icons-material';
import { useContactPersons, useDeleteContactPerson } from '../hooks/useContactPersons';
import type { ContactPerson, ContactPersonFilterOptions } from '../types/contact_person.types';
import { useNotification } from '../contexts/NotificationContext';

// ============================================================================
// Types
// ============================================================================

/**
 * Column definition for the entity list table
 */
interface Column {
  /** Field key in the entity object */
  key: keyof ContactPerson | string;
  /** Display label for the column header */
  label: string;
  /** Whether the column is sortable */
  sortable?: boolean;
  /** Text alignment for the column */
  align?: 'left' | 'center' | 'right';
  /** Column width (CSS value) */
  width?: string;
  /** Custom render function for cell content */
  render?: (value: unknown, row: ContactPerson) => React.ReactNode;
}

/**
 * Sort direction type
 */
type SortDirection = 'asc' | 'desc';

/**
 * Props for ContactPersonList component
 */
interface ContactPersonListProps {
  /** Optional title override */
  title?: string;
  /** Whether to show the add button */
  showAddButton?: boolean;
  /** Callback when add button is clicked */
  onAdd?: () => void;
  /** Whether to enable CSV export */
  exportable?: boolean;
  /** Custom empty state message */
  emptyMessage?: string;
  /** Whether to navigate to detail page on row click */
  navigateOnClick?: boolean;
  /** Custom row click handler (overrides navigation) */
  onRowClick?: (row: ContactPerson) => void;
  /** Custom delete handler (overrides internal confirm dialog) */
  onDelete?: (row: ContactPerson) => void;
  /** Additional filters to apply */
  additionalFilters?: Partial<ContactPersonFilterOptions>;
  /** Custom className for the container */
  className?: string;
}

// ============================================================================
// Constants
// ============================================================================

/** Debounce delay for search input (ms) */
const SEARCH_DEBOUNCE_MS = 500;

/** Available rows per page options */
const ROWS_PER_PAGE_OPTIONS = [25, 50, 100, 200];

/** Default rows per page */
const DEFAULT_ROWS_PER_PAGE = 50;

/** Number of skeleton rows to show when loading */
const SKELETON_ROWS = 5;

/**
 * Column definitions for the contact_person list table
 */
const COLUMNS: Column[] = [
  {
    key: 'user_id',
    label: 'User Id',
    sortable: true,
    align: 'left',
    render: (value) => value != null ? String(value) : '-',
  },
  {
    key: 'legal_entity_id',
    label: 'Legal Entity Id',
    sortable: true,
    align: 'left',
    render: (value) => value != null ? String(value) : '-',
  },
  {
    key: 'full_name',
    label: 'Full Name',
    sortable: true,
    align: 'left',
    render: (value) => value != null ? String(value) : '-',
  },
  {
    key: 'email',
    label: 'Email',
    sortable: true,
    align: 'left',
    render: (value) => value != null ? String(value) : '-',
  },
  {
    key: 'role',
    label: 'Role',
    sortable: true,
    align: 'left',
    render: (value) => value != null ? String(value) : '-',
  },
  {
    key: 'is_primary',
    label: 'Is Primary',
    sortable: true,
    align: 'left',
    render: (value) => (
      <Chip
        size="small"
        label={value ? 'Yes' : 'No'}
        color={value ? 'success' : 'default'}
        variant="outlined"
      />
    ),
  },
];

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Export data to CSV file
 */
function exportToCsv(data: ContactPerson[], filename: string): void {
  const headers = COLUMNS.map((col) => col.label).join(',');
  const rows = data.map((row) =>
    COLUMNS.map((col) => {
      const value = row[col.key as keyof ContactPerson];
      const stringValue = value === null || value === undefined ? '' : String(value);
      // Escape commas and quotes in CSV
      return stringValue.includes(',') || stringValue.includes('"')
        ? `"${stringValue.replace(/"/g, '""')}"`
        : stringValue;
    }).join(',')
  );

  const csv = [headers, ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}

// ============================================================================
// Component
// ============================================================================

/**
 * ContactPersonList Component
 *
 * Renders a paginated, sortable list of contact_persons with search,
 * filtering, and export capabilities.
 */
export function ContactPersonList({
  title = 'ContactPersons',
  showAddButton = true,
  onAdd,
  exportable = true,
  emptyMessage = 'No contact_persons found',
  navigateOnClick = true,
  onRowClick,
  onDelete,
  additionalFilters = {},
  className = '',
}: ContactPersonListProps): React.ReactElement {
  const navigate = useNavigate();
  const { showSuccess, showError } = useNotification();
  const deleteContactPersonMutation = useDeleteContactPerson();

  // -------------------------------------------------------------------------
  // State
  // -------------------------------------------------------------------------

  // Pagination state
  const [page, setPage] = useState(0);
  const [rowsPerPage, setRowsPerPage] = useState(DEFAULT_ROWS_PER_PAGE);

  // Search state with debounce
  const [searchInput, setSearchInput] = useState('');
  const [debouncedSearch, setDebouncedSearch] = useState('');

  // Sorting state
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>('asc');

  // -------------------------------------------------------------------------
  // Effects
  // -------------------------------------------------------------------------

  // Debounce search input
  useEffect(() => {
    const timer = setTimeout(() => {
      setDebouncedSearch(searchInput);
      setPage(0); // Reset to first page on search
    }, SEARCH_DEBOUNCE_MS);

    return () => clearTimeout(timer);
  }, [searchInput]);

  // -------------------------------------------------------------------------
  // Data Fetching
  // -------------------------------------------------------------------------

  // Build filter options
  const filters: ContactPersonFilterOptions = useMemo(
    () => ({
      search: debouncedSearch || undefined,
      page: page + 1, // API uses 1-indexed pages
      page_size: rowsPerPage,
      sort_by: sortKey || undefined,
      sort_order: sortKey ? sortDirection : undefined,
      ...additionalFilters,
    }),
    [debouncedSearch, page, rowsPerPage, sortKey, sortDirection, additionalFilters]
  );

  // Fetch data using React Query
  const {
    data: contactPersons,
    isLoading,
    isError,
    error,
    refetch,
  } = useContactPersons({ filters, activeOnly: false });

  // -------------------------------------------------------------------------
  // Handlers
  // -------------------------------------------------------------------------

  /** Handle page change */
  const handleChangePage = useCallback(
    (_event: unknown, newPage: number) => {
      setPage(newPage);
    },
    []
  );

  /** Handle rows per page change */
  const handleChangeRowsPerPage = useCallback(
    (event: React.ChangeEvent<HTMLInputElement>) => {
      setRowsPerPage(parseInt(event.target.value, 10));
      setPage(0);
    },
    []
  );

  /** Handle sort change */
  const handleSort = useCallback((columnKey: string) => {
    setSortKey((prevKey) => {
      if (prevKey === columnKey) {
        setSortDirection((prevDir) => (prevDir === 'asc' ? 'desc' : 'asc'));
        return columnKey;
      }
      setSortDirection('asc');
      return columnKey;
    });
  }, []);

  /** Handle row click */
  const handleRowClick = useCallback(
    (row: ContactPerson) => {
      if (onRowClick) {
        onRowClick(row);
      } else if (navigateOnClick) {
        navigate(`/contact_persons/${row.id}`);
      }
    },
    [navigate, navigateOnClick, onRowClick]
  );

  /** Handle export click */
  const handleExport = useCallback(() => {
    if (contactPersons && contactPersons.length > 0) {
      const timestamp = new Date().toISOString().split('T')[0];
      exportToCsv(contactPersons, `contact_persons_${timestamp}`);
    }
  }, [contactPersons]);

  /** Handle add click */
  const handleAdd = useCallback(() => {
    if (onAdd) {
      onAdd();
    } else {
      navigate('/contact_persons/new');
    }
  }, [navigate, onAdd]);

  /** Handle edit click */
  const handleEdit = useCallback(
    (row: ContactPerson, event: React.MouseEvent) => {
      event.stopPropagation(); // Prevent row click navigation
      navigate(`/contact_persons/${row.id}/edit`);
    },
    [navigate]
  );

  /** Handle view click */
  const handleView = useCallback(
    (row: ContactPerson, event: React.MouseEvent) => {
      event.stopPropagation(); // Prevent row click navigation
      navigate(`/contact_persons/${row.id}`);
    },
    [navigate]
  );

  /** Handle delete click */
  const handleDelete = useCallback(
    async (row: ContactPerson, event: React.MouseEvent) => {
      event.stopPropagation(); // Prevent row click navigation

      // Delegate to external handler if provided
      if (onDelete) {
        onDelete(row);
        return;
      }

      // Confirm before deleting
      if (!window.confirm(`Are you sure you want to delete this contact_person?`)) {
        return;
      }

      try {
        await deleteContactPersonMutation.mutateAsync(row.id);
        showSuccess('ContactPerson deleted successfully');
        refetch(); // Refresh the list after deletion
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
        showError(`Failed to delete ContactPerson: ${errorMessage}`);
      }
    },
    [onDelete, deleteContactPersonMutation, showSuccess, showError, refetch]
  );

  /** Handle refresh click */
  const handleRefresh = useCallback(() => {
    refetch();
  }, [refetch]);

  // -------------------------------------------------------------------------
  // Render Helpers
  // -------------------------------------------------------------------------

  /** Render loading skeleton */
  const renderSkeleton = () => (
    <>
      {Array.from({ length: SKELETON_ROWS }).map((_, index) => (
        <TableRow key={index}>
          {COLUMNS.map((column) => (
            <TableCell key={String(column.key)}>
              <Skeleton animation="wave" height={24} />
            </TableCell>
          ))}
          {/* Actions column skeleton */}
          <TableCell>
            <Skeleton animation="wave" width={32} height={32} variant="circular" />
          </TableCell>
        </TableRow>
      ))}
    </>
  );

  /** Render empty state */
  const renderEmptyState = () => (
    <TableRow>
      <TableCell colSpan={COLUMNS.length + 1} align="center">
        <Box py={4}>
          <Typography color="text.secondary">{emptyMessage}</Typography>
        </Box>
      </TableCell>
    </TableRow>
  );

  /** Render data rows */
  const renderRows = () => (
    <>
      {contactPersons?.map((row) => (
        <TableRow
          key={row.id}
          hover
          onClick={() => handleRowClick(row)}
          sx={{
            cursor: navigateOnClick || onRowClick ? 'pointer' : 'default',
          }}
        >
          {COLUMNS.map((column) => {
            const value = row[column.key as keyof ContactPerson];
            return (
              <TableCell key={String(column.key)} align={column.align || 'left'}>
                {column.render ? column.render(value, row) : String(value ?? '-')}
              </TableCell>
            );
          })}
          {/* Actions cell */}
          <TableCell align="right">
            <Tooltip title="View ContactPerson">
              <span>
                <IconButton
                  size="small"
                  data-testid={`btn-view-contact_person-${row.id}`}
                  onClick={(e) => handleView(row, e)}
                >
                  <ViewIcon fontSize="small" />
                </IconButton>
              </span>
            </Tooltip>
            <Tooltip title="Edit ContactPerson">
              <IconButton
                size="small"
                data-testid={`btn-edit-contact_person-${row.id}`}
                onClick={(e) => handleEdit(row, e)}
              >
                <EditIcon fontSize="small" />
              </IconButton>
            </Tooltip>
            <Tooltip title="Delete ContactPerson">
              <span>
                <IconButton
                  size="small"
                  data-testid={`btn-delete-contact_person-${row.id}`}
                  onClick={(e) => handleDelete(row, e)}
                >
                  <DeleteIcon fontSize="small" />
                </IconButton>
              </span>
            </Tooltip>
          </TableCell>
        </TableRow>
      ))}
    </>
  );

  // -------------------------------------------------------------------------
  // Error State
  // -------------------------------------------------------------------------

  if (isError) {
    return (
      <Box className={className} p={3}>
        <MuiAlert
          severity="error"
          action={
            <IconButton color="inherit" size="small" onClick={handleRefresh}>
              <RefreshIcon />
            </IconButton>
          }
        >
          Error loading contact_persons: {(error as Error)?.message || 'Unknown error'}
        </MuiAlert>
      </Box>
    );
  }

  // -------------------------------------------------------------------------
  // Main Render
  // -------------------------------------------------------------------------

  return (
    <Box className={className}>
      {/* Header */}
      <Box
        display="flex"
        justifyContent="space-between"
        alignItems="center"
        mb={3}
      >
        <Typography variant="h5" component="h1">
          {title}
        </Typography>

        <Box display="flex" gap={1}>
          <Tooltip title="Refresh">
            <span>
              <IconButton onClick={handleRefresh} disabled={isLoading}>
                <RefreshIcon />
              </IconButton>
            </span>
          </Tooltip>

          {exportable && (
            <Tooltip title="Export to CSV">
              <span>
                <IconButton
                  onClick={handleExport}
                  disabled={isLoading || !contactPersons?.length}
                >
                  <DownloadIcon />
                </IconButton>
              </span>
            </Tooltip>
          )}

          {showAddButton && (
            <Tooltip title="Add ContactPerson">
              <IconButton
                onClick={handleAdd}
                color="primary"
                data-testid="btn-add-contact_person"
              >
                <AddIcon />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      </Box>

      {/* Search Filter */}
      <Box mb={2}>
        <TextField
          fullWidth
          size="small"
          placeholder="Search contact_persons..."
          value={searchInput}
          onChange={(e) => setSearchInput(e.target.value)}
          InputProps={{
            startAdornment: (
              <InputAdornment position="start">
                <SearchIcon color="action" />
              </InputAdornment>
            ),
          }}
        />
      </Box>

      {/* Table */}
      <Paper>
        <TableContainer>
          <Table size="small">
            <TableHead>
              <TableRow>
                {COLUMNS.map((column) => (
                  <TableCell
                    key={String(column.key)}
                    align={column.align || 'left'}
                    sx={{ width: column.width }}
                  >
                    {column.sortable ? (
                      <TableSortLabel
                        active={sortKey === column.key}
                        direction={sortKey === column.key ? sortDirection : 'asc'}
                        onClick={() => handleSort(String(column.key))}
                      >
                        {column.label}
                      </TableSortLabel>
                    ) : (
                      column.label
                    )}
                  </TableCell>
                ))}
                {/* Actions column header */}
                <TableCell align="right" sx={{ width: '120px' }}>
                  Actions
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              {isLoading
                ? renderSkeleton()
                : contactPersons?.length
                  ? renderRows()
                  : renderEmptyState()}
            </TableBody>
          </Table>
        </TableContainer>

        {/* Pagination */}
        <TablePagination
          component="div"
          count={contactPersons?.length || 0}
          page={page}
          onPageChange={handleChangePage}
          rowsPerPage={rowsPerPage}
          onRowsPerPageChange={handleChangeRowsPerPage}
          rowsPerPageOptions={ROWS_PER_PAGE_OPTIONS}
        />
      </Paper>
    </Box>
  );
}

// Default export for convenience
export default ContactPersonList;
