/**
 * LegalDocumentDetail Component
 *
 * Displays detailed information about a legal_document in a structured layout.
 * Organized into sections:
 * - Basic Information (all entity fields)
 * - Status (active/inactive indicator)
 * - Audit Trail (created/updated timestamps)
 *
 * Features:
 * - React Query integration for data fetching
 * - Material UI Grid layout for responsive design
 * - Loading skeleton states
 * - Error handling with Alert component
 * - Not found state handling
 * - Edit/Delete action buttons
 * - Back navigation
 * - Status badge indicators (active/inactive)
 * - Formatted dates and numbers
 * - Accessibility support (WCAG 2.1 Level AA)
 *
 * Generated legal document with full lifecycle tracking, template reference, and party links
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:54.145247Z
 */

import React, { useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Paper,
  Grid,
  Typography,
  Alert as MuiAlert,
  Skeleton,
  IconButton,
  Button,
  Chip,
  Divider,
  Tooltip,
} from '@mui/material';
import {
  ArrowBack as ArrowBackIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';
import { useLegalDocument} from '../hooks/useLegalDocuments';
import type { LegalDocument} from '../types/legal_document.types';

// ============================================================================
// Types
// ============================================================================

/**
 * Props for LegalDocumentDetail component
 */
interface LegalDocumentDetailProps {
  /** Entity ID to display (optional, can be read from URL params) */
  id?: string;
  /** Whether to show the back button */
  showBackButton?: boolean;
  /** Whether to show edit button */
  showEditButton?: boolean;
  /** Whether to show delete button */
  showDeleteButton?: boolean;
  /** Callback when edit button is clicked */
  onEdit?: (legalDocument: LegalDocument) => void;
  /** Callback when delete button is clicked */
  onDelete?: (legalDocument: LegalDocument) => void;
  /** Custom className for the container */
  className?: string;
}

// ============================================================================
// Helper Components
// ============================================================================

/**
 * Field component for displaying label-value pairs
 */
const DetailField: React.FC<{
  label: string;
  value: string | React.ReactNode;
  testId: string;
}> = ({ label, value, testId }) => (
  <div data-testid={testId}>
    <label>
      <Typography variant="body2" color="text.secondary" component="span">
        {label}
      </Typography>
    </label>
    <span>
      <Typography variant="body1" component="span">
        {value}
      </Typography>
    </span>
  </div>
);

/**
 * Loading skeleton for the detail view
 */
const DetailSkeleton: React.FC = () => (
  <Box data-testid="legal_document-detail-skeleton">
    <Box display="flex" alignItems="center" gap={2} mb={3}>
      <Skeleton variant="circular" width={40} height={40} />
      <Skeleton variant="text" width={200} height={32} />
    </Box>
    <Paper sx={{ p: 3 }}>
      <Skeleton variant="text" width={150} height={28} sx={{ mb: 2 }} />
      {Array.from({ length: 6 }).map((_, index) => (
        <Box key={index} sx={{ mb: 2 }}>
          <Skeleton variant="text" width={100} height={16} />
          <Skeleton variant="text" width={250} height={24} />
        </Box>
      ))}
    </Paper>
  </Box>
);

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Format a date string for display
 */
function formatDate(value: string | undefined | null): string {
  if (!value) return '-';
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}

/**
 * Format a number for display
 */
function formatNumber(value: number | undefined | null, decimals: number = 2): string {
  if (value === null || value === undefined) return '-';
  return value.toLocaleString(undefined, {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

/**
 * Display a value with fallback for empty/null values
 */
function displayValue(value: string | number | boolean | undefined | null): string {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'string') {
    return value.trim() !== '' ? value : '-';
  }
  if (typeof value === 'boolean') {
    return value ? 'Yes' : 'No';
  }
  return String(value);
}

// ============================================================================
// Component
// ============================================================================

/**
 * LegalDocumentDetail Component
 *
 * Renders comprehensive legal_document information in a structured grid layout.
 *
 * @example
 * ```tsx
 * // Using URL params (in a route like /legal_documents/:id)
 * <LegalDocumentDetail />
 *
 * // With explicit ID
 * <LegalDocumentDetail id="123" />
 *
 * // With custom handlers
 * <LegalDocumentDetail
 *   onEdit={(entity) => navigate(`/legal_documents/${entity.id}/edit`)}
 *   onDelete={(entity) => handleDelete(entity.id)}
 * />
 * ```
 */
export function LegalDocumentDetail({
  id: propId,
  showBackButton = true,
  showEditButton = true,
  showDeleteButton = true,
  onEdit,
  onDelete,
  className = '',
}: LegalDocumentDetailProps): React.ReactElement {
  const navigate = useNavigate();
  const params = useParams<{ id: string }>();

  // Use prop ID if provided, otherwise get from URL params
  const id = propId ?? params.id;

  // -------------------------------------------------------------------------
  // Data Fetching
  // -------------------------------------------------------------------------

  const {
    data: legalDocument,
    isLoading,
    isError,
    error,
    refetch,
  } = useLegalDocument(id ?? '', {
    enabled: Boolean(id),
  });

  // -------------------------------------------------------------------------
  // Handlers
  // -------------------------------------------------------------------------

  /** Handle back button click */
  const handleBack = useCallback(() => {
    navigate('/legal_documents');
  }, [navigate]);

  /** Handle edit button click */
  const handleEdit = useCallback(() => {
    if (legalDocument) {
      if (onEdit) {
        onEdit(legalDocument);
      } else {
        navigate(`/legal_documents/${legalDocument.id}/edit`);
      }
    }
  }, [navigate, legalDocument, onEdit]);

  /** Handle delete button click */
  const handleDelete = useCallback(() => {
    if (legalDocument && onDelete) {
      onDelete(legalDocument);
    }
  }, [legalDocument, onDelete]);

  /** Handle refresh button click */
  const handleRefresh = useCallback(() => {
    refetch();
  }, [refetch]);

  // -------------------------------------------------------------------------
  // Render States
  // -------------------------------------------------------------------------

  // Loading state
  if (isLoading) {
    return (
      <Box className={className}>
        <DetailSkeleton />
      </Box>
    );
  }

  // Error state
  if (isError) {
    return (
      <Box className={className} p={3}>
        <MuiAlert
          severity="error"
          action={
            <IconButton color="inherit" size="small" onClick={handleRefresh}>
              <RefreshIcon />
            </IconButton>
          }
        >
          Error loading legal_document: {(error as Error)?.message || 'Unknown error'}
        </MuiAlert>
      </Box>
    );
  }

  // Not found state
  if (!legalDocument) {
    return (
      <Box className={className} p={3}>
        <MuiAlert severity="warning">
          LegalDocument not found
        </MuiAlert>
        {showBackButton && (
          <Box mt={2}>
            <Button
              startIcon={<ArrowBackIcon />}
              onClick={handleBack}
              variant="outlined"
            >
              Back to LegalDocuments
            </Button>
          </Box>
        )}
      </Box>
    );
  }

  // -------------------------------------------------------------------------
  // Main Render
  // -------------------------------------------------------------------------

  return (
    <div data-testid="legal_document-detail" className={className}>
      {/* Header */}
      <Box
        display="flex"
        justifyContent="space-between"
        alignItems="center"
        mb={3}
      >
        <Box display="flex" alignItems="center" gap={2}>
          {showBackButton && (
            <Tooltip title="Back to LegalDocuments">
              <IconButton onClick={handleBack}>
                <ArrowBackIcon />
              </IconButton>
            </Tooltip>
          )}
          <Typography variant="h5" component="h1">
            LegalDocument Details
          </Typography>
{legalDocument.is_active !== undefined && (
            <Chip
              size="small"
              label={legalDocument.is_active ? 'Active' : 'Inactive'}
              color={legalDocument.is_active ? 'success' : 'default'}
              variant="outlined"
            />
          )}
        </Box>

        <Box display="flex" gap={1}>
          <Tooltip title="Refresh">
            <span>
              <IconButton onClick={handleRefresh} disabled={isLoading}>
                <RefreshIcon />
              </IconButton>
            </span>
          </Tooltip>

          {showEditButton && (
            <Tooltip title="Edit LegalDocument">
              <IconButton onClick={handleEdit} color="primary">
                <EditIcon />
              </IconButton>
            </Tooltip>
          )}

          {showDeleteButton && onDelete && (
            <Tooltip title="Delete LegalDocument">
              <IconButton onClick={handleDelete} color="error">
                <DeleteIcon />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      </Box>

      {/* Detail Content */}
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={3}>
          {/* Basic Information Section */}
          <Grid size={12}>
            <section data-testid="basic-info-section" aria-label="Basic Information">
              <Typography variant="h6" component="h2" gutterBottom>
                Basic Information
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                {/* ID field */}
                <DetailField
                  label="ID:"
                  value={legalDocument.id}
                  testId="field-id"
                />

                {/* User Id field */}
                <DetailField
                  label="User Id:"
                  value={displayValue(legalDocument.user_id)}
                  testId="field-user-id"
                />

                {/* Template Id field */}
                <DetailField
                  label="Template Id:"
                  value={displayValue(legalDocument.template_id)}
                  testId="field-template-id"
                />

                {/* Investor Id field */}
                <DetailField
                  label="Investor Id:"
                  value={displayValue(legalDocument.investor_id)}
                  testId="field-investor-id"
                />

                {/* Document Type field */}
                <DetailField
                  label="Document Type:"
                  value={displayValue(legalDocument.document_type)}
                  testId="field-document-type"
                />

                {/* Title field */}
                <DetailField
                  label="Title:"
                  value={displayValue(legalDocument.title)}
                  testId="field-title"
                />

                {/* Status field */}
                <DetailField
                  label="Status:"
                  value={displayValue(legalDocument.status)}
                  testId="field-status"
                />

                {/* Configuration field */}
                <DetailField
                  label="Configuration:"
                  value={legalDocument.configuration ? JSON.stringify(legalDocument.configuration, null, 2) : '-'}
                  testId="field-configuration"
                />

                {/* Content Markdown field */}
                <DetailField
                  label="Content Markdown:"
                  value={displayValue(legalDocument.content_markdown)}
                  testId="field-content-markdown"
                />

                {/* Content Html field */}
                <DetailField
                  label="Content Html:"
                  value={displayValue(legalDocument.content_html)}
                  testId="field-content-html"
                />

                {/* File Path Docx field */}
                <DetailField
                  label="File Path Docx:"
                  value={displayValue(legalDocument.file_path_docx)}
                  testId="field-file-path-docx"
                />

                {/* File Path Pdf field */}
                <DetailField
                  label="File Path Pdf:"
                  value={displayValue(legalDocument.file_path_pdf)}
                  testId="field-file-path-pdf"
                />

                {/* Version field */}
                <DetailField
                  label="Version:"
                  value={formatNumber(legalDocument.version)}
                  testId="field-version"
                />

                {/* Generated At field */}
                <DetailField
                  label="Generated At:"
                  value={displayValue(legalDocument.generated_at)}
                  testId="field-generated-at"
                />

              </Box>
            </section>
          </Grid>

          {/* Status Section */}
          <Grid size={12}>
            <Divider sx={{ my: 2 }} />
            <section data-testid="status-section" aria-label="Status">
              <Typography variant="h6" component="h2" gutterBottom>
                Status
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <div data-testid="field-status">
                  <label>
                    <Typography variant="body2" color="text.secondary" component="span">
                      Status:
                    </Typography>
                  </label>
                  <span className={legalDocument.is_active ? 'active-badge' : 'inactive-badge'}>
                    <Typography variant="body1" component="span">
                      {legalDocument.is_active ? 'Active' : 'Inactive'}
                    </Typography>
                  </span>
                </div>
              </Box>
            </section>
          </Grid>

          {/* Audit Trail Section */}
          <Grid size={12}>
            <Divider sx={{ my: 2 }} />
            <section data-testid="audit-trail-section" aria-label="Audit Trail">
              <Typography variant="h6" component="h2" gutterBottom>
                Audit Trail
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <DetailField
                  label="Created At:"
                  value={formatDate(legalDocument.created_at)}
                  testId="field-created-at"
                />

                <DetailField
                  label="Updated At:"
                  value={formatDate(legalDocument.updated_at)}
                  testId="field-updated-at"
                />

              </Box>
            </section>
          </Grid>
        </Grid>
      </Paper>
    </div>
  );
}

// Default export for convenience
export default LegalDocumentDetail;
