/**
 * VestingScheduleForm Component
 *
 * Form component for creating and editing vesting_schedules.
 * Uses React Hook Form with Controller pattern for form state management.
 *
 * Features:
 * - Create and Edit mode support
 * - Form validation with error messages
 * - Material UI components
 * - Loading state handling
 * - Accessible form fields (WCAG 2.1 Level AA)
 * - Modal wrapper support (form_display: modal)
 *
 * Vesting schedule for equity grants — cliff period, total period, and acceleration triggers
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:55.668337Z
 */

import React, { useMemo, useEffect } from 'react';
import { useForm, Controller, FormProvider } from 'react-hook-form';
import {
  Alert as MuiAlert,
  Box,
  Grid,
  TextField,
  Button,
  CircularProgress,
  Dialog,
  DialogTitle,
  DialogContent,
  IconButton,
} from '@mui/material';
import { Close as CloseIcon } from '@mui/icons-material';
import type { VestingScheduleCreateRequest, VestingSchedule } from '../types/vesting_schedule.types';
import { useNotification } from '../contexts/NotificationContext';
// Form select components for foreign key fields
import { FormEquityGrantSelect } from './FormEquityGrantSelect';

// ============================================================================
// Types
// ============================================================================

/**
 * Form data type for VestingSchedule
 */
export type VestingScheduleFormData = VestingScheduleCreateRequest;

/**
 * Props for VestingScheduleForm component
 */
export interface VestingScheduleFormProps {
  /** Existing vesting_schedule data for edit mode (optional) */
  vestingSchedule?: VestingSchedule;
  /** Form submission handler (can be sync or async) */
  onSubmit: (data: VestingScheduleFormData) => void | Promise<void>;
  /** Cancel handler */
  onCancel: () => void;
  /** Loading state (disables form during submission) */
  isLoading?: boolean;
  /** Custom className for the form container */
  className?: string;
}

/**
 * Props for VestingScheduleFormModal component (modal wrapper)
 */
export interface VestingScheduleFormModalProps extends VestingScheduleFormProps {
  /** Whether the modal is open */
  open: boolean;
  /** Handler called when the modal requests to be closed */
  onClose: () => void;
  /** Optional title override for the modal */
  title?: string;
}


// ============================================================================
// Constants
// ============================================================================

/**
 * Default form values for creating a new vesting_schedule
 */
const DEFAULT_FORM_VALUES: Partial<VestingScheduleFormData> = {
  equity_grant_id: '',
  total_period_months: undefined,
  cliff_months: undefined,
  start_date: '',
  acceleration_trigger: "none",
};

// ============================================================================
// Component
// ============================================================================

/**
 * VestingScheduleForm Component
 *
 * Renders a form for creating or editing vesting_schedules.
 * Uses React Hook Form with Controller pattern for form state management.
 *
 * @example
 * ```tsx
 * // Create mode
 * <VestingScheduleForm
 *   onSubmit={handleCreate}
 *   onCancel={handleCancel}
 *   isLoading={isCreating}
 * />
 *
 * // Edit mode
 * <VestingScheduleForm
 *   vestingSchedule={existingVestingSchedule}
 *   onSubmit={handleUpdate}
 *   onCancel={handleCancel}
 *   isLoading={isUpdating}
 * />
 * ```
 */
export function VestingScheduleForm({
  vestingSchedule,
  onSubmit,
  onCancel,
  isLoading = false,
  className = '',
}: VestingScheduleFormProps): React.ReactElement {
  // Determine if we're in edit mode
  const isEditMode = Boolean(vestingSchedule);

  // Notification context for showing success/error messages
  const { showSuccess, showError } = useNotification();

  // Build default values from existing entity or defaults
  const defaultValues = useMemo<Partial<VestingScheduleFormData>>(() => {
    if (vestingSchedule) {
      // Edit mode: use existing entity values
      return {
        equity_grant_id: vestingSchedule.equity_grant_id,
        total_period_months: vestingSchedule.total_period_months,
        cliff_months: vestingSchedule.cliff_months,
        start_date: vestingSchedule.start_date,
        acceleration_trigger: vestingSchedule.acceleration_trigger,
      };
    }
    // Create mode: use defaults
    return DEFAULT_FORM_VALUES;
  }, [vestingSchedule]);

  // Initialize React Hook Form
  const methods = useForm<VestingScheduleFormData>({
    defaultValues,
    mode: 'onBlur',
  });

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = methods;

  // Reset form when entity data changes (e.g., switching from create to edit mode)
  useEffect(() => {
    reset(defaultValues);
  }, [defaultValues, reset]);

  // Log validation errors to console for debugging
  useEffect(() => {
    if (Object.keys(errors).length > 0) {
      console.log('[VestingScheduleForm] Validation errors:', errors);
    }
  }, [errors]);
  // -------------------------------------------------------------------------
  // Form Submission
  // -------------------------------------------------------------------------

  const handleFormSubmit = async (data: VestingScheduleFormData) => {
    console.log('[VestingScheduleForm] Submitting:', { data, isEditMode });
    try {
      const result = await onSubmit(data);
      console.log('[VestingScheduleForm] Form submission successful', { data, result, isEditMode });
      // Show success notification for create operation
      if (!isEditMode) {
        showSuccess('VestingSchedule created successfully');
      }
    } catch (error) {
      // Log full error details to console for debugging
      console.error('[VestingScheduleForm] Form submission failed', {
        error,
        errorMessage: error instanceof Error ? error.message : String(error),
        errorStack: error instanceof Error ? error.stack : undefined,
        data,
        isEditMode,
      });
      // Show error notification on failure
      const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
      showError(`Failed to ${isEditMode ? 'update' : 'create'} VestingSchedule: ${errorMessage}`);
    }
  };

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------

  // Count validation errors
  const errorCount = Object.keys(errors).length;

  return (
    <FormProvider {...methods}>
      <Box
        component="form"
        onSubmit={handleSubmit(handleFormSubmit)}
        className={className}
        data-testid="form-vesting_schedule"
        noValidate
      >
        {/* Error Summary Alert */}
        {errorCount > 0 && (
          <MuiAlert
            severity="error"
            sx={{ mb: 3 }}
            data-testid="form-errors-summary"
          >
            Please fix {errorCount} error{errorCount !== 1 ? 's' : ''} before submitting
          </MuiAlert>
        )}

        <Grid container spacing={3}>
          {/* Equity Grant Id field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* Foreign key field - renders as dropdown select */}
            <FormEquityGrantSelect
              name="equity_grant_id"
              label="Equity Grant"
              required={false}
              disabled={isLoading}
            />
          </Grid>

          {/* Total Period Months field */}
          <Grid size={{ xs: 12, md: 6 }}>
            <Controller
              name="total_period_months"
              control={control}
              rules={{
                required: 'Total Period Months is required',
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  type="number"
                  label="Total Period Months"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Total vesting period in months (12-60, typically 48 for 4-year vest)"}
                  placeholder=""
                  value={formField.value ?? ''}
                  onChange={(e) => {
                    const val = e.target.value;
                    formField.onChange(val === '' ? undefined : parseFloat(val));
                  }}
                  inputProps={{
                    step: 'any',
                  }}
                  data-testid="field-total-period-months"
                />
              )}
            />
          </Grid>

          {/* Cliff Months field */}
          <Grid size={{ xs: 12, md: 6 }}>
            <Controller
              name="cliff_months"
              control={control}
              rules={{
                required: 'Cliff Months is required',
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  type="number"
                  label="Cliff Months"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Cliff period in months (0-24, typically 12 for 1-year cliff)"}
                  placeholder=""
                  value={formField.value ?? ''}
                  onChange={(e) => {
                    const val = e.target.value;
                    formField.onChange(val === '' ? undefined : parseFloat(val));
                  }}
                  inputProps={{
                    step: 'any',
                  }}
                  data-testid="field-cliff-months"
                />
              )}
            />
          </Grid>

          {/* Start Date field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="start_date"
              control={control}
              rules={{
                required: 'Start Date is required',
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Start Date"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-start-date"
                />
              )}
            />
          </Grid>

          {/* Acceleration Trigger field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="acceleration_trigger"
              control={control}
              rules={{
                required: 'Acceleration Trigger is required',
                maxLength: { value: 20, message: 'Acceleration Trigger must be at most 20 characters' },
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Acceleration Trigger"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Acceleration event type on change of control"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-acceleration-trigger"
                />
              )}
            />
          </Grid>

          {/* Form Actions */}
          <Grid size={12}>
            <Box display="flex" gap={2} pt={2}>
              <Button
                type="submit"
                variant="contained"
                color="primary"
                disabled={isLoading}
                startIcon={isLoading ? <CircularProgress size={20} /> : undefined}
                data-testid="submit-button"
              >
                {isLoading
                  ? 'Saving...'
                  : isEditMode
                    ? 'Update VestingSchedule'
                    : 'Create VestingSchedule'}
              </Button>

              <Button
                type="button"
                variant="outlined"
                onClick={onCancel}
                disabled={isLoading}
                data-testid="cancel-button"
              >
                Cancel
              </Button>
            </Box>
          </Grid>
        </Grid>
      </Box>
    </FormProvider>
  );
}

// ============================================================================
// Modal Wrapper Component
// ============================================================================

/**
 * VestingScheduleFormModal Component
 *
 * Wraps the VestingScheduleForm in a Material UI Dialog for modal display.
 * Use this component when you want to show the form in a popup dialog.
 *
 * @example
 * ```tsx
 * <VestingScheduleFormModal
 *   open={isModalOpen}
 *   onClose={handleClose}
 *   onSubmit={handleCreate}
 *   onCancel={handleClose}
 *   isLoading={isCreating}
 * />
 * ```
 */
export function VestingScheduleFormModal({
  open,
  onClose,
  title,
  vestingSchedule,
  onSubmit,
  onCancel,
  isLoading = false,
  className = '',
}: VestingScheduleFormModalProps): React.ReactElement {
  const isEditMode = Boolean(vestingSchedule);
  const modalTitle = title ?? (isEditMode ? 'Edit VestingSchedule' : 'Create VestingSchedule');

  // Handle modal close - prevent closing during loading
  const handleClose = () => {
    if (!isLoading) {
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="md"
      fullWidth
      data-testid="modal-vesting_schedule-form"
    >
      <DialogTitle sx={{ m: 0, p: 2, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        {modalTitle}
        <IconButton
          aria-label="close"
          onClick={handleClose}
          disabled={isLoading}
          data-testid="modal-close-button"
          sx={{ color: (theme) => theme.palette.grey[500] }}
        >
          <CloseIcon />
        </IconButton>
      </DialogTitle>
      <DialogContent dividers>
        <VestingScheduleForm
          vestingSchedule={vestingSchedule}
          onSubmit={onSubmit}
          onCancel={onCancel}
          isLoading={isLoading}
          className={className}
        />
      </DialogContent>
    </Dialog>
  );
}


// Default export for convenience
export default VestingScheduleForm;
