"""Platform integration for billing-service.

Initializes BaseModel ORM with database connection and model registry.
Generated by VentureStrat CLI.
"""

import os
import structlog
from venturestrat.models import BaseModel
from venturestrat.models.registry import ModelRegistry

logger = structlog.get_logger(__name__)


def init_platform(registry_url: str = None, platform_mode: str = 'integrated'):
    """
    Initialize platform integration with BaseModel ORM.

    This function must be called during service startup to configure:
    - Database connection via ModelRegistry
    - Database table creation (auto-migration)
    - Security settings
    - Schema registry connection (optional)

    Args:
        registry_url: URL for schema registry service (optional)
        platform_mode: 'integrated' (full platform) or 'standalone' (database only)
    """
    logger.info("platform_init_start", mode=platform_mode)

    if platform_mode not in ['integrated', 'standalone']:
        logger.warning(
            "platform_mode_invalid",
            mode=platform_mode,
            message="Using standalone mode"
        )
        platform_mode = 'standalone'

    # Get database URL from environment
    database_url = os.getenv('DATABASE_URL')
    if not database_url:
        error_msg = "DATABASE_URL environment variable is required for BaseModel ORM"
        logger.error("database_url_missing", error=error_msg)
        raise ValueError(error_msg)

    # Initialize ModelRegistry with database connection
    try:
        service_name = os.getenv('SERVICE_NAME', 'billing-service')

        logger.info(
            "model_registry_init_start",
            database_url=database_url.split('@')[-1],  # Hide credentials in logs
            service_name=service_name
        )

        ModelRegistry.initialize(
            database_url=database_url,
            service_name=service_name
        )

        logger.info("model_registry_initialized")

        # CRITICAL: Disable security BEFORE importing models
        # Models inherit _security_enabled at import time, so this must happen first
        BaseModel._security_enabled = False
        logger.info("security_disabled_before_model_import")

        # Import ORM models AFTER security is disabled
        # This ensures models get _security_enabled = False
        try:
            from billing_service.infrastructure import orm  # noqa: F401
            logger.info("orm_models_imported_with_security_disabled")
        except Exception as import_error:
            logger.error("orm_models_import_failed", error=str(import_error))
            raise

    except Exception as e:
        logger.error(
            "model_registry_init_failed",
            error=str(e),
            error_type=type(e).__name__
        )
        raise RuntimeError(f"Failed to initialize ModelRegistry: {e}") from e

    # Create database tables from BaseModel metadata
    try:
        logger.info("database_tables_create_start")

        metadata = ModelRegistry.get_metadata()
        engine = ModelRegistry.get_engine()

        # Get all unique schemas needed by models and create them
        try:
            from sqlalchemy import text
            registered_models = ModelRegistry.get_all_models()
            schemas_needed = set()
            for model_name, model_class in registered_models.items():
                if hasattr(model_class, '_schema') and model_class._schema:
                    schemas_needed.add(model_class._schema)

            # Create all schemas
            with engine.connect() as conn:
                for schema in schemas_needed:
                    conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema}"))
                conn.commit()
            logger.info("schemas_created", schemas=list(schemas_needed))
        except Exception as schema_error:
            logger.warning("schema_creation_failed", error=str(schema_error))

        # Reflect registry.tenants table for cross-schema foreign keys
        # BaseModel auto-injects tenant_id with FK to registry.tenants
        try:
            from sqlalchemy import Table
            Table('tenants', metadata, autoload_with=engine, schema='registry')
            logger.info("registry_tenants_reflected")
        except Exception as reflect_error:
            logger.warning("registry_tenants_reflect_failed", error=str(reflect_error))

        # Register SQLAlchemy tables for all BaseModel classes
        registered_models = ModelRegistry.get_all_models()
        table_count = 0
        for model_name, model_class in registered_models.items():
            try:
                table = model_class._create_table(metadata)
                table_count += 1
                logger.debug(
                    "table_registered",
                    model=model_name,
                    table_name=table.name,
                    schema=table.schema
                )
            except Exception as table_error:
                logger.warning(
                    "table_registration_failed",
                    model=model_name,
                    error=str(table_error)
                )

        logger.info("tables_registered", count=table_count)

        # Create all tables (idempotent - won't recreate existing tables)
        metadata.create_all(engine)

        logger.info("database_tables_created", count=table_count)

    except Exception as e:
        logger.error(
            "database_tables_create_failed",
            error=str(e),
            error_type=type(e).__name__
        )
        # Don't raise - tables might already exist
        logger.warning("continuing_with_existing_tables")

    # Connect to schema registry (if in integrated mode and URL provided)
    if platform_mode == 'integrated' and registry_url:
        try:
            logger.info("schema_registry_connect_start", url=registry_url)
            # TODO: Implement schema registry connection when available
            # from venturestrat_registry.client import RegistryClient
            # registry = RegistryClient(url=registry_url)
            # BaseModel._registry = registry
            logger.info("schema_registry_skipped", reason="not_implemented")
        except Exception as e:
            logger.warning(
                "schema_registry_connect_failed",
                error=str(e),
                message="Continuing without schema registry"
            )

    logger.info("platform_init_complete", mode=platform_mode)


def get_current_tenant(tenant_id: str = None) -> str:
    """
    Get current tenant ID for multi-tenant operations.

    Args:
        tenant_id: Optional tenant ID to use

    Returns:
        Tenant ID string
    """
    if tenant_id:
        return tenant_id

    # Try environment variable
    tenant_id = os.getenv('DEFAULT_TENANT_ID')
    if tenant_id:
        return tenant_id

    # Fallback to default
    return 'default-tenant-00000000'
