/**
 * UserRole Query Key Factory
 *
 * Centralized query key factory for React Query cache management.
 * Provides consistent, type-safe query keys for all user_role queries.
 *
 * Query keys follow a hierarchical structure for efficient cache invalidation:
 * - ['userroles'] - All user_role queries
 * - ['userroles', 'list'] - All list queries
 * - ['userroles', 'list', { filters }] - Specific filtered list
 * - ['userroles', 'detail', id] - Specific user_role by ID
 *
 * @example
 * ```typescript
 * import { user_roleKeys } from './queryKeys';
 *
 * // Use in useQuery
 * const { data } = useQuery({
 *   queryKey: user_roleKeys.list({ is_active: true }),
 *   queryFn: () => user_roleService.getAll({ is_active: true }),
 * });
 *
 * // Invalidate all user_role queries
 * queryClient.invalidateQueries({ queryKey: user_roleKeys.all });
 *
 * // Invalidate specific user_role
 * queryClient.invalidateQueries({ queryKey: user_roleKeys.detail('uuid') });
 * ```
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-02-23T11:13:16.473867Z
 */

import type { UserRoleFilterOptions } from '../types/user_role.types';

/**
 * Root query key for UserRole entity
 * Used as namespace prefix for all user_role queries
 */
const USER_ROLE_ROOT = 'userroles' as const;

/**
 * UserRole Query Keys
 *
 * Hierarchical query key factory for user_role queries:
 * - all: Base key for all user_role queries
 * - lists: All list queries (for bulk invalidation)
 * - list(filters): Specific filtered list
 * - details: All detail queries
 * - detail(id): Specific user_role by ID
 * - dropdown(activeOnly): Dropdown options query
 *
 * @example
 * ```typescript
 * // List with filters
 * const key = user_roleKeys.list({ is_active: true });
 * // Result: ['userroles', 'list', { is_active: true }]
 *
 * // Detail by ID
 * const key = user_roleKeys.detail('uuid-here');
 * // Result: ['userroles', 'detail', 'uuid-here']
 *
 * // Invalidate all user_role data
 * queryClient.invalidateQueries({ queryKey: user_roleKeys.all });
 * ```
 */
export const user_roleKeys = {
  /**
   * Base key for all user_role queries
   * Use this to invalidate all user_role-related queries at once
   *
   * @example
   * ```typescript
   * // Invalidate everything after a major change
   * queryClient.invalidateQueries({ queryKey: user_roleKeys.all });
   * ```
   */
  all: [USER_ROLE_ROOT] as const,

  /**
   * Key for all list queries
   * Use this to invalidate all list queries without affecting detail queries
   *
   * @returns Query key tuple for list namespace
   *
   * @example
   * ```typescript
   * // Invalidate all list queries
   * queryClient.invalidateQueries({ queryKey: user_roleKeys.lists() });
   * ```
   */
  lists: () => [...user_roleKeys.all, 'list'] as const,

  /**
   * Key for a specific filtered list query
   * Include filters in the key to enable automatic re-fetching when filters change
   *
   * @param filters - Optional filter options for the query
   * @returns Query key tuple including filters
   *
   * @example
   * ```typescript
   * // List all active
   * const key = user_roleKeys.list({ is_active: true });
   *
   * // List with search
   * const key = user_roleKeys.list({ search: 'test' });
   *
   * // Unfiltered list
   * const key = user_roleKeys.list();
   * ```
   */
  list: (filters?: UserRoleFilterOptions) =>
    [...user_roleKeys.lists(), filters ?? {}] as const,

  /**
   * Key for all detail queries
   * Use this to invalidate all detail queries without affecting list queries
   *
   * @returns Query key tuple for detail namespace
   *
   * @example
   * ```typescript
   * // Invalidate all detail queries
   * queryClient.invalidateQueries({ queryKey: user_roleKeys.details() });
   * ```
   */
  details: () => [...user_roleKeys.all, 'detail'] as const,

  /**
   * Key for a specific user_role by ID
   * Use this for fetching and invalidating individual user_role records
   *
   * @param id - UserRole ID (UUID)
   * @returns Query key tuple for specific user_role
   *
   * @example
   * ```typescript
   * // Fetch specific user_role
   * const { data } = useQuery({
   *   queryKey: user_roleKeys.detail('uuid-here'),
   *   queryFn: () => user_roleService.getById('uuid-here'),
   * });
   *
   * // Invalidate after update
   * queryClient.invalidateQueries({
   *   queryKey: user_roleKeys.detail('uuid-here')
   * });
   * ```
   */
  detail: (id: string) => [...user_roleKeys.details(), id] as const,

  /**
   * Key for dropdown options query
   * Separate key allows independent caching of dropdown data
   *
   * @param activeOnly - Whether to include only active user_roles (default: true)
   * @returns Query key tuple for dropdown query
   *
   * @example
   * ```typescript
   * // Active items only (default)
   * const key = user_roleKeys.dropdown();
   *
   * // Include inactive items
   * const key = user_roleKeys.dropdown(false);
   * ```
   */
  dropdown: (activeOnly: boolean = true) =>
    [...user_roleKeys.all, 'dropdown', { activeOnly }] as const,

  /**
   * UserRoles filtered by user ID
   *
   * @param userId - User ID (UUID)
   * @returns Query key tuple
   */
  byUser: (userId: string) =>
    [...user_roleKeys.all, 'by-user', userId] as const,

  /**
   * UserRoles filtered by role ID
   *
   * @param roleId - Role ID (UUID)
   * @returns Query key tuple
   */
  byRole: (roleId: string) =>
    [...user_roleKeys.all, 'by-role', roleId] as const,

  /**
   * UserRoles filtered by tenant ID
   *
   * @param tenantId - Tenant ID (UUID)
   * @returns Query key tuple
   */
  byTenant: (tenantId: string) =>
    [...user_roleKeys.all, 'by-tenant', tenantId] as const,
} as const;

/**
 * Type representing any valid UserRole query key
 * Useful for typing query key arrays in generic contexts
 */
export type UserRoleQueryKey =
  | typeof user_roleKeys.all
  | ReturnType<typeof user_roleKeys.lists>
  | ReturnType<typeof user_roleKeys.list>
  | ReturnType<typeof user_roleKeys.details>
  | ReturnType<typeof user_roleKeys.detail>
  | ReturnType<typeof user_roleKeys.dropdown>
;

/**
 * Default export for convenience
 */
export default user_roleKeys;
