"""LifecycleEmail Application Service - Generated by Code Generator v1.0.0"""

from typing import List, Optional
from uuid import UUID
import structlog

from outreach_service.infrastructure.repositories.lifecycle_email_repository import (
    LifecycleEmailRepository,
)
from outreach_service.infrastructure.orm.lifecycle_email import LifecycleEmail
from outreach_service.schemas.lifecycle_email import (
    LifecycleEmailCreate,
    LifecycleEmailUpdate,
    LifecycleEmailResponse,
)
from outreach_service.integrations.events import event_publisher
from outreach_service.integrations.metrics import entity_operations_total

logger = structlog.get_logger(__name__)


class LifecycleEmailService:
    """Application service for LifecycleEmail use cases."""

    def __init__(self, session=None):
        """Initialize service with repository."""
        self.repository = LifecycleEmailRepository(session)

    async def create_lifecycle_email(
        self, data: LifecycleEmailCreate, tenant_id: str = None
    ) -> LifecycleEmailResponse:
        """Create new LifecycleEmail."""
        try:
            data_dict = data.model_dump()
            if tenant_id:
                data_dict["tenant_id"] = tenant_id

            # BaseModel.create() returns the created instance directly
            created = await self.repository.create(**data_dict)

            # Publish event
            await event_publisher.publish(
                entity_name="lifecycle_email",
                action="created",
                data=created.to_dict(),
                tenant_id=tenant_id,
            )

            # Track metric
            entity_operations_total.labels(
                entity="lifecycle_email", operation="create", status="success"
            ).inc()

            # Convert BaseModel to dict for response
            return LifecycleEmailResponse(**created.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="lifecycle_email", operation="create", status="error"
            ).inc()
            logger.error("create_lifecycle_email_failed", error=str(e))
            raise

    async def get_lifecycle_email(self, id: UUID) -> Optional[LifecycleEmailResponse]:
        """Get LifecycleEmail by ID."""
        orm_obj = await self.repository.get_by_id(id)
        return LifecycleEmailResponse(**orm_obj.to_dict()) if orm_obj else None

    async def list_lifecycle_emails(
        self, skip: int = 0, limit: int = 100
    ) -> List[LifecycleEmailResponse]:
        """List LifecycleEmails with pagination."""
        orm_objs = await self.repository.get_all(skip, limit)
        return [LifecycleEmailResponse(**obj.to_dict()) for obj in orm_objs]

    async def update_lifecycle_email(
        self, id: UUID, data: LifecycleEmailUpdate
    ) -> Optional[LifecycleEmailResponse]:
        """Update LifecycleEmail."""
        try:
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return None

            # Update fields from DTO
            for key, value in data.model_dump(exclude_unset=True).items():
                setattr(orm_obj, key, value)

            # BaseModel.save() returns self
            updated = await self.repository.update(orm_obj)

            # Publish event
            await event_publisher.publish(
                entity_name="lifecycle_email",
                action="updated",
                data=updated.to_dict(),
                tenant_id=getattr(updated, "tenant_id", None),
            )

            # Track metric
            entity_operations_total.labels(
                entity="lifecycle_email", operation="update", status="success"
            ).inc()

            return LifecycleEmailResponse(**updated.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="lifecycle_email", operation="update", status="error"
            ).inc()
            logger.error("update_lifecycle_email_failed", id=str(id), error=str(e))
            raise

    async def delete_lifecycle_email(self, id: UUID) -> bool:
        """Delete LifecycleEmail."""
        try:
            # Get entity before deletion
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return False

            entity_data = orm_obj.to_dict()

            # Delete
            deleted = await self.repository.delete(id)

            if deleted:
                # Publish event
                await event_publisher.publish(
                    entity_name="lifecycle_email",
                    action="deleted",
                    data=entity_data,
                    tenant_id=entity_data.get("tenant_id"),
                )

                # Track metric
                entity_operations_total.labels(
                    entity="lifecycle_email", operation="delete", status="success"
                ).inc()

            return deleted

        except Exception as e:
            entity_operations_total.labels(
                entity="lifecycle_email", operation="delete", status="error"
            ).inc()
            logger.error("delete_lifecycle_email_failed", id=str(id), error=str(e))
            raise

    async def search_lifecycle_emails(
        self, domain: list = None, skip: int = 0, limit: int = 100
    ) -> List[LifecycleEmailResponse]:
        """
        Search LifecycleEmails with domain filtering.

        Args:
            domain: domain filter (e.g., [('field', '=', 'value')])
            skip: Offset for pagination
            limit: Maximum records to return

        Returns:
            List of matching LifecycleEmail instances
        """
        orm_objs = await self.repository.search(domain, skip, limit)
        return [LifecycleEmailResponse(**obj.to_dict()) for obj in orm_objs]

    async def count_lifecycle_emails(self, domain: list = None) -> int:
        """
        Count LifecycleEmails matching domain.

        Args:
            domain: Optional domain filter

        Returns:
            Number of matching records
        """
        return await self.repository.count(domain)

    async def bulk_create_lifecycle_emails(
        self, records_data: List[LifecycleEmailCreate]
    ) -> List[LifecycleEmailResponse]:
        """
        Create multiple LifecycleEmails efficiently.

        Args:
            records_data: List of create DTOs

        Returns:
            List of created LifecycleEmail instances
        """
        # Convert DTOs to dicts
        data_dicts = [record.model_dump() for record in records_data]

        # Bulk create
        created_objs = await self.repository.bulk_create(data_dicts)

        return [LifecycleEmailResponse(**obj.to_dict()) for obj in created_objs]
