/**
 * PermissionForm Component
 *
 * Form component for creating and editing permissions.
 * Uses React Hook Form with Controller pattern for form state management.
 *
 * Features:
 * - Create and Edit mode support
 * - Form validation with error messages
 * - Material UI components
 * - Loading state handling
 * - Accessible form fields (WCAG 2.1 Level AA)
 * - Modal wrapper support (form_display: modal)
 *
 * Granular permission for resource access control
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-02-23T11:13:14.613520Z
 */

import React, { useMemo, useEffect } from 'react';
import { useForm, Controller, FormProvider } from 'react-hook-form';
import {
  Alert as MuiAlert,
  Box,
  Grid,
  TextField,
  Button,
  CircularProgress,
  Dialog,
  DialogTitle,
  DialogContent,
  IconButton,
} from '@mui/material';
import { Close as CloseIcon } from '@mui/icons-material';
import type { PermissionCreateRequest, Permission } from '../types/permission.types';
import { useNotification } from '../contexts/NotificationContext';

// ============================================================================
// Types
// ============================================================================

/**
 * Form data type for Permission
 */
export type PermissionFormData = PermissionCreateRequest;

/**
 * Props for PermissionForm component
 */
export interface PermissionFormProps {
  /** Existing permission data for edit mode (optional) */
  permission?: Permission;
  /** Form submission handler (can be sync or async) */
  onSubmit: (data: PermissionFormData) => void | Promise<void>;
  /** Cancel handler */
  onCancel: () => void;
  /** Loading state (disables form during submission) */
  isLoading?: boolean;
  /** Custom className for the form container */
  className?: string;
}

/**
 * Props for PermissionFormModal component (modal wrapper)
 */
export interface PermissionFormModalProps extends PermissionFormProps {
  /** Whether the modal is open */
  open: boolean;
  /** Handler called when the modal requests to be closed */
  onClose: () => void;
  /** Optional title override for the modal */
  title?: string;
}


// ============================================================================
// Constants
// ============================================================================

/**
 * Default form values for creating a new permission
 */
const DEFAULT_FORM_VALUES: Partial<PermissionFormData> = {
  resource: '',
  action: '',
  code: '',
  description: '',
  service_name: '',
  tenant_id: '',
};

// ============================================================================
// Component
// ============================================================================

/**
 * PermissionForm Component
 *
 * Renders a form for creating or editing permissions.
 * Uses React Hook Form with Controller pattern for form state management.
 *
 * @example
 * ```tsx
 * // Create mode
 * <PermissionForm
 *   onSubmit={handleCreate}
 *   onCancel={handleCancel}
 *   isLoading={isCreating}
 * />
 *
 * // Edit mode
 * <PermissionForm
 *   permission={existingPermission}
 *   onSubmit={handleUpdate}
 *   onCancel={handleCancel}
 *   isLoading={isUpdating}
 * />
 * ```
 */
export function PermissionForm({
  permission,
  onSubmit,
  onCancel,
  isLoading = false,
  className = '',
}: PermissionFormProps): React.ReactElement {
  // Determine if we're in edit mode
  const isEditMode = Boolean(permission);

  // Notification context for showing success/error messages
  const { showSuccess, showError } = useNotification();

  // Build default values from existing entity or defaults
  const defaultValues = useMemo<Partial<PermissionFormData>>(() => {
    if (permission) {
      // Edit mode: use existing entity values
      return {
        resource: permission.resource,
        action: permission.action,
        code: permission.code,
        description: permission.description ?? '',
        service_name: permission.service_name ?? '',
        tenant_id: permission.tenant_id,
      };
    }
    // Create mode: use defaults
    return DEFAULT_FORM_VALUES;
  }, [permission]);

  // Initialize React Hook Form
  const methods = useForm<PermissionFormData>({
    defaultValues,
    mode: 'onBlur',
  });

  const {
    control,
    handleSubmit,
    formState: { errors },
    reset,
  } = methods;

  // Reset form when entity data changes (e.g., switching from create to edit mode)
  useEffect(() => {
    reset(defaultValues);
  }, [defaultValues, reset]);

  // Log validation errors to console for debugging
  useEffect(() => {
    if (Object.keys(errors).length > 0) {
      console.log('[PermissionForm] Validation errors:', errors);
    }
  }, [errors]);
  // -------------------------------------------------------------------------
  // Form Submission
  // -------------------------------------------------------------------------

  const handleFormSubmit = async (data: PermissionFormData) => {
    console.log('[PermissionForm] Submitting:', { data, isEditMode });
    try {
      const result = await onSubmit(data);
      console.log('[PermissionForm] Form submission successful', { data, result, isEditMode });
      // Show success notification for create operation
      if (!isEditMode) {
        showSuccess('Permission created successfully');
      }
    } catch (error) {
      // Log full error details to console for debugging
      console.error('[PermissionForm] Form submission failed', {
        error,
        errorMessage: error instanceof Error ? error.message : String(error),
        errorStack: error instanceof Error ? error.stack : undefined,
        data,
        isEditMode,
      });
      // Show error notification on failure
      const errorMessage = error instanceof Error ? error.message : 'An unexpected error occurred';
      showError(`Failed to ${isEditMode ? 'update' : 'create'} Permission: ${errorMessage}`);
    }
  };

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------

  // Count validation errors
  const errorCount = Object.keys(errors).length;

  return (
    <FormProvider {...methods}>
      <Box
        component="form"
        onSubmit={handleSubmit(handleFormSubmit)}
        className={className}
        data-testid="form-permission"
        noValidate
      >
        {/* Error Summary Alert */}
        {errorCount > 0 && (
          <MuiAlert
            severity="error"
            sx={{ mb: 3 }}
            data-testid="form-errors-summary"
          >
            Please fix {errorCount} error{errorCount !== 1 ? 's' : ''} before submitting
          </MuiAlert>
        )}

        <Grid container spacing={3}>
          {/* Resource field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="resource"
              control={control}
              rules={{
                required: 'Resource is required',
                maxLength: { value: 100, message: 'Resource must be at most 100 characters' },
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Resource"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Resource name (e.g. trade, position, risk)"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-resource"
                />
              )}
            />
          </Grid>

          {/* Action field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="action"
              control={control}
              rules={{
                required: 'Action is required',
                maxLength: { value: 50, message: 'Action must be at most 50 characters' },
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Action"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Action type (e.g. create, read, update, delete, approve)"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-action"
                />
              )}
            />
          </Grid>

          {/* Code field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="code"
              control={control}
              rules={{
                required: 'Code is required',
                maxLength: { value: 100, message: 'Code must be at most 100 characters' },
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Code"
                  fullWidth
                  required
                  disabled={isLoading || isEditMode}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Unique permission code (e.g. trade:create)" || (isEditMode ? "Code cannot be changed after creation" : undefined)}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-code"
                />
              )}
            />
          </Grid>

          {/* Description field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="description"
              control={control}
              rules={{
                required: 'Description is required',
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Description"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Human-readable permission description"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-description"
                />
              )}
            />
          </Grid>

          {/* Service Name field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="service_name"
              control={control}
              rules={{
                required: 'Service Name is required',
                maxLength: { value: 100, message: 'Service Name must be at most 100 characters' },
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Service Name"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Service this permission applies to"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-service-name"
                />
              )}
            />
          </Grid>

          {/* Tenant Id field */}
          <Grid size={{ xs: 12, md: 6 }}>
            {/* 4. Default: plain text field */}
            <Controller
              name="tenant_id"
              control={control}
              rules={{
                required: 'Tenant Id is required',
              }}
              render={({ field: formField, fieldState }) => (
                <TextField
                  {...formField}
                  label="Tenant Id"
                  fullWidth
                  required
                  disabled={isLoading}
                  error={!!fieldState.error}
                  helperText={fieldState.error?.message || "Owning tenant"}
                  placeholder=""
                  value={formField.value || ''}
                  data-testid="field-tenant-id"
                />
              )}
            />
          </Grid>

          {/* Form Actions */}
          <Grid size={12}>
            <Box display="flex" gap={2} pt={2}>
              <Button
                type="submit"
                variant="contained"
                color="primary"
                disabled={isLoading}
                startIcon={isLoading ? <CircularProgress size={20} /> : undefined}
                data-testid="submit-button"
              >
                {isLoading
                  ? 'Saving...'
                  : isEditMode
                    ? 'Update Permission'
                    : 'Create Permission'}
              </Button>

              <Button
                type="button"
                variant="outlined"
                onClick={onCancel}
                disabled={isLoading}
                data-testid="cancel-button"
              >
                Cancel
              </Button>
            </Box>
          </Grid>
        </Grid>
      </Box>
    </FormProvider>
  );
}

// ============================================================================
// Modal Wrapper Component
// ============================================================================

/**
 * PermissionFormModal Component
 *
 * Wraps the PermissionForm in a Material UI Dialog for modal display.
 * Use this component when you want to show the form in a popup dialog.
 *
 * @example
 * ```tsx
 * <PermissionFormModal
 *   open={isModalOpen}
 *   onClose={handleClose}
 *   onSubmit={handleCreate}
 *   onCancel={handleClose}
 *   isLoading={isCreating}
 * />
 * ```
 */
export function PermissionFormModal({
  open,
  onClose,
  title,
  permission,
  onSubmit,
  onCancel,
  isLoading = false,
  className = '',
}: PermissionFormModalProps): React.ReactElement {
  const isEditMode = Boolean(permission);
  const modalTitle = title ?? (isEditMode ? 'Edit Permission' : 'Create Permission');

  // Handle modal close - prevent closing during loading
  const handleClose = () => {
    if (!isLoading) {
      onClose();
    }
  };

  return (
    <Dialog
      open={open}
      onClose={handleClose}
      maxWidth="md"
      fullWidth
      data-testid="modal-permission-form"
    >
      <DialogTitle sx={{ m: 0, p: 2, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        {modalTitle}
        <IconButton
          aria-label="close"
          onClick={handleClose}
          disabled={isLoading}
          data-testid="modal-close-button"
          sx={{ color: (theme) => theme.palette.grey[500] }}
        >
          <CloseIcon />
        </IconButton>
      </DialogTitle>
      <DialogContent dividers>
        <PermissionForm
          permission={permission}
          onSubmit={onSubmit}
          onCancel={onCancel}
          isLoading={isLoading}
          className={className}
        />
      </DialogContent>
    </Dialog>
  );
}


// Default export for convenience
export default PermissionForm;
