/**
 * Subscription Type Definitions
 *
 * This file contains type definitions for the Subscription entity:
 * - Subscription: Full entity model with all fields
 * - SubscriptionCreateRequest: Data for creating a new subscription
 * - SubscriptionUpdateRequest: Partial data for updating a subscription
 * - SubscriptionListResponse: Paginated list response
 * - SubscriptionFilterOptions: Query parameters for filtering
 * - SubscriptionDropdownOption: Options for select components
 *
 * User subscription linked to Stripe
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:43.848105Z
 */

// ============================================================================
// Base Types
// ============================================================================

/**
 * Base filter interface with common query parameters
 * Provides pagination, sorting, and search capabilities
 */
export interface BaseEntityFilters {
  /** Search query string - searches across multiple text fields */
  search?: string;
  /** Active/inactive status filter */
  is_active?: boolean;
  /** Pagination: page number (1-indexed) */
  page?: number;
  /** Pagination: items per page */
  page_size?: number;
  /** Sort field name */
  sort_by?: string;
  /** Sort direction */
  sort_order?: 'asc' | 'desc';
}

/**
 * Pagination metadata returned by the API
 */
export interface PaginationMeta {
  /** Current page number (1-indexed) */
  page: number;
  /** Number of items per page */
  page_size: number;
  /** Total number of items matching the query */
  total: number;
  /** Total number of pages */
  total_pages: number;
  /** Whether there is a next page */
  has_next: boolean;
  /** Whether there is a previous page */
  has_prev: boolean;
}

// ============================================================================
// Subscription Entity
// ============================================================================

/**
 * Subscription entity model
 *
 * Represents the full subscription entity as returned by the API.
 * User subscription linked to Stripe
 *
 * @remarks
 * This interface matches the backend SubscriptionDTO schema exactly.
 */
export interface Subscription {
  /** Unique identifier (UUID) */
  id: string;

  /** Auth user reference — one subscription per user */
  user_id: string;

  /** Plan Id */
  plan_id: string;

  /** Status */
  status: string;

  /** Stripe Customer Id */
  stripe_customer_id: string | null;

  /** Stripe Subscription Id */
  stripe_subscription_id: string | null;

  /** Stripe Payment Method Id */
  stripe_payment_method_id: string | null;

  /** Billing Period */
  billing_period: string | null;

  /** Current Period End */
  current_period_end: string | null;

  /** Cancel At Period End */
  cancel_at_period_end: boolean;

  /** Trial Ends At */
  trial_ends_at: string | null;

  /** Creation timestamp (ISO 8601) */
  created_at: string;

  /** Last update timestamp (ISO 8601) */
  updated_at: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Request/Response Types
// ============================================================================

/**
 * Subscription creation request data
 *
 * Used when creating a new subscription. Omits system-generated fields
 * like id, timestamps, and audit fields.
 *
 * @remarks
 * Matches the backend SubscriptionCreateDTO schema.
 */
export interface SubscriptionCreateRequest {
  /** Auth user reference — one subscription per user (required) */
  user_id: string;

  /** Plan Id (required) */
  plan_id: string;

  /** Status (optional) */
  status?: string;

  /** Stripe Customer Id (optional) */
  stripe_customer_id?: string;

  /** Stripe Subscription Id (optional) */
  stripe_subscription_id?: string;

  /** Stripe Payment Method Id (optional) */
  stripe_payment_method_id?: string;

  /** Billing Period (optional) */
  billing_period?: string;

  /** Current Period End (optional) */
  current_period_end?: string;

  /** Cancel At Period End (optional) */
  cancel_at_period_end?: boolean;

  /** Trial Ends At (optional) */
  trial_ends_at?: string;

  /** Active status (defaults to true for new subscriptions) */
  is_active?: boolean;
}

/**
 * Subscription update request data
 *
 * Used when updating an existing subscription. All fields are optional
 * to support partial updates.
 *
 * @remarks
 * Matches the backend SubscriptionUpdateDTO schema.
 */
export interface SubscriptionUpdateRequest {
  /** Auth user reference — one subscription per user */
  user_id?: string;

  /** Plan Id */
  plan_id?: string;

  /** Status */
  status?: string;

  /** Stripe Customer Id */
  stripe_customer_id?: string | null;

  /** Stripe Subscription Id */
  stripe_subscription_id?: string | null;

  /** Stripe Payment Method Id */
  stripe_payment_method_id?: string | null;

  /** Billing Period */
  billing_period?: string | null;

  /** Current Period End */
  current_period_end?: string | null;

  /** Cancel At Period End */
  cancel_at_period_end?: boolean;

  /** Trial Ends At */
  trial_ends_at?: string | null;

  /** Active status */
  is_active?: boolean;
}

/**
 * Subscription list response
 *
 * Wrapper for paginated subscription list queries.
 */
export interface SubscriptionListResponse {
  /** Array of subscription items */
  items: Subscription[];

  /** Alternative property name for items (for API compatibility) */
  subscriptions?: Subscription[];

  /** Pagination metadata */
  pagination?: PaginationMeta;

  /** Total count of items matching the query */
  total?: number;
}

// ============================================================================
// Filter Types
// ============================================================================

/**
 * Subscription filter options for list queries
 *
 * Extends BaseEntityFilters with subscription-specific filtering options.
 */
export interface SubscriptionFilterOptions extends BaseEntityFilters {
  /** Filter by auth user reference — one subscription per user */
  user_id?: string;

  /** Filter by plan id */
  plan_id?: string;

  /** Filter by status */
  status?: string;

  /** Filter by stripe customer id */
  stripe_customer_id?: string;

  /** Filter by stripe subscription id */
  stripe_subscription_id?: string;

  /** Filter by stripe payment method id */
  stripe_payment_method_id?: string;

}

// ============================================================================
// Dropdown/Select Types
// ============================================================================

/**
 * Subscription dropdown option for select components
 *
 * Provides a standardized structure for dropdown/select options with
 * the full entity data attached for additional context.
 */
export interface SubscriptionDropdownOption {
  /** Option value (typically the entity ID) */
  value: string;

  /** Display label for the option */
  label: string;

  /** Full entity data for additional context */
  data: Subscription;

  /** Whether this option should be disabled */
  disabled?: boolean;
}

// ============================================================================
// Summary Types
// ============================================================================

/**
 * Subscription summary for list views
 *
 * Contains minimal fields for efficient list rendering.
 * Use this type when you only need basic display information.
 */
export interface SubscriptionSummary {
  /** Unique identifier */
  id: string;

  /** Status */
  status: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Form Types
// ============================================================================

/**
 * Subscription form data for React Hook Form integration
 *
 * Type alias for the create request that can be used with form libraries.
 * Provides sensible defaults for form state.
 */
export type SubscriptionFormData = SubscriptionCreateRequest;

/**
 * Default form values for new subscription
 *
 * Use this when initializing form state for creating a new subscription.
 */
export const DEFAULT_SUBSCRIPTION_FORM_DATA: Partial<SubscriptionFormData> = {
  is_active: true,
  status: "trialing",
  cancel_at_period_end: false,
};

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Single subscription API response
 */
export interface SubscriptionResponse {
  /** The requested subscription entity */
  data: Subscription;
}

/**
 * Subscription mutation response (create/update)
 */
export interface SubscriptionMutationResponse {
  /** The created or updated subscription */
  data: Subscription;

  /** Success message */
  message?: string;
}

/**
 * API error response for subscription operations
 */
export interface SubscriptionApiError {
  /** HTTP status code */
  status_code: number;

  /** Error message */
  message: string;

  /** Error code for programmatic handling */
  error_code?: string;

  /** Detailed error information */
  detail?: string | Record<string, unknown>;

  /** Field-level validation errors */
  validation_errors?: Record<string, string[]>;
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Type guard to check if a value is a Subscription
 *
 * @param value - Value to check
 * @returns True if value is a Subscription
 */
export function isSubscription(value: unknown): value is Subscription {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.id === 'string' &&
    typeof obj.user_id === 'string' &&
    typeof obj.plan_id === 'string'
  );
}

/**
 * Type guard to check if a value is a SubscriptionDropdownOption
 *
 * @param value - Value to check
 * @returns True if value is a SubscriptionDropdownOption
 */
export function isSubscriptionDropdownOption(
  value: unknown
): value is SubscriptionDropdownOption {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.value === 'string' &&
    typeof obj.label === 'string' &&
    isSubscription(obj.data)
  );
}

// ============================================================================
// Exports
// ============================================================================

/** All subscription types re-exported for convenience */
export type {
  Subscription as SubscriptionEntity,
  SubscriptionCreateRequest as CreateSubscriptionInput,
  SubscriptionUpdateRequest as UpdateSubscriptionInput,
};
