/**
 * DocumentParty E2E Test Helpers
 *
 * Utility functions for DocumentParty E2E tests using Playwright.
 * Provides form filling, navigation, and entity manipulation helpers.
 *
 * Form Display Mode: modal
 *
 * Helper functions:
 * - fillDocumentPartyForm: Fill all form fields with test data
 * - waitForDocumentPartyList: Wait for list page to load
 * - waitForDocumentPartyForm: Wait for form to be visible and ready
 * - waitForDocumentPartyModal: Wait for modal form to open
 * - closeDocumentPartyModal: Close the modal form
 * - findDocumentPartyInList: Locate entity row by display value
 * - deleteDocumentPartyByName: Delete entity and confirm
 * - getFormField: Get form field locator by name
 * - getFormErrorMessage: Get validation error message
 *
 * Links a legal document to its parties (entity + signatory) with role designation
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:51.200262Z
 */

import { Page, Locator, expect } from '@playwright/test';
import type { DocumentPartyCreateRequest } from '../../types/document_party.types';

// ============================================================================
// Configuration
// ============================================================================

/**
 * Default timeout for waiting operations (ms)
 */
const DEFAULT_TIMEOUT = 10000;

/**
 * Short timeout for quick checks (ms)
 */
const SHORT_TIMEOUT = 3000;

/**
 * Debounce delay for form interactions (ms)
 */
const DEBOUNCE_DELAY = 100;

// ============================================================================
// Form Field Helpers
// ============================================================================

/**
 * Get a form field locator by field name
 *
 * Supports different field types:
 * - text/number fields: [data-testid="field-{fieldName}"]
 * - select fields: [data-testid="select-{fieldName}"]
 * - checkbox fields: [data-testid="checkbox-{fieldName}"]
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the field (snake_case or camelCase)
 * @returns Locator for the form field
 *
 * @example
 * ```typescript
 * const nameField = getFormField(page, 'name');
 * await nameField.fill('Test Value');
 * ```
 */
export function getFormField(page: Page, fieldName: string): Locator {
  // Convert camelCase to kebab-case for test IDs
  const kebabName = fieldName.replace(/_/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();

  // Try text/number field first (most common)
  return page.locator(`[data-testid="field-${kebabName}"] input, [data-testid="field-${kebabName}"] textarea`);
}

/**
 * Get a select field locator by field name
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the select field
 * @returns Locator for the select trigger element
 *
 * @example
 * ```typescript
 * const statusSelect = getSelectField(page, 'status');
 * await statusSelect.click();
 * await page.locator('[role="option"]').filter({ hasText: 'Active' }).click();
 * ```
 */
export function getSelectField(page: Page, fieldName: string): Locator {
  const kebabName = fieldName.replace(/_/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  return page.locator(`[data-testid="select-${kebabName}"]`);
}

/**
 * Get a checkbox field locator by field name
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the checkbox field
 * @returns Locator for the checkbox input element
 *
 * @example
 * ```typescript
 * const isActiveCheckbox = getCheckboxField(page, 'is_active');
 * await isActiveCheckbox.check();
 * ```
 */
export function getCheckboxField(page: Page, fieldName: string): Locator {
  const kebabName = fieldName.replace(/_/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  return page.locator(`[data-testid="checkbox-${kebabName}"]`);
}

/**
 * Get the validation error message for a form field
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the field with error
 * @returns Error message text or null if no error
 *
 * @example
 * ```typescript
 * const error = await getFormErrorMessage(page, 'email');
 * expect(error).toContain('Invalid email');
 * ```
 */
export async function getFormErrorMessage(page: Page, fieldName: string): Promise<string | null> {
  const kebabName = fieldName.replace(/_/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
  const errorLocator = page.locator(`[data-testid-error="field-${kebabName}-error"]`);

  try {
    await errorLocator.waitFor({ state: 'visible', timeout: SHORT_TIMEOUT });
    return await errorLocator.textContent();
  } catch {
    // No error message visible
    return null;
  }
}

/**
 * Check if a form field has a validation error
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the field to check
 * @returns True if field has error, false otherwise
 */
export async function hasFieldError(page: Page, fieldName: string): Promise<boolean> {
  const error = await getFormErrorMessage(page, fieldName);
  return error !== null;
}

/**
 * Get all form validation errors as a map
 *
 * @param page - Playwright page object
 * @returns Map of field names to error messages
 */
export async function getAllFormErrors(page: Page): Promise<Map<string, string>> {
  const errors = new Map<string, string>();
  const errorElements = page.locator('[data-testid-error]');
  const count = await errorElements.count();

  for (let i = 0; i < count; i++) {
    const element = errorElements.nth(i);
    const testId = await element.getAttribute('data-testid-error');
    const message = await element.textContent();

    if (testId && message) {
      // Extract field name from testId (format: field-{name}-error)
      const match = testId.match(/^field-(.+)-error$/);
      if (match) {
        errors.set(match[1], message);
      }
    }
  }

  return errors;
}

// ============================================================================
// Form Filling Helpers
// ============================================================================

/**
 * Fill the DocumentParty form with provided test data
 *
 * Handles all field types:
 * - Text fields: Direct input
 * - Number fields: Converts to string and inputs
 * - Boolean fields: Checkbox check/uncheck
 * - Enum/Select fields: Dropdown selection
 *
 * @param page - Playwright page object
 * @param data - Test data to fill the form with
 * @param options - Optional configuration
 * @param options.clearFirst - Clear fields before filling (default: true)
 * @param options.skipReadonly - Skip readonly fields (default: true)
 *
 * @example
 * ```typescript
 * const testData = generateDocumentPartyTestData('complete');
 * await fillDocumentPartyForm(page, testData);
 * ```
 */
export async function fillDocumentPartyForm(
  page: Page,
  data: Partial<DocumentPartyCreateRequest>,
  options: { clearFirst?: boolean; skipReadonly?: boolean } = {}
): Promise<void> {
  const { clearFirst = true, skipReadonly = true } = options;

  console.log(`[DocumentPartyHelpers] Filling form with data:`, JSON.stringify(data, null, 2));

  // Fill legal_document_id field
  if (data.legal_document_id !== undefined) {
    // legal_document_id is a text field
    const legal_document_idField = getFormField(page, 'legal_document_id');
    if (clearFirst) {
      await legal_document_idField.clear();
    }
    await legal_document_idField.fill(data.legal_document_id || '');
  }

  // Fill legal_entity_id field
  if (data.legal_entity_id !== undefined) {
    // legal_entity_id is a text field
    const legal_entity_idField = getFormField(page, 'legal_entity_id');
    if (clearFirst) {
      await legal_entity_idField.clear();
    }
    await legal_entity_idField.fill(data.legal_entity_id || '');
  }

  // Fill signatory_id field
  if (data.signatory_id !== undefined) {
    // signatory_id is a text field
    const signatory_idField = getFormField(page, 'signatory_id');
    if (clearFirst) {
      await signatory_idField.clear();
    }
    await signatory_idField.fill(data.signatory_id || '');
  }

  // Fill party_role field
  if (data.party_role !== undefined) {
    // party_role is a text field
    const party_roleField = getFormField(page, 'party_role');
    if (clearFirst) {
      await party_roleField.clear();
    }
    await party_roleField.fill(data.party_role || '');
  }

  // Fill party_label field
  if (data.party_label !== undefined) {
    // party_label is a text field
    const party_labelField = getFormField(page, 'party_label');
    if (clearFirst) {
      await party_labelField.clear();
    }
    await party_labelField.fill(data.party_label || '');
  }


  console.log(`[DocumentPartyHelpers] Form filled successfully`);
}

/**
 * Fill a single form field by name
 *
 * @param page - Playwright page object
 * @param fieldName - Name of the field to fill
 * @param value - Value to fill
 * @param fieldType - Type of the field (text, number, boolean, select)
 */
export async function fillFormField(
  page: Page,
  fieldName: string,
  value: string | number | boolean,
  fieldType: 'text' | 'number' | 'boolean' | 'select' = 'text'
): Promise<void> {
  switch (fieldType) {
    case 'boolean':
      const checkbox = getCheckboxField(page, fieldName);
      const isChecked = await checkbox.isChecked();
      if (value && !isChecked) {
        await checkbox.check();
      } else if (!value && isChecked) {
        await checkbox.uncheck();
      }
      break;

    case 'select':
      const select = getSelectField(page, fieldName);
      await select.click();
      await page.waitForTimeout(DEBOUNCE_DELAY);
      await page.locator('[role="option"]').filter({ hasText: String(value) }).click();
      break;

    case 'number':
    case 'text':
    default:
      const field = getFormField(page, fieldName);
      await field.clear();
      await field.fill(String(value));
      break;
  }
}

// ============================================================================
// Navigation Helpers
// ============================================================================

/**
 * Wait for the DocumentParty list page to fully load
 *
 * Waits for:
 * - Page heading to be visible
 * - Add button to be visible
 * - Loading indicators to disappear
 * - Table or empty state to be visible
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms (default: 10000)
 *
 * @example
 * ```typescript
 * await page.goto('/document_parties');
 * await waitForDocumentPartyList(page);
 * ```
 */
export async function waitForDocumentPartyList(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  console.log(`[DocumentPartyHelpers] Waiting for DocumentParty list to load...`);

  // Wait for add button to be visible (indicates page is loaded)
  await expect(
    page.locator('[data-testid="btn-add-document_party"]')
  ).toBeVisible({ timeout });

  // Wait for any loading indicators to disappear
  const loadingIndicator = page.locator('[data-testid="loading"], [role="progressbar"]');
  await loadingIndicator.waitFor({ state: 'hidden', timeout }).catch(() => {
    // Loading indicator might not exist, that's okay
  });

  // Wait for either table or empty state to be visible
  const table = page.locator('table');
  const emptyState = page.getByText(/no document_parties found/i);

  await Promise.race([
    table.waitFor({ state: 'visible', timeout }).catch(() => {}),
    emptyState.waitFor({ state: 'visible', timeout }).catch(() => {}),
  ]);

  console.log(`[DocumentPartyHelpers] DocumentParty list loaded`);
}

/**
 * Wait for the DocumentParty form to be visible and ready
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms
 */
export async function waitForDocumentPartyForm(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  console.log(`[DocumentPartyHelpers] Waiting for DocumentParty form...`);

  await expect(
    page.locator('[data-testid="form-document_party"]')
  ).toBeVisible({ timeout });

  // Wait for form fields to be interactive
  await page.locator('[data-testid="submit-button"]').waitFor({ state: 'visible', timeout });

  console.log(`[DocumentPartyHelpers] DocumentParty form ready`);
}

/**
 * Wait for the DocumentParty form modal to open
 *
 * Waits for the modal dialog wrapper and the form inside it to be visible.
 * Use this function when the entity is configured with form_display: modal.
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms
 *
 * @example
 * ```typescript
 * await page.locator('[data-testid="btn-add-document_party"]').click();
 * await waitForDocumentPartyModal(page);
 * // Modal is now open and ready for interaction
 * ```
 */
export async function waitForDocumentPartyModal(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  console.log(`[DocumentPartyHelpers] Waiting for DocumentParty modal to open...`);

  // Wait for the modal wrapper to be visible
  await expect(
    page.locator('[data-testid="modal-document_party-form"]')
  ).toBeVisible({ timeout });

  // Wait for the form inside the modal to be visible
  await expect(
    page.locator('[data-testid="form-document_party"]')
  ).toBeVisible({ timeout });

  // Wait for form fields to be interactive
  await page.locator('[data-testid="submit-button"]').waitFor({ state: 'visible', timeout });

  console.log(`[DocumentPartyHelpers] DocumentParty modal opened`);
}

/**
 * Close the DocumentParty form modal
 *
 * Closes the modal using the close button and waits for it to disappear.
 * Use this function to dismiss the modal without submitting the form.
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms
 *
 * @example
 * ```typescript
 * // After opening the modal and deciding to cancel
 * await closeDocumentPartyModal(page);
 * // Modal is now closed
 * ```
 */
export async function closeDocumentPartyModal(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  console.log(`[DocumentPartyHelpers] Closing DocumentParty modal...`);

  // Click the modal close button
  const closeButton = page.locator('[data-testid="modal-close-button"]');
  if (await closeButton.isVisible()) {
    await closeButton.click();
  } else {
    // Fallback: try the cancel button
    await page.locator('[data-testid="cancel-button"]').click();
  }

  // Wait for modal to be hidden
  await expect(
    page.locator('[data-testid="modal-document_party-form"]')
  ).not.toBeVisible({ timeout });

  console.log(`[DocumentPartyHelpers] DocumentParty modal closed`);
}


/**
 * Navigate to the DocumentParty list page
 *
 * @param page - Playwright page object
 * @param baseUrl - Base URL of the application
 */
export async function navigateToDocumentPartyList(page: Page, baseUrl = 'http://localhost:5173'): Promise<void> {
  await page.goto(`${baseUrl}/document_parties`);
  await waitForDocumentPartyList(page);
}

/**
 * Navigate to create a new DocumentParty
 *
 * Clicks the add button and waits for the appropriate form display:
 * - Modal: Waits for modal dialog to open
 * - Drawer: Waits for drawer panel to open
 * - Inline: Waits for inline form to be visible
 *
 * @param page - Playwright page object
 */
export async function navigateToCreateDocumentParty(page: Page): Promise<void> {
  await page.locator('[data-testid="btn-add-document_party"]').click();
  await waitForDocumentPartyModal(page);
}

// ============================================================================
// Entity Finding Helpers
// ============================================================================

/**
 * Find a DocumentParty row in the list by display value
 *
 * Searches the table for a row containing the specified text.
 * Returns the row locator if found, or null if not found.
 *
 * @param page - Playwright page object
 * @param displayValue - Value to search for (name, code, or other identifier)
 * @param column - Optional column index to search in (0-based)
 * @returns Locator for the table row, or null if not found
 *
 * @example
 * ```typescript
 * const row = await findDocumentPartyInList(page, 'Test Currency');
 * if (row) {
 *   await row.locator('[data-testid^="btn-edit"]').click();
 * }
 * ```
 */
export async function findDocumentPartyInList(
  page: Page,
  displayValue: string,
  column?: number
): Promise<Locator | null> {
  console.log(`[DocumentPartyHelpers] Finding DocumentParty with value: ${displayValue}`);

  // Wait for table to be visible
  const table = page.locator('table');
  await table.waitFor({ state: 'visible', timeout: SHORT_TIMEOUT }).catch(() => null);

  if (!(await table.isVisible())) {
    console.log(`[DocumentPartyHelpers] Table not visible`);
    return null;
  }

  // Search in table rows
  const rows = page.locator('tbody tr');
  const rowCount = await rows.count();

  for (let i = 0; i < rowCount; i++) {
    const row = rows.nth(i);
    const rowText = await row.textContent();

    if (rowText && rowText.includes(displayValue)) {
      console.log(`[DocumentPartyHelpers] Found DocumentParty at row ${i}`);
      return row;
    }

    // Also check specific column if provided
    if (column !== undefined) {
      const cell = row.locator('td').nth(column);
      const cellText = await cell.textContent();
      if (cellText && cellText.includes(displayValue)) {
        console.log(`[DocumentPartyHelpers] Found DocumentParty at row ${i}, column ${column}`);
        return row;
      }
    }
  }

  console.log(`[DocumentPartyHelpers] DocumentParty not found: ${displayValue}`);
  return null;
}

/**
 * Check if a DocumentParty exists in the list
 *
 * @param page - Playwright page object
 * @param displayValue - Value to search for
 * @returns True if entity exists in list, false otherwise
 */
export async function documentPartyExistsInList(page: Page, displayValue: string): Promise<boolean> {
  const row = await findDocumentPartyInList(page, displayValue);
  return row !== null;
}

/**
 * Get the count of DocumentParties in the list
 *
 * @param page - Playwright page object
 * @returns Number of entities in the table
 */
export async function getDocumentPartyCount(page: Page): Promise<number> {
  const rows = page.locator('tbody tr');
  return await rows.count();
}

// ============================================================================
// Entity Action Helpers
// ============================================================================

/**
 * Delete a DocumentParty by its display name
 *
 * Finds the entity in the list and clicks the delete button.
 * Handles the confirmation dialog.
 *
 * @param page - Playwright page object
 * @param displayValue - Display value of the entity to delete
 * @returns True if deletion was initiated, false if entity not found
 *
 * @example
 * ```typescript
 * const deleted = await deleteDocumentPartyByName(page, 'Test Currency');
 * expect(deleted).toBeTruthy();
 * ```
 */
export async function deleteDocumentPartyByName(page: Page, displayValue: string): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Deleting DocumentParty: ${displayValue}`);

  const row = await findDocumentPartyInList(page, displayValue);

  if (!row) {
    console.log(`[DocumentPartyHelpers] DocumentParty not found for deletion: ${displayValue}`);
    return false;
  }

  // Find and click the delete button in this row
  const deleteButton = row.locator('[data-testid^="btn-delete-document_party"]');

  if (!(await deleteButton.isVisible())) {
    console.log(`[DocumentPartyHelpers] Delete button not visible for: ${displayValue}`);
    return false;
  }

  // Set up dialog handler for confirmation
  page.once('dialog', async (dialog) => {
    console.log(`[DocumentPartyHelpers] Confirming delete dialog`);
    await dialog.accept();
  });

  await deleteButton.click();

  console.log(`[DocumentPartyHelpers] Delete initiated for: ${displayValue}`);
  return true;
}

/**
 * Edit a DocumentParty by its display name
 *
 * Opens the edit form for the specified entity. The form will be displayed
 * according to the configured display mode (modal).
 *
 * @param page - Playwright page object
 * @param displayValue - Display value of the entity to edit
 * @returns True if edit form was opened, false if entity not found
 */
export async function editDocumentPartyByName(page: Page, displayValue: string): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Editing DocumentParty: ${displayValue}`);

  const row = await findDocumentPartyInList(page, displayValue);

  if (!row) {
    console.log(`[DocumentPartyHelpers] DocumentParty not found for editing: ${displayValue}`);
    return false;
  }

  const editButton = row.locator('[data-testid^="btn-edit-document_party"]');

  if (!(await editButton.isVisible())) {
    console.log(`[DocumentPartyHelpers] Edit button not visible for: ${displayValue}`);
    return false;
  }

  await editButton.click();
  await waitForDocumentPartyModal(page);

  console.log(`[DocumentPartyHelpers] Edit form opened for: ${displayValue}`);
  return true;
}

/**
 * View DocumentParty details by its display name
 *
 * @param page - Playwright page object
 * @param displayValue - Display value of the entity to view
 * @returns True if view was opened, false if entity not found
 */
export async function viewDocumentPartyByName(page: Page, displayValue: string): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Viewing DocumentParty: ${displayValue}`);

  const row = await findDocumentPartyInList(page, displayValue);

  if (!row) {
    return false;
  }

  const viewButton = row.locator('[data-testid^="btn-view-document_party"]');

  if (await viewButton.isVisible()) {
    await viewButton.click();
    return true;
  }

  // Fallback: try clicking the row itself
  await row.click();
  return true;
}

// ============================================================================
// Notification Helpers
// ============================================================================

/**
 * Wait for a success notification to appear
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms
 */
export async function waitForSuccessNotification(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  await expect(
    page.locator('[data-testid="notification-success"]')
  ).toBeVisible({ timeout });
}

/**
 * Wait for an error notification to appear
 *
 * @param page - Playwright page object
 * @param timeout - Maximum wait time in ms
 */
export async function waitForErrorNotification(page: Page, timeout = DEFAULT_TIMEOUT): Promise<void> {
  await expect(
    page.locator('[data-testid="notification-error"]')
  ).toBeVisible({ timeout });
}

/**
 * Close any visible notification
 *
 * @param page - Playwright page object
 */
export async function closeNotification(page: Page): Promise<void> {
  const closeButtons = page.locator('[data-testid^="notification-"] button[aria-label="Close"]');
  const count = await closeButtons.count();

  for (let i = 0; i < count; i++) {
    const button = closeButtons.nth(i);
    if (await button.isVisible()) {
      await button.click();
    }
  }
}

/**
 * Get the notification message text
 *
 * @param page - Playwright page object
 * @param type - Type of notification to check (success, error, warning, info)
 * @returns Notification message text or null
 */
export async function getNotificationMessage(
  page: Page,
  type: 'success' | 'error' | 'warning' | 'info' = 'success'
): Promise<string | null> {
  const notification = page.locator(`[data-testid="notification-${type}"]`);

  if (await notification.isVisible()) {
    return await notification.textContent();
  }

  return null;
}

// ============================================================================
// Form Submission Helpers
// ============================================================================

/**
 * Submit the DocumentParty form and wait for response
 *
 * @param page - Playwright page object
 * @param expectSuccess - Whether to expect success (default: true)
 * @returns True if form was submitted (success or expected error)
 */
export async function submitDocumentPartyForm(
  page: Page,
  expectSuccess = true
): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Submitting form, expecting ${expectSuccess ? 'success' : 'error'}`);

  const submitButton = page.locator('[data-testid="submit-button"]');
  await submitButton.click();

  if (expectSuccess) {
    await waitForSuccessNotification(page);
    console.log(`[DocumentPartyHelpers] Form submitted successfully`);
    return true;
  } else {
    // Wait for either error notification or form errors
    await Promise.race([
      waitForErrorNotification(page).catch(() => {}),
      page.locator('[data-testid="form-errors-summary"]').waitFor({ state: 'visible' }).catch(() => {}),
    ]);
    console.log(`[DocumentPartyHelpers] Form submission failed as expected`);
    return true;
  }
}

/**
 * Cancel the DocumentParty form and return to list
 *
 * @param page - Playwright page object
 */
export async function cancelDocumentPartyForm(page: Page): Promise<void> {
  console.log(`[DocumentPartyHelpers] Cancelling form`);

  const cancelButton = page.locator('[data-testid="cancel-button"]');
  await cancelButton.click();
  await waitForDocumentPartyList(page);

  console.log(`[DocumentPartyHelpers] Form cancelled, back to list`);
}

// ============================================================================
// CRUD Workflow Helpers
// ============================================================================

/**
 * Create a new DocumentParty with provided data
 *
 * Complete workflow: navigate to form, fill data, submit, verify success
 *
 * @param page - Playwright page object
 * @param data - Test data to create with
 * @returns True if creation was successful
 *
 * @example
 * ```typescript
 * const testData = generateDocumentPartyTestData('complete');
 * const created = await createDocumentParty(page, testData);
 * expect(created).toBeTruthy();
 * ```
 */
export async function createDocumentParty(
  page: Page,
  data: Partial<DocumentPartyCreateRequest>
): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Creating new DocumentParty`);

  try {
    // Navigate to create form
    await navigateToCreateDocumentParty(page);

    // Fill form with data
    await fillDocumentPartyForm(page, data);

    // Submit and wait for success
    await submitDocumentPartyForm(page, true);

    // Wait for list to reload
    await waitForDocumentPartyList(page);

    console.log(`[DocumentPartyHelpers] DocumentParty created successfully`);
    return true;
  } catch (error) {
    console.error(`[DocumentPartyHelpers] Failed to create DocumentParty:`, error);
    return false;
  }
}

/**
 * Update an existing DocumentParty
 *
 * @param page - Playwright page object
 * @param displayValue - Display value to find the entity
 * @param data - Updated data
 * @returns True if update was successful
 */
export async function updateDocumentParty(
  page: Page,
  displayValue: string,
  data: Partial<DocumentPartyCreateRequest>
): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Updating DocumentParty: ${displayValue}`);

  try {
    // Find and open edit form
    const opened = await editDocumentPartyByName(page, displayValue);
    if (!opened) {
      return false;
    }

    // Fill form with updated data
    await fillDocumentPartyForm(page, data, { clearFirst: true });

    // Submit and wait for success
    await submitDocumentPartyForm(page, true);

    // Wait for list to reload
    await waitForDocumentPartyList(page);

    console.log(`[DocumentPartyHelpers] DocumentParty updated successfully`);
    return true;
  } catch (error) {
    console.error(`[DocumentPartyHelpers] Failed to update DocumentParty:`, error);
    return false;
  }
}

/**
 * Delete a DocumentParty and verify deletion
 *
 * @param page - Playwright page object
 * @param displayValue - Display value to find the entity
 * @returns True if deletion was successful
 */
export async function deleteDocumentParty(
  page: Page,
  displayValue: string
): Promise<boolean> {
  console.log(`[DocumentPartyHelpers] Deleting DocumentParty: ${displayValue}`);

  try {
    const deleted = await deleteDocumentPartyByName(page, displayValue);
    if (!deleted) {
      return false;
    }

    // Wait for success notification
    await waitForSuccessNotification(page);

    // Verify entity is removed from list
    await waitForDocumentPartyList(page);
    const stillExists = await documentPartyExistsInList(page, displayValue);

    if (stillExists) {
      console.error(`[DocumentPartyHelpers] DocumentParty still exists after deletion`);
      return false;
    }

    console.log(`[DocumentPartyHelpers] DocumentParty deleted successfully`);
    return true;
  } catch (error) {
    console.error(`[DocumentPartyHelpers] Failed to delete DocumentParty:`, error);
    return false;
  }
}

// ============================================================================
// Search and Filter Helpers
// ============================================================================

/**
 * Search for DocumentParties by query
 *
 * @param page - Playwright page object
 * @param query - Search query string
 */
export async function searchDocumentParties(page: Page, query: string): Promise<void> {
  console.log(`[DocumentPartyHelpers] Searching for: ${query}`);

  const searchInput = page.getByPlaceholder(/search/i);
  await searchInput.fill(query);

  // Wait for debounced search
  await page.waitForTimeout(700);
}

/**
 * Clear the search filter
 *
 * @param page - Playwright page object
 */
export async function clearSearch(page: Page): Promise<void> {
  const searchInput = page.getByPlaceholder(/search/i);
  await searchInput.clear();
  await page.waitForTimeout(700);
}

// Note: All functions are already exported via 'export function' declarations above.
