# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from . import registry_pb2 as registry__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in registry_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RegistryServiceStub:
    """=============================================================================
    Registry Service
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/Register",
            request_serializer=registry__pb2.RegisterRequest.SerializeToString,
            response_deserializer=registry__pb2.RegisterResponse.FromString,
            _registered_method=True,
        )
        self.Deregister = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/Deregister",
            request_serializer=registry__pb2.DeregisterRequest.SerializeToString,
            response_deserializer=registry__pb2.DeregisterResponse.FromString,
            _registered_method=True,
        )
        self.Heartbeat = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/Heartbeat",
            request_serializer=registry__pb2.HeartbeatRequest.SerializeToString,
            response_deserializer=registry__pb2.HeartbeatResponse.FromString,
            _registered_method=True,
        )
        self.Discover = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/Discover",
            request_serializer=registry__pb2.DiscoverRequest.SerializeToString,
            response_deserializer=registry__pb2.DiscoverResponse.FromString,
            _registered_method=True,
        )
        self.Watch = channel.unary_stream(
            "/venturestrat.registry.v1.RegistryService/Watch",
            request_serializer=registry__pb2.WatchRequest.SerializeToString,
            response_deserializer=registry__pb2.ServiceEvent.FromString,
            _registered_method=True,
        )
        self.ListServices = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/ListServices",
            request_serializer=registry__pb2.ListServicesRequest.SerializeToString,
            response_deserializer=registry__pb2.ListServicesResponse.FromString,
            _registered_method=True,
        )
        self.GetHealth = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/GetHealth",
            request_serializer=registry__pb2.GetHealthRequest.SerializeToString,
            response_deserializer=registry__pb2.GetHealthResponse.FromString,
            _registered_method=True,
        )
        self.GetServiceHealth = channel.unary_unary(
            "/venturestrat.registry.v1.RegistryService/GetServiceHealth",
            request_serializer=registry__pb2.GetServiceHealthRequest.SerializeToString,
            response_deserializer=registry__pb2.GetServiceHealthResponse.FromString,
            _registered_method=True,
        )


class RegistryServiceServicer:
    """=============================================================================
    Registry Service
    =============================================================================

    """

    def Register(self, request, context):
        """Registration"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Deregister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Discover(self, request, context):
        """Discovery"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHealth(self, request, context):
        """Health"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetServiceHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=registry__pb2.RegisterRequest.FromString,
            response_serializer=registry__pb2.RegisterResponse.SerializeToString,
        ),
        "Deregister": grpc.unary_unary_rpc_method_handler(
            servicer.Deregister,
            request_deserializer=registry__pb2.DeregisterRequest.FromString,
            response_serializer=registry__pb2.DeregisterResponse.SerializeToString,
        ),
        "Heartbeat": grpc.unary_unary_rpc_method_handler(
            servicer.Heartbeat,
            request_deserializer=registry__pb2.HeartbeatRequest.FromString,
            response_serializer=registry__pb2.HeartbeatResponse.SerializeToString,
        ),
        "Discover": grpc.unary_unary_rpc_method_handler(
            servicer.Discover,
            request_deserializer=registry__pb2.DiscoverRequest.FromString,
            response_serializer=registry__pb2.DiscoverResponse.SerializeToString,
        ),
        "Watch": grpc.unary_stream_rpc_method_handler(
            servicer.Watch,
            request_deserializer=registry__pb2.WatchRequest.FromString,
            response_serializer=registry__pb2.ServiceEvent.SerializeToString,
        ),
        "ListServices": grpc.unary_unary_rpc_method_handler(
            servicer.ListServices,
            request_deserializer=registry__pb2.ListServicesRequest.FromString,
            response_serializer=registry__pb2.ListServicesResponse.SerializeToString,
        ),
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=registry__pb2.GetHealthRequest.FromString,
            response_serializer=registry__pb2.GetHealthResponse.SerializeToString,
        ),
        "GetServiceHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetServiceHealth,
            request_deserializer=registry__pb2.GetServiceHealthRequest.FromString,
            response_serializer=registry__pb2.GetServiceHealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "venturestrat.registry.v1.RegistryService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "venturestrat.registry.v1.RegistryService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RegistryService:
    """=============================================================================
    Registry Service
    =============================================================================

    """

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/Register",
            registry__pb2.RegisterRequest.SerializeToString,
            registry__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Deregister(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/Deregister",
            registry__pb2.DeregisterRequest.SerializeToString,
            registry__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Heartbeat(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/Heartbeat",
            registry__pb2.HeartbeatRequest.SerializeToString,
            registry__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Discover(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/Discover",
            registry__pb2.DiscoverRequest.SerializeToString,
            registry__pb2.DiscoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Watch(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/Watch",
            registry__pb2.WatchRequest.SerializeToString,
            registry__pb2.ServiceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListServices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/ListServices",
            registry__pb2.ListServicesRequest.SerializeToString,
            registry__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/GetHealth",
            registry__pb2.GetHealthRequest.SerializeToString,
            registry__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetServiceHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/venturestrat.registry.v1.RegistryService/GetServiceHealth",
            registry__pb2.GetServiceHealthRequest.SerializeToString,
            registry__pb2.GetServiceHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
