"""DocumentTemplate API Endpoints - Generated by Code Generator v1.0.0

This module provides RESTful API endpoints for DocumentTemplate CRUD operations.

Endpoints:
    - POST /api/v1/document_templates/ - Create a new DocumentTemplate
    - GET /api/v1/document_templates/{id} - Get DocumentTemplate by ID
    - GET /api/v1/document_templates/ - List DocumentTemplates with pagination
    - PUT /api/v1/document_templates/{id} - Update DocumentTemplate
    - DELETE /api/v1/document_templates/{id} - Delete DocumentTemplate
"""

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
from uuid import UUID
from legal_service.core.database import get_session
from legal_service.application.services.document_template_service import DocumentTemplateService
from legal_service.schemas.document_template import (
    DocumentTemplateCreate,
    DocumentTemplateUpdate,
    DocumentTemplateResponse,
)

# OpenAPI tag metadata for this router
TAGS_METADATA = [
    {
        "name": "DocumentTemplates",
        "description": "Operations for managing DocumentTemplate resources. Supports full CRUD operations with pagination.",
    }
]

router = APIRouter(tags=["DocumentTemplates"])


# Response examples for OpenAPI documentation
EXAMPLE_RESPONSE = {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "name": "example_name",
    "document_type": "example_document_type",
    "jurisdiction": "example_jurisdiction",
    "version": "example_version",
    "description": "example_description",
    "template_content": "example_template_content",
    "configuration_schema": {},
    "is_active": True,
    "clause_ids": {},
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-01-01T12:00:00Z",
}


@router.post(
    "",
    response_model=DocumentTemplateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create DocumentTemplate",
    description="Create a new DocumentTemplate with the provided data.",
    responses={
        201: {
            "description": "DocumentTemplate created successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        400: {
            "description": "Invalid request body",
            "content": {"application/json": {"example": {"detail": "Invalid request body"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "field required",
                                "type": "value_error.missing",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.post(
    "/",
    response_model=DocumentTemplateResponse,
    status_code=status.HTTP_201_CREATED,
    include_in_schema=False,
)
async def create_document_template(
    data: DocumentTemplateCreate, request: Request, session: AsyncSession = Depends(get_session)
) -> DocumentTemplateResponse:
    """
    Create a new DocumentTemplate.

    Creates a new DocumentTemplate record with the provided data. All required fields
    must be included in the request body. Auto-generated fields (id, created_at,
    updated_at) will be set automatically.

    Args:
        data: DocumentTemplateCreate schema with the DocumentTemplate data.
        request: FastAPI Request (for tenant context).
        session: Database session (injected).

    Returns:
        DocumentTemplateResponse: The created DocumentTemplate with all fields including auto-generated ones.

    Raises:
        HTTPException: 400 if request body is invalid, 422 if validation fails.
    """
    tenant_id = getattr(request.state, "tenant_id", None)
    service = DocumentTemplateService(session)
    return await service.create_document_template(data, tenant_id=tenant_id)


@router.get(
    "/{id}",
    response_model=DocumentTemplateResponse,
    summary="Get DocumentTemplate by ID",
    description="Retrieve a single DocumentTemplate by its unique identifier.",
    responses={
        200: {
            "description": "DocumentTemplate found",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "DocumentTemplate not found",
            "content": {"application/json": {"example": {"detail": "DocumentTemplate not found"}}},
        },
    },
)
@router.get("/{id}/", response_model=DocumentTemplateResponse, include_in_schema=False)
async def get_document_template(
    id: UUID, session: AsyncSession = Depends(get_session)
) -> DocumentTemplateResponse:
    """
    Get DocumentTemplate by ID.

    Retrieves a single DocumentTemplate record by its unique identifier (UUID).

    Args:
        id: The unique identifier (UUID) of the DocumentTemplate to retrieve.
        session: Database session (injected).

    Returns:
        DocumentTemplateResponse: The DocumentTemplate data if found.

    Raises:
        HTTPException: 404 if DocumentTemplate with the given ID is not found.
    """
    service = DocumentTemplateService(session)
    result = await service.get_document_template(id)
    if not result:
        raise HTTPException(status_code=404, detail="DocumentTemplate not found")
    return result


@router.get(
    "",
    response_model=List[DocumentTemplateResponse],
    summary="List DocumentTemplates",
    description="Retrieve a paginated list of DocumentTemplates. Supports both page-based and offset-based pagination.",
    responses={
        200: {
            "description": "List of DocumentTemplates",
            "content": {"application/json": {"example": [EXAMPLE_RESPONSE]}},
        },
    },
)
@router.get("/", response_model=List[DocumentTemplateResponse], include_in_schema=False)
async def list_document_templates(
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed). Used for page-based pagination.",
        example=1,
    ),
    page_size: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Number of items per page (1-200).",
        example=50,
    ),
    skip: Optional[int] = Query(
        default=None,
        ge=0,
        description="Number of items to skip. Used for offset-based pagination. Overrides page if provided.",
        example=0,
    ),
    limit: Optional[int] = Query(
        default=None,
        ge=1,
        le=200,
        description="Maximum number of items to return (1-200). Used with skip for offset-based pagination.",
        example=100,
    ),
    session: AsyncSession = Depends(get_session),
) -> List[DocumentTemplateResponse]:
    """
    List DocumentTemplates with pagination.

    Retrieves a paginated list of DocumentTemplate records. Supports two pagination styles:

    **Page-based pagination** (default):
    - Use `page` (1-indexed) and `page_size` parameters
    - Example: `?page=2&page_size=25` returns items 26-50

    **Offset-based pagination**:
    - Use `skip` and `limit` parameters
    - Example: `?skip=20&limit=10` returns items 21-30

    If both styles are provided, offset-based (`skip`/`limit`) takes precedence.

    Args:
        page: Page number (1-indexed, default: 1).
        page_size: Items per page (default: 50, max: 200).
        skip: Items to skip (offset-based pagination).
        limit: Max items to return (offset-based pagination).
        session: Database session (injected).

    Returns:
        List[DocumentTemplateResponse]: List of DocumentTemplates. Empty list if no records found.
    """
    # Convert page-based to offset-based pagination
    if skip is None and limit is None:
        # Use page/page_size (default)
        skip = (page - 1) * page_size if page > 0 else 0
        limit = page_size
    elif limit is None:
        limit = 100

    service = DocumentTemplateService(session)
    return await service.list_document_templates(skip, limit)


@router.put(
    "/{id}",
    response_model=DocumentTemplateResponse,
    summary="Update DocumentTemplate",
    description="Update an existing DocumentTemplate by ID. All fields in the request body are optional; only provided fields will be updated.",
    responses={
        200: {
            "description": "DocumentTemplate updated successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "DocumentTemplate not found",
            "content": {"application/json": {"example": {"detail": "DocumentTemplate not found"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "invalid value",
                                "type": "value_error",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.put("/{id}/", response_model=DocumentTemplateResponse, include_in_schema=False)
async def update_document_template(
    id: UUID, data: DocumentTemplateUpdate, session: AsyncSession = Depends(get_session)
) -> DocumentTemplateResponse:
    """
    Update DocumentTemplate.

    Updates an existing DocumentTemplate record with the provided data. This is a partial
    update (PATCH-like behavior) - only fields included in the request body will be updated.
    Fields set to `null` will clear the existing value (if nullable).

    The `updated_at` timestamp will be automatically set to the current time.

    Args:
        id: The unique identifier (UUID) of the DocumentTemplate to update.
        data: DocumentTemplateUpdate schema with fields to update (all fields optional).
        session: Database session (injected).

    Returns:
        DocumentTemplateResponse: The updated DocumentTemplate with all current values.

    Raises:
        HTTPException: 404 if DocumentTemplate not found, 422 if validation fails.
    """
    service = DocumentTemplateService(session)
    result = await service.update_document_template(id, data)
    if not result:
        raise HTTPException(status_code=404, detail="DocumentTemplate not found")
    return result


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete DocumentTemplate",
    description="Delete a DocumentTemplate by ID. This operation is permanent and cannot be undone.",
    responses={
        204: {
            "description": "DocumentTemplate deleted successfully (no content returned)",
        },
        404: {
            "description": "DocumentTemplate not found",
            "content": {"application/json": {"example": {"detail": "DocumentTemplate not found"}}},
        },
    },
)
@router.delete("/{id}/", status_code=status.HTTP_204_NO_CONTENT, include_in_schema=False)
async def delete_document_template(id: UUID, session: AsyncSession = Depends(get_session)) -> None:
    """
    Delete DocumentTemplate.

    Permanently deletes a DocumentTemplate record by its unique identifier.
    This operation cannot be undone.

    Args:
        id: The unique identifier (UUID) of the DocumentTemplate to delete.
        session: Database session (injected).

    Returns:
        None: Returns HTTP 204 No Content on success.

    Raises:
        HTTPException: 404 if DocumentTemplate with the given ID is not found.
    """
    service = DocumentTemplateService(session)
    deleted = await service.delete_document_template(id)
    if not deleted:
        raise HTTPException(status_code=404, detail="DocumentTemplate not found")
