"""EquityGrant API Endpoints - Generated by Code Generator v1.0.0

This module provides RESTful API endpoints for EquityGrant CRUD operations.

Endpoints:
    - POST /api/v1/equity_grants/ - Create a new EquityGrant
    - GET /api/v1/equity_grants/{id} - Get EquityGrant by ID
    - GET /api/v1/equity_grants/ - List EquityGrants with pagination
    - PUT /api/v1/equity_grants/{id} - Update EquityGrant
    - DELETE /api/v1/equity_grants/{id} - Delete EquityGrant
"""

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
from uuid import UUID
from legal_service.core.database import get_session
from legal_service.application.services.equity_grant_service import EquityGrantService
from legal_service.schemas.equity_grant import (
    EquityGrantCreate,
    EquityGrantUpdate,
    EquityGrantResponse,
)

# OpenAPI tag metadata for this router
TAGS_METADATA = [
    {
        "name": "EquityGrants",
        "description": "Operations for managing EquityGrant resources. Supports full CRUD operations with pagination.",
    }
]

router = APIRouter(tags=["EquityGrants"])


# Response examples for OpenAPI documentation
EXAMPLE_RESPONSE = {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "legal_entity_id": "550e8400-e29b-41d4-a716-446655440000",
    "holder_person_id": "550e8400-e29b-41d4-a716-446655440000",
    "holder_entity_id": "550e8400-e29b-41d4-a716-446655440000",
    "holder_type": "example_holder_type",
    "share_class": "example_share_class",
    "number_of_shares": 42,
    "percentage": "123.45",
    "valuation": "123.45",
    "issue_date": "2024-01-01",
    "source_document_id": "550e8400-e29b-41d4-a716-446655440000",
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-01-01T12:00:00Z",
}


@router.post(
    "",
    response_model=EquityGrantResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create EquityGrant",
    description="Create a new EquityGrant with the provided data.",
    responses={
        201: {
            "description": "EquityGrant created successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        400: {
            "description": "Invalid request body",
            "content": {"application/json": {"example": {"detail": "Invalid request body"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "field required",
                                "type": "value_error.missing",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.post(
    "/",
    response_model=EquityGrantResponse,
    status_code=status.HTTP_201_CREATED,
    include_in_schema=False,
)
async def create_equity_grant(
    data: EquityGrantCreate, request: Request, session: AsyncSession = Depends(get_session)
) -> EquityGrantResponse:
    """
    Create a new EquityGrant.

    Creates a new EquityGrant record with the provided data. All required fields
    must be included in the request body. Auto-generated fields (id, created_at,
    updated_at) will be set automatically.

    Args:
        data: EquityGrantCreate schema with the EquityGrant data.
        request: FastAPI Request (for tenant context).
        session: Database session (injected).

    Returns:
        EquityGrantResponse: The created EquityGrant with all fields including auto-generated ones.

    Raises:
        HTTPException: 400 if request body is invalid, 422 if validation fails.
    """
    tenant_id = getattr(request.state, "tenant_id", None)
    service = EquityGrantService(session)
    return await service.create_equity_grant(data, tenant_id=tenant_id)


@router.get(
    "/{id}",
    response_model=EquityGrantResponse,
    summary="Get EquityGrant by ID",
    description="Retrieve a single EquityGrant by its unique identifier.",
    responses={
        200: {
            "description": "EquityGrant found",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "EquityGrant not found",
            "content": {"application/json": {"example": {"detail": "EquityGrant not found"}}},
        },
    },
)
@router.get("/{id}/", response_model=EquityGrantResponse, include_in_schema=False)
async def get_equity_grant(
    id: UUID, session: AsyncSession = Depends(get_session)
) -> EquityGrantResponse:
    """
    Get EquityGrant by ID.

    Retrieves a single EquityGrant record by its unique identifier (UUID).

    Args:
        id: The unique identifier (UUID) of the EquityGrant to retrieve.
        session: Database session (injected).

    Returns:
        EquityGrantResponse: The EquityGrant data if found.

    Raises:
        HTTPException: 404 if EquityGrant with the given ID is not found.
    """
    service = EquityGrantService(session)
    result = await service.get_equity_grant(id)
    if not result:
        raise HTTPException(status_code=404, detail="EquityGrant not found")
    return result


@router.get(
    "",
    response_model=List[EquityGrantResponse],
    summary="List EquityGrants",
    description="Retrieve a paginated list of EquityGrants. Supports both page-based and offset-based pagination.",
    responses={
        200: {
            "description": "List of EquityGrants",
            "content": {"application/json": {"example": [EXAMPLE_RESPONSE]}},
        },
    },
)
@router.get("/", response_model=List[EquityGrantResponse], include_in_schema=False)
async def list_equity_grants(
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed). Used for page-based pagination.",
        example=1,
    ),
    page_size: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Number of items per page (1-200).",
        example=50,
    ),
    skip: Optional[int] = Query(
        default=None,
        ge=0,
        description="Number of items to skip. Used for offset-based pagination. Overrides page if provided.",
        example=0,
    ),
    limit: Optional[int] = Query(
        default=None,
        ge=1,
        le=200,
        description="Maximum number of items to return (1-200). Used with skip for offset-based pagination.",
        example=100,
    ),
    session: AsyncSession = Depends(get_session),
) -> List[EquityGrantResponse]:
    """
    List EquityGrants with pagination.

    Retrieves a paginated list of EquityGrant records. Supports two pagination styles:

    **Page-based pagination** (default):
    - Use `page` (1-indexed) and `page_size` parameters
    - Example: `?page=2&page_size=25` returns items 26-50

    **Offset-based pagination**:
    - Use `skip` and `limit` parameters
    - Example: `?skip=20&limit=10` returns items 21-30

    If both styles are provided, offset-based (`skip`/`limit`) takes precedence.

    Args:
        page: Page number (1-indexed, default: 1).
        page_size: Items per page (default: 50, max: 200).
        skip: Items to skip (offset-based pagination).
        limit: Max items to return (offset-based pagination).
        session: Database session (injected).

    Returns:
        List[EquityGrantResponse]: List of EquityGrants. Empty list if no records found.
    """
    # Convert page-based to offset-based pagination
    if skip is None and limit is None:
        # Use page/page_size (default)
        skip = (page - 1) * page_size if page > 0 else 0
        limit = page_size
    elif limit is None:
        limit = 100

    service = EquityGrantService(session)
    return await service.list_equity_grants(skip, limit)


@router.put(
    "/{id}",
    response_model=EquityGrantResponse,
    summary="Update EquityGrant",
    description="Update an existing EquityGrant by ID. All fields in the request body are optional; only provided fields will be updated.",
    responses={
        200: {
            "description": "EquityGrant updated successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "EquityGrant not found",
            "content": {"application/json": {"example": {"detail": "EquityGrant not found"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "invalid value",
                                "type": "value_error",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.put("/{id}/", response_model=EquityGrantResponse, include_in_schema=False)
async def update_equity_grant(
    id: UUID, data: EquityGrantUpdate, session: AsyncSession = Depends(get_session)
) -> EquityGrantResponse:
    """
    Update EquityGrant.

    Updates an existing EquityGrant record with the provided data. This is a partial
    update (PATCH-like behavior) - only fields included in the request body will be updated.
    Fields set to `null` will clear the existing value (if nullable).

    The `updated_at` timestamp will be automatically set to the current time.

    Args:
        id: The unique identifier (UUID) of the EquityGrant to update.
        data: EquityGrantUpdate schema with fields to update (all fields optional).
        session: Database session (injected).

    Returns:
        EquityGrantResponse: The updated EquityGrant with all current values.

    Raises:
        HTTPException: 404 if EquityGrant not found, 422 if validation fails.
    """
    service = EquityGrantService(session)
    result = await service.update_equity_grant(id, data)
    if not result:
        raise HTTPException(status_code=404, detail="EquityGrant not found")
    return result


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete EquityGrant",
    description="Delete a EquityGrant by ID. This operation is permanent and cannot be undone.",
    responses={
        204: {
            "description": "EquityGrant deleted successfully (no content returned)",
        },
        404: {
            "description": "EquityGrant not found",
            "content": {"application/json": {"example": {"detail": "EquityGrant not found"}}},
        },
    },
)
@router.delete("/{id}/", status_code=status.HTTP_204_NO_CONTENT, include_in_schema=False)
async def delete_equity_grant(id: UUID, session: AsyncSession = Depends(get_session)) -> None:
    """
    Delete EquityGrant.

    Permanently deletes a EquityGrant record by its unique identifier.
    This operation cannot be undone.

    Args:
        id: The unique identifier (UUID) of the EquityGrant to delete.
        session: Database session (injected).

    Returns:
        None: Returns HTTP 204 No Content on success.

    Raises:
        HTTPException: 404 if EquityGrant with the given ID is not found.
    """
    service = EquityGrantService(session)
    deleted = await service.delete_equity_grant(id)
    if not deleted:
        raise HTTPException(status_code=404, detail="EquityGrant not found")
