"""VestingSchedule API Endpoints - Generated by Code Generator v1.0.0

This module provides RESTful API endpoints for VestingSchedule CRUD operations.

Endpoints:
    - POST /api/v1/vesting_schedules/ - Create a new VestingSchedule
    - GET /api/v1/vesting_schedules/{id} - Get VestingSchedule by ID
    - GET /api/v1/vesting_schedules/ - List VestingSchedules with pagination
    - PUT /api/v1/vesting_schedules/{id} - Update VestingSchedule
    - DELETE /api/v1/vesting_schedules/{id} - Delete VestingSchedule
"""

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
from uuid import UUID
from legal_service.core.database import get_session
from legal_service.application.services.vesting_schedule_service import VestingScheduleService
from legal_service.schemas.vesting_schedule import (
    VestingScheduleCreate,
    VestingScheduleUpdate,
    VestingScheduleResponse,
)

# OpenAPI tag metadata for this router
TAGS_METADATA = [
    {
        "name": "VestingSchedules",
        "description": "Operations for managing VestingSchedule resources. Supports full CRUD operations with pagination.",
    }
]

router = APIRouter(tags=["VestingSchedules"])


# Response examples for OpenAPI documentation
EXAMPLE_RESPONSE = {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "equity_grant_id": "550e8400-e29b-41d4-a716-446655440000",
    "total_period_months": 42,
    "cliff_months": 42,
    "start_date": "2024-01-01",
    "acceleration_trigger": "example_acceleration_trigger",
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-01-01T12:00:00Z",
}


@router.post(
    "",
    response_model=VestingScheduleResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create VestingSchedule",
    description="Create a new VestingSchedule with the provided data.",
    responses={
        201: {
            "description": "VestingSchedule created successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        400: {
            "description": "Invalid request body",
            "content": {"application/json": {"example": {"detail": "Invalid request body"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "field required",
                                "type": "value_error.missing",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.post(
    "/",
    response_model=VestingScheduleResponse,
    status_code=status.HTTP_201_CREATED,
    include_in_schema=False,
)
async def create_vesting_schedule(
    data: VestingScheduleCreate, request: Request, session: AsyncSession = Depends(get_session)
) -> VestingScheduleResponse:
    """
    Create a new VestingSchedule.

    Creates a new VestingSchedule record with the provided data. All required fields
    must be included in the request body. Auto-generated fields (id, created_at,
    updated_at) will be set automatically.

    Args:
        data: VestingScheduleCreate schema with the VestingSchedule data.
        request: FastAPI Request (for tenant context).
        session: Database session (injected).

    Returns:
        VestingScheduleResponse: The created VestingSchedule with all fields including auto-generated ones.

    Raises:
        HTTPException: 400 if request body is invalid, 422 if validation fails.
    """
    tenant_id = getattr(request.state, "tenant_id", None)
    service = VestingScheduleService(session)
    return await service.create_vesting_schedule(data, tenant_id=tenant_id)


@router.get(
    "/{id}",
    response_model=VestingScheduleResponse,
    summary="Get VestingSchedule by ID",
    description="Retrieve a single VestingSchedule by its unique identifier.",
    responses={
        200: {
            "description": "VestingSchedule found",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "VestingSchedule not found",
            "content": {"application/json": {"example": {"detail": "VestingSchedule not found"}}},
        },
    },
)
@router.get("/{id}/", response_model=VestingScheduleResponse, include_in_schema=False)
async def get_vesting_schedule(
    id: UUID, session: AsyncSession = Depends(get_session)
) -> VestingScheduleResponse:
    """
    Get VestingSchedule by ID.

    Retrieves a single VestingSchedule record by its unique identifier (UUID).

    Args:
        id: The unique identifier (UUID) of the VestingSchedule to retrieve.
        session: Database session (injected).

    Returns:
        VestingScheduleResponse: The VestingSchedule data if found.

    Raises:
        HTTPException: 404 if VestingSchedule with the given ID is not found.
    """
    service = VestingScheduleService(session)
    result = await service.get_vesting_schedule(id)
    if not result:
        raise HTTPException(status_code=404, detail="VestingSchedule not found")
    return result


@router.get(
    "",
    response_model=List[VestingScheduleResponse],
    summary="List VestingSchedules",
    description="Retrieve a paginated list of VestingSchedules. Supports both page-based and offset-based pagination.",
    responses={
        200: {
            "description": "List of VestingSchedules",
            "content": {"application/json": {"example": [EXAMPLE_RESPONSE]}},
        },
    },
)
@router.get("/", response_model=List[VestingScheduleResponse], include_in_schema=False)
async def list_vesting_schedules(
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed). Used for page-based pagination.",
        example=1,
    ),
    page_size: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Number of items per page (1-200).",
        example=50,
    ),
    skip: Optional[int] = Query(
        default=None,
        ge=0,
        description="Number of items to skip. Used for offset-based pagination. Overrides page if provided.",
        example=0,
    ),
    limit: Optional[int] = Query(
        default=None,
        ge=1,
        le=200,
        description="Maximum number of items to return (1-200). Used with skip for offset-based pagination.",
        example=100,
    ),
    session: AsyncSession = Depends(get_session),
) -> List[VestingScheduleResponse]:
    """
    List VestingSchedules with pagination.

    Retrieves a paginated list of VestingSchedule records. Supports two pagination styles:

    **Page-based pagination** (default):
    - Use `page` (1-indexed) and `page_size` parameters
    - Example: `?page=2&page_size=25` returns items 26-50

    **Offset-based pagination**:
    - Use `skip` and `limit` parameters
    - Example: `?skip=20&limit=10` returns items 21-30

    If both styles are provided, offset-based (`skip`/`limit`) takes precedence.

    Args:
        page: Page number (1-indexed, default: 1).
        page_size: Items per page (default: 50, max: 200).
        skip: Items to skip (offset-based pagination).
        limit: Max items to return (offset-based pagination).
        session: Database session (injected).

    Returns:
        List[VestingScheduleResponse]: List of VestingSchedules. Empty list if no records found.
    """
    # Convert page-based to offset-based pagination
    if skip is None and limit is None:
        # Use page/page_size (default)
        skip = (page - 1) * page_size if page > 0 else 0
        limit = page_size
    elif limit is None:
        limit = 100

    service = VestingScheduleService(session)
    return await service.list_vesting_schedules(skip, limit)


@router.put(
    "/{id}",
    response_model=VestingScheduleResponse,
    summary="Update VestingSchedule",
    description="Update an existing VestingSchedule by ID. All fields in the request body are optional; only provided fields will be updated.",
    responses={
        200: {
            "description": "VestingSchedule updated successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "VestingSchedule not found",
            "content": {"application/json": {"example": {"detail": "VestingSchedule not found"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "invalid value",
                                "type": "value_error",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.put("/{id}/", response_model=VestingScheduleResponse, include_in_schema=False)
async def update_vesting_schedule(
    id: UUID, data: VestingScheduleUpdate, session: AsyncSession = Depends(get_session)
) -> VestingScheduleResponse:
    """
    Update VestingSchedule.

    Updates an existing VestingSchedule record with the provided data. This is a partial
    update (PATCH-like behavior) - only fields included in the request body will be updated.
    Fields set to `null` will clear the existing value (if nullable).

    The `updated_at` timestamp will be automatically set to the current time.

    Args:
        id: The unique identifier (UUID) of the VestingSchedule to update.
        data: VestingScheduleUpdate schema with fields to update (all fields optional).
        session: Database session (injected).

    Returns:
        VestingScheduleResponse: The updated VestingSchedule with all current values.

    Raises:
        HTTPException: 404 if VestingSchedule not found, 422 if validation fails.
    """
    service = VestingScheduleService(session)
    result = await service.update_vesting_schedule(id, data)
    if not result:
        raise HTTPException(status_code=404, detail="VestingSchedule not found")
    return result


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete VestingSchedule",
    description="Delete a VestingSchedule by ID. This operation is permanent and cannot be undone.",
    responses={
        204: {
            "description": "VestingSchedule deleted successfully (no content returned)",
        },
        404: {
            "description": "VestingSchedule not found",
            "content": {"application/json": {"example": {"detail": "VestingSchedule not found"}}},
        },
    },
)
@router.delete("/{id}/", status_code=status.HTTP_204_NO_CONTENT, include_in_schema=False)
async def delete_vesting_schedule(id: UUID, session: AsyncSession = Depends(get_session)) -> None:
    """
    Delete VestingSchedule.

    Permanently deletes a VestingSchedule record by its unique identifier.
    This operation cannot be undone.

    Args:
        id: The unique identifier (UUID) of the VestingSchedule to delete.
        session: Database session (injected).

    Returns:
        None: Returns HTTP 204 No Content on success.

    Raises:
        HTTPException: 404 if VestingSchedule with the given ID is not found.
    """
    service = VestingScheduleService(session)
    deleted = await service.delete_vesting_schedule(id)
    if not deleted:
        raise HTTPException(status_code=404, detail="VestingSchedule not found")
