"""VestingSchedule Application Service - Generated by Code Generator v1.0.0"""

from typing import List, Optional
from uuid import UUID
import structlog

from legal_service.infrastructure.repositories.vesting_schedule_repository import (
    VestingScheduleRepository,
)
from legal_service.infrastructure.orm.vesting_schedule import VestingSchedule
from legal_service.schemas.vesting_schedule import (
    VestingScheduleCreate,
    VestingScheduleUpdate,
    VestingScheduleResponse,
)
from legal_service.integrations.events import event_publisher
from legal_service.integrations.metrics import entity_operations_total

logger = structlog.get_logger(__name__)


class VestingScheduleService:
    """Application service for VestingSchedule use cases."""

    def __init__(self, session=None):
        """Initialize service with repository."""
        self.repository = VestingScheduleRepository(session)

    async def create_vesting_schedule(
        self, data: VestingScheduleCreate, tenant_id: str = None
    ) -> VestingScheduleResponse:
        """Create new VestingSchedule."""
        try:
            data_dict = data.model_dump()
            if tenant_id:
                data_dict["tenant_id"] = tenant_id

            # BaseModel.create() returns the created instance directly
            created = await self.repository.create(**data_dict)

            # Publish event
            await event_publisher.publish(
                entity_name="vesting_schedule",
                action="created",
                data=created.to_dict(),
                tenant_id=tenant_id,
            )

            # Track metric
            entity_operations_total.labels(
                entity="vesting_schedule", operation="create", status="success"
            ).inc()

            # Convert BaseModel to dict for response
            return VestingScheduleResponse(**created.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="vesting_schedule", operation="create", status="error"
            ).inc()
            logger.error("create_vesting_schedule_failed", error=str(e))
            raise

    async def get_vesting_schedule(self, id: UUID) -> Optional[VestingScheduleResponse]:
        """Get VestingSchedule by ID."""
        orm_obj = await self.repository.get_by_id(id)
        return VestingScheduleResponse(**orm_obj.to_dict()) if orm_obj else None

    async def list_vesting_schedules(
        self, skip: int = 0, limit: int = 100
    ) -> List[VestingScheduleResponse]:
        """List VestingSchedules with pagination."""
        orm_objs = await self.repository.get_all(skip, limit)
        return [VestingScheduleResponse(**obj.to_dict()) for obj in orm_objs]

    async def update_vesting_schedule(
        self, id: UUID, data: VestingScheduleUpdate
    ) -> Optional[VestingScheduleResponse]:
        """Update VestingSchedule."""
        try:
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return None

            # Update fields from DTO
            for key, value in data.model_dump(exclude_unset=True).items():
                setattr(orm_obj, key, value)

            # BaseModel.save() returns self
            updated = await self.repository.update(orm_obj)

            # Publish event
            await event_publisher.publish(
                entity_name="vesting_schedule",
                action="updated",
                data=updated.to_dict(),
                tenant_id=getattr(updated, "tenant_id", None),
            )

            # Track metric
            entity_operations_total.labels(
                entity="vesting_schedule", operation="update", status="success"
            ).inc()

            return VestingScheduleResponse(**updated.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="vesting_schedule", operation="update", status="error"
            ).inc()
            logger.error("update_vesting_schedule_failed", id=str(id), error=str(e))
            raise

    async def delete_vesting_schedule(self, id: UUID) -> bool:
        """Delete VestingSchedule."""
        try:
            # Get entity before deletion
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return False

            entity_data = orm_obj.to_dict()

            # Delete
            deleted = await self.repository.delete(id)

            if deleted:
                # Publish event
                await event_publisher.publish(
                    entity_name="vesting_schedule",
                    action="deleted",
                    data=entity_data,
                    tenant_id=entity_data.get("tenant_id"),
                )

                # Track metric
                entity_operations_total.labels(
                    entity="vesting_schedule", operation="delete", status="success"
                ).inc()

            return deleted

        except Exception as e:
            entity_operations_total.labels(
                entity="vesting_schedule", operation="delete", status="error"
            ).inc()
            logger.error("delete_vesting_schedule_failed", id=str(id), error=str(e))
            raise

    async def search_vesting_schedules(
        self, domain: list = None, skip: int = 0, limit: int = 100
    ) -> List[VestingScheduleResponse]:
        """
        Search VestingSchedules with domain filtering.

        Args:
            domain: domain filter (e.g., [('field', '=', 'value')])
            skip: Offset for pagination
            limit: Maximum records to return

        Returns:
            List of matching VestingSchedule instances
        """
        orm_objs = await self.repository.search(domain, skip, limit)
        return [VestingScheduleResponse(**obj.to_dict()) for obj in orm_objs]

    async def count_vesting_schedules(self, domain: list = None) -> int:
        """
        Count VestingSchedules matching domain.

        Args:
            domain: Optional domain filter

        Returns:
            Number of matching records
        """
        return await self.repository.count(domain)

    async def bulk_create_vesting_schedules(
        self, records_data: List[VestingScheduleCreate]
    ) -> List[VestingScheduleResponse]:
        """
        Create multiple VestingSchedules efficiently.

        Args:
            records_data: List of create DTOs

        Returns:
            List of created VestingSchedule instances
        """
        # Convert DTOs to dicts
        data_dicts = [record.model_dump() for record in records_data]

        # Bulk create
        created_objs = await self.repository.bulk_create(data_dicts)

        return [VestingScheduleResponse(**obj.to_dict()) for obj in created_objs]
