/**
 * DocumentParty Type Definitions
 *
 * This file contains type definitions for the DocumentParty entity:
 * - DocumentParty: Full entity model with all fields
 * - DocumentPartyCreateRequest: Data for creating a new document_party
 * - DocumentPartyUpdateRequest: Partial data for updating a document_party
 * - DocumentPartyListResponse: Paginated list response
 * - DocumentPartyFilterOptions: Query parameters for filtering
 * - DocumentPartyDropdownOption: Options for select components
 *
 * Links a legal document to its parties (entity + signatory) with role designation
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:50.827870Z
 */

// ============================================================================
// Base Types
// ============================================================================

/**
 * Base filter interface with common query parameters
 * Provides pagination, sorting, and search capabilities
 */
export interface BaseEntityFilters {
  /** Search query string - searches across multiple text fields */
  search?: string;
  /** Active/inactive status filter */
  is_active?: boolean;
  /** Pagination: page number (1-indexed) */
  page?: number;
  /** Pagination: items per page */
  page_size?: number;
  /** Sort field name */
  sort_by?: string;
  /** Sort direction */
  sort_order?: 'asc' | 'desc';
}

/**
 * Pagination metadata returned by the API
 */
export interface PaginationMeta {
  /** Current page number (1-indexed) */
  page: number;
  /** Number of items per page */
  page_size: number;
  /** Total number of items matching the query */
  total: number;
  /** Total number of pages */
  total_pages: number;
  /** Whether there is a next page */
  has_next: boolean;
  /** Whether there is a previous page */
  has_prev: boolean;
}

// ============================================================================
// DocumentParty Entity
// ============================================================================

/**
 * DocumentParty entity model
 *
 * Represents the full document_party entity as returned by the API.
 * Links a legal document to its parties (entity + signatory) with role designation
 *
 * @remarks
 * This interface matches the backend DocumentPartyDTO schema exactly.
 */
export interface DocumentParty {
  /** Unique identifier (UUID) */
  id: string;

  /** Legal Document Id */
  legal_document_id: string;

  /** Company acting as party to the document */
  legal_entity_id: string;

  /** Person signing on behalf of the entity */
  signatory_id: string | null;

  /** Role in the document context */
  party_role: string;

  /** Custom label, e.g. 'The Disclosing Party' */
  party_label: string | null;

  /** Creation timestamp (ISO 8601) */
  created_at: string;

  /** Last update timestamp (ISO 8601) */
  updated_at: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Request/Response Types
// ============================================================================

/**
 * DocumentParty creation request data
 *
 * Used when creating a new document_party. Omits system-generated fields
 * like id, timestamps, and audit fields.
 *
 * @remarks
 * Matches the backend DocumentPartyCreateDTO schema.
 */
export interface DocumentPartyCreateRequest {
  /** Legal Document Id (required) */
  legal_document_id: string;

  /** Company acting as party to the document (required) */
  legal_entity_id: string;

  /** Person signing on behalf of the entity (optional) */
  signatory_id?: string;

  /** Role in the document context (required) */
  party_role: string;

  /** Custom label, e.g. 'The Disclosing Party' (optional) */
  party_label?: string;

  /** Active status (defaults to true for new document_parties) */
  is_active?: boolean;
}

/**
 * DocumentParty update request data
 *
 * Used when updating an existing document_party. All fields are optional
 * to support partial updates.
 *
 * @remarks
 * Matches the backend DocumentPartyUpdateDTO schema.
 */
export interface DocumentPartyUpdateRequest {
  /** Legal Document Id */
  legal_document_id?: string;

  /** Company acting as party to the document */
  legal_entity_id?: string;

  /** Person signing on behalf of the entity */
  signatory_id?: string | null;

  /** Role in the document context */
  party_role?: string;

  /** Custom label, e.g. 'The Disclosing Party' */
  party_label?: string | null;

  /** Active status */
  is_active?: boolean;
}

/**
 * DocumentParty list response
 *
 * Wrapper for paginated document_party list queries.
 */
export interface DocumentPartyListResponse {
  /** Array of document_party items */
  items: DocumentParty[];

  /** Alternative property name for items (for API compatibility) */
  document_parties?: DocumentParty[];

  /** Pagination metadata */
  pagination?: PaginationMeta;

  /** Total count of items matching the query */
  total?: number;
}

// ============================================================================
// Filter Types
// ============================================================================

/**
 * DocumentParty filter options for list queries
 *
 * Extends BaseEntityFilters with document_party-specific filtering options.
 */
export interface DocumentPartyFilterOptions extends BaseEntityFilters {
  /** Filter by legal document id */
  legal_document_id?: string;

  /** Filter by company acting as party to the document */
  legal_entity_id?: string;

  /** Filter by person signing on behalf of the entity */
  signatory_id?: string;

}

// ============================================================================
// Dropdown/Select Types
// ============================================================================

/**
 * DocumentParty dropdown option for select components
 *
 * Provides a standardized structure for dropdown/select options with
 * the full entity data attached for additional context.
 */
export interface DocumentPartyDropdownOption {
  /** Option value (typically the entity ID) */
  value: string;

  /** Display label for the option */
  label: string;

  /** Full entity data for additional context */
  data: DocumentParty;

  /** Whether this option should be disabled */
  disabled?: boolean;
}

// ============================================================================
// Summary Types
// ============================================================================

/**
 * DocumentParty summary for list views
 *
 * Contains minimal fields for efficient list rendering.
 * Use this type when you only need basic display information.
 */
export interface DocumentPartySummary {
  /** Unique identifier */
  id: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Form Types
// ============================================================================

/**
 * DocumentParty form data for React Hook Form integration
 *
 * Type alias for the create request that can be used with form libraries.
 * Provides sensible defaults for form state.
 */
export type DocumentPartyFormData = DocumentPartyCreateRequest;

/**
 * Default form values for new document_party
 *
 * Use this when initializing form state for creating a new document_party.
 */
export const DEFAULT_DOCUMENT_PARTY_FORM_DATA: Partial<DocumentPartyFormData> = {
  is_active: true,
};

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Single document_party API response
 */
export interface DocumentPartyResponse {
  /** The requested document_party entity */
  data: DocumentParty;
}

/**
 * DocumentParty mutation response (create/update)
 */
export interface DocumentPartyMutationResponse {
  /** The created or updated document_party */
  data: DocumentParty;

  /** Success message */
  message?: string;
}

/**
 * API error response for document_party operations
 */
export interface DocumentPartyApiError {
  /** HTTP status code */
  status_code: number;

  /** Error message */
  message: string;

  /** Error code for programmatic handling */
  error_code?: string;

  /** Detailed error information */
  detail?: string | Record<string, unknown>;

  /** Field-level validation errors */
  validation_errors?: Record<string, string[]>;
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Type guard to check if a value is a DocumentParty
 *
 * @param value - Value to check
 * @returns True if value is a DocumentParty
 */
export function isDocumentParty(value: unknown): value is DocumentParty {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.id === 'string' &&
    typeof obj.legal_document_id === 'string' &&
    typeof obj.legal_entity_id === 'string' &&
    typeof obj.party_role === 'string'
  );
}

/**
 * Type guard to check if a value is a DocumentPartyDropdownOption
 *
 * @param value - Value to check
 * @returns True if value is a DocumentPartyDropdownOption
 */
export function isDocumentPartyDropdownOption(
  value: unknown
): value is DocumentPartyDropdownOption {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.value === 'string' &&
    typeof obj.label === 'string' &&
    isDocumentParty(obj.data)
  );
}

// ============================================================================
// Exports
// ============================================================================

/** All document_party types re-exported for convenience */
export type {
  DocumentParty as DocumentPartyEntity,
  DocumentPartyCreateRequest as CreateDocumentPartyInput,
  DocumentPartyUpdateRequest as UpdateDocumentPartyInput,
};
