/**
 * InvestmentTerm Type Definitions
 *
 * This file contains type definitions for the InvestmentTerm entity:
 * - InvestmentTerm: Full entity model with all fields
 * - InvestmentTermCreateRequest: Data for creating a new investment_term
 * - InvestmentTermUpdateRequest: Partial data for updating a investment_term
 * - InvestmentTermListResponse: Paginated list response
 * - InvestmentTermFilterOptions: Query parameters for filtering
 * - InvestmentTermDropdownOption: Options for select components
 *
 * SAFE or priced round investment terms linked to a legal entity and investor person
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:52.908646Z
 */

// ============================================================================
// Base Types
// ============================================================================

/**
 * Base filter interface with common query parameters
 * Provides pagination, sorting, and search capabilities
 */
export interface BaseEntityFilters {
  /** Search query string - searches across multiple text fields */
  search?: string;
  /** Active/inactive status filter */
  is_active?: boolean;
  /** Pagination: page number (1-indexed) */
  page?: number;
  /** Pagination: items per page */
  page_size?: number;
  /** Sort field name */
  sort_by?: string;
  /** Sort direction */
  sort_order?: 'asc' | 'desc';
}

/**
 * Pagination metadata returned by the API
 */
export interface PaginationMeta {
  /** Current page number (1-indexed) */
  page: number;
  /** Number of items per page */
  page_size: number;
  /** Total number of items matching the query */
  total: number;
  /** Total number of pages */
  total_pages: number;
  /** Whether there is a next page */
  has_next: boolean;
  /** Whether there is a previous page */
  has_prev: boolean;
}

// ============================================================================
// InvestmentTerm Entity
// ============================================================================

/**
 * InvestmentTerm entity model
 *
 * Represents the full investment_term entity as returned by the API.
 * SAFE or priced round investment terms linked to a legal entity and investor person
 *
 * @remarks
 * This interface matches the backend InvestmentTermDTO schema exactly.
 */
export interface InvestmentTerm {
  /** Unique identifier (UUID) */
  id: string;

  /** Company receiving the investment */
  legal_entity_id: string;

  /** Person making the investment */
  investor_person_id: string;

  /** Cross-service reference to investor-service Investor */
  investor_id: string | null;

  /** Investment amount (must be > 0) */
  investment_amount: number;

  /** Currency */
  currency: string;

  /** SAFE valuation cap (null for uncapped) */
  valuation_cap: number | null;

  /** Discount percentage 0-30 (null if no discount) */
  discount_percentage: number | null;

  /** Investment Date */
  investment_date: string;

  /** Pro Rata Rights */
  pro_rata_rights: boolean;

  /** Reference to LegalDocument that defines these terms */
  source_document_id: string | null;

  /** Creation timestamp (ISO 8601) */
  created_at: string;

  /** Last update timestamp (ISO 8601) */
  updated_at: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Request/Response Types
// ============================================================================

/**
 * InvestmentTerm creation request data
 *
 * Used when creating a new investment_term. Omits system-generated fields
 * like id, timestamps, and audit fields.
 *
 * @remarks
 * Matches the backend InvestmentTermCreateDTO schema.
 */
export interface InvestmentTermCreateRequest {
  /** Company receiving the investment (required) */
  legal_entity_id: string;

  /** Person making the investment (required) */
  investor_person_id: string;

  /** Cross-service reference to investor-service Investor (optional) */
  investor_id?: string;

  /** Investment amount (must be > 0) (required) */
  investment_amount: number;

  /** Currency (optional) */
  currency?: string;

  /** SAFE valuation cap (null for uncapped) (optional) */
  valuation_cap?: number;

  /** Discount percentage 0-30 (null if no discount) (optional) */
  discount_percentage?: number;

  /** Investment Date (required) */
  investment_date: string;

  /** Pro Rata Rights (optional) */
  pro_rata_rights?: boolean;

  /** Reference to LegalDocument that defines these terms (optional) */
  source_document_id?: string;

  /** Active status (defaults to true for new investment_terms) */
  is_active?: boolean;
}

/**
 * InvestmentTerm update request data
 *
 * Used when updating an existing investment_term. All fields are optional
 * to support partial updates.
 *
 * @remarks
 * Matches the backend InvestmentTermUpdateDTO schema.
 */
export interface InvestmentTermUpdateRequest {
  /** Company receiving the investment */
  legal_entity_id?: string;

  /** Person making the investment */
  investor_person_id?: string;

  /** Cross-service reference to investor-service Investor */
  investor_id?: string | null;

  /** Investment amount (must be > 0) */
  investment_amount?: number;

  /** Currency */
  currency?: string;

  /** SAFE valuation cap (null for uncapped) */
  valuation_cap?: number | null;

  /** Discount percentage 0-30 (null if no discount) */
  discount_percentage?: number | null;

  /** Investment Date */
  investment_date?: string;

  /** Pro Rata Rights */
  pro_rata_rights?: boolean;

  /** Reference to LegalDocument that defines these terms */
  source_document_id?: string | null;

  /** Active status */
  is_active?: boolean;
}

/**
 * InvestmentTerm list response
 *
 * Wrapper for paginated investment_term list queries.
 */
export interface InvestmentTermListResponse {
  /** Array of investment_term items */
  items: InvestmentTerm[];

  /** Alternative property name for items (for API compatibility) */
  investment_terms?: InvestmentTerm[];

  /** Pagination metadata */
  pagination?: PaginationMeta;

  /** Total count of items matching the query */
  total?: number;
}

// ============================================================================
// Filter Types
// ============================================================================

/**
 * InvestmentTerm filter options for list queries
 *
 * Extends BaseEntityFilters with investment_term-specific filtering options.
 */
export interface InvestmentTermFilterOptions extends BaseEntityFilters {
  /** Filter by company receiving the investment */
  legal_entity_id?: string;

  /** Filter by person making the investment */
  investor_person_id?: string;

  /** Filter by cross-service reference to investor-service investor */
  investor_id?: string;

  /** Filter by reference to legaldocument that defines these terms */
  source_document_id?: string;

}

// ============================================================================
// Dropdown/Select Types
// ============================================================================

/**
 * InvestmentTerm dropdown option for select components
 *
 * Provides a standardized structure for dropdown/select options with
 * the full entity data attached for additional context.
 */
export interface InvestmentTermDropdownOption {
  /** Option value (typically the entity ID) */
  value: string;

  /** Display label for the option */
  label: string;

  /** Full entity data for additional context */
  data: InvestmentTerm;

  /** Whether this option should be disabled */
  disabled?: boolean;
}

// ============================================================================
// Summary Types
// ============================================================================

/**
 * InvestmentTerm summary for list views
 *
 * Contains minimal fields for efficient list rendering.
 * Use this type when you only need basic display information.
 */
export interface InvestmentTermSummary {
  /** Unique identifier */
  id: string;

  /** Active status */
  is_active: boolean;
}

// ============================================================================
// Form Types
// ============================================================================

/**
 * InvestmentTerm form data for React Hook Form integration
 *
 * Type alias for the create request that can be used with form libraries.
 * Provides sensible defaults for form state.
 */
export type InvestmentTermFormData = InvestmentTermCreateRequest;

/**
 * Default form values for new investment_term
 *
 * Use this when initializing form state for creating a new investment_term.
 */
export const DEFAULT_INVESTMENT_TERM_FORM_DATA: Partial<InvestmentTermFormData> = {
  is_active: true,
  currency: "USD",
  pro_rata_rights: false,
};

// ============================================================================
// API Response Types
// ============================================================================

/**
 * Single investment_term API response
 */
export interface InvestmentTermResponse {
  /** The requested investment_term entity */
  data: InvestmentTerm;
}

/**
 * InvestmentTerm mutation response (create/update)
 */
export interface InvestmentTermMutationResponse {
  /** The created or updated investment_term */
  data: InvestmentTerm;

  /** Success message */
  message?: string;
}

/**
 * API error response for investment_term operations
 */
export interface InvestmentTermApiError {
  /** HTTP status code */
  status_code: number;

  /** Error message */
  message: string;

  /** Error code for programmatic handling */
  error_code?: string;

  /** Detailed error information */
  detail?: string | Record<string, unknown>;

  /** Field-level validation errors */
  validation_errors?: Record<string, string[]>;
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Type guard to check if a value is a InvestmentTerm
 *
 * @param value - Value to check
 * @returns True if value is a InvestmentTerm
 */
export function isInvestmentTerm(value: unknown): value is InvestmentTerm {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.id === 'string' &&
    typeof obj.legal_entity_id === 'string' &&
    typeof obj.investor_person_id === 'string' &&
    typeof obj.investment_amount === 'number' &&
    typeof obj.investment_date === 'string'
  );
}

/**
 * Type guard to check if a value is a InvestmentTermDropdownOption
 *
 * @param value - Value to check
 * @returns True if value is a InvestmentTermDropdownOption
 */
export function isInvestmentTermDropdownOption(
  value: unknown
): value is InvestmentTermDropdownOption {
  if (!value || typeof value !== 'object') {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.value === 'string' &&
    typeof obj.label === 'string' &&
    isInvestmentTerm(obj.data)
  );
}

// ============================================================================
// Exports
// ============================================================================

/** All investment_term types re-exported for convenience */
export type {
  InvestmentTerm as InvestmentTermEntity,
  InvestmentTermCreateRequest as CreateInvestmentTermInput,
  InvestmentTermUpdateRequest as UpdateInvestmentTermInput,
};
