/**
 * ContactPerson Validation Hooks
 *
 * Domain-specific validation hooks for ContactPerson forms.
 * Implements client-side validation with optional server verification.
 *
 * Hooks provided:
 * - useBusinessDayValidation: Validate dates against business day calendars
 * - useContactPersonValidation: Combined validation hook for ContactPerson forms
 *
 * Features:
 * - Client-side instant validation for quick feedback
 * - Optional server-side verification for authoritative data
 * - React Hook Form integration
 * - Memoized validation functions
 * - Configurable validation rules
 *
 * Extracted from D2C platform patterns:
 * - useBusinessDayValidation (hybrid client/server validation)
 * - useCrossfieldValidation (cross-field date validation)
 * - useCurrencyFormatting (currency precision validation)
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:50.376358Z
 */

import { useCallback } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import type { ContactPersonCreateRequest } from '../types/contact_person.types';

// ============================================================================
// Types
// ============================================================================

/**
 * Validation severity levels
 * - error: Blocking validation failure
 * - warning: Non-blocking advisory message
 * - info: Informational message
 */
export type ValidationSeverity = 'error' | 'warning' | 'info';

/**
 * Single validation error or warning
 */
export interface ValidationError {
  /** Field that failed validation */
  field: string;
  /** Error message */
  message: string;
  /** Severity level */
  severity: ValidationSeverity;
  /** Validation rule type that triggered the error */
  type?: string;
}

/**
 * Result of form-level validation
 */
export interface ValidationResult {
  /** Whether all validations passed */
  isValid: boolean;
  /** Array of validation errors/warnings */
  errors: ValidationError[];
}

// ============================================================================
// Business Day Validation (extracted from D2C useBusinessDayValidation)
// ============================================================================

/**
 * Trading calendar types
 * Maps to financial market trading calendars for business day validation
 */
export type Calendar =
  | 'US'
  | 'UK'
  | 'TARGET'        // Eurozone
  | 'JAPAN'
  | 'AUSTRALIA'
  | 'HONG_KONG'
  | 'SINGAPORE'
  | 'CHINA'
  | 'CANADA'
  | 'SWITZERLAND'
  | 'SOUTH_KOREA'
  | 'INDIA'
  | 'SAUDI_ARABIA'
  | 'STOCKHOLM'
  | 'OSLO'
  | 'COPENHAGEN'
  | 'WARSAW'
  | 'PRAGUE'
  | 'BUDAPEST'
  | 'WEEKEND_ONLY';

/**
 * Business day validation result
 */
export interface BusinessDayValidationResult {
  /** Whether the date is a valid business day */
  isValid: boolean;
  /** Validation message */
  message?: string;
  /** Suggested next business day if validation fails */
  suggestedDate?: Date;
  /** Formatted suggested date string */
  suggestedDateFormatted?: string;
  /** The calendar used for validation */
  calendar: Calendar;
  /** Whether the date falls on a weekend */
  isWeekend?: boolean;
  /** Whether the date falls on a holiday */
  isHoliday?: boolean;
  /** Holiday name if applicable */
  holidayName?: string;
}

/**
 * Cache timing for server verification (24 hours)
 */
const BUSINESS_DAY_STALE_TIME = 24 * 60 * 60 * 1000;

/**
 * Common public holidays by calendar (client-side validation)
 * Server verification provides authoritative holiday data
 */
const COMMON_HOLIDAYS: Record<string, Array<{ month: number; day: number; name?: string }>> = {
  US: [
    { month: 1, day: 1, name: "New Year's Day" },
    { month: 7, day: 4, name: 'Independence Day' },
    { month: 12, day: 25, name: 'Christmas Day' },
  ],
  UK: [
    { month: 1, day: 1, name: "New Year's Day" },
    { month: 12, day: 25, name: 'Christmas Day' },
    { month: 12, day: 26, name: 'Boxing Day' },
  ],
  TARGET: [
    { month: 1, day: 1, name: "New Year's Day" },
    { month: 5, day: 1, name: 'Labour Day' },
    { month: 12, day: 25, name: 'Christmas Day' },
    { month: 12, day: 26, name: 'Boxing Day' },
  ],
  JAPAN: [
    { month: 1, day: 1, name: "New Year's Day" },
    { month: 1, day: 2, name: 'Bank Holiday' },
    { month: 1, day: 3, name: 'Bank Holiday' },
  ],
  WEEKEND_ONLY: [],
};

/**
 * Query keys for business day validation
 */
export const businessDayKeys = {
  all: ['business-day'] as const,
  verification: (date: string, calendar: Calendar, secondaryCalendar?: Calendar) =>
    [...businessDayKeys.all, 'verify', date, calendar, secondaryCalendar] as const,
};

/**
 * Options for the useBusinessDayValidation hook
 */
export interface UseBusinessDayValidationOptions {
  /** Calendar to use for validation */
  calendar?: Calendar;
  /** Currency code to derive calendar from (e.g., 'USD' -> 'US') */
  currency?: string;
  /** Secondary calendar for cross-currency validation */
  secondaryCalendar?: Calendar;
  /** API endpoint for server verification */
  apiEndpoint?: string;
}

/**
 * Hook for business day validation with hybrid client/server validation
 *
 * Provides instant client-side validation for weekend/known holidays,
 * with optional server verification for authoritative holiday data.
 *
 * @example
 * ```typescript
 * const { validateDate, verifyWithServer, getNextBusinessDay } =
 *   useBusinessDayValidation({ calendar: 'US' });
 *
 * const result = validateDate(new Date('2024-07-04'));
 * // { isValid: false, message: 'Date is a holiday (Independence Day)', ... }
 * ```
 */
export function useBusinessDayValidation(
  options: UseBusinessDayValidationOptions = {}
): {
  validateDate: (date: Date | string) => BusinessDayValidationResult;
  verifyWithServer: (date: Date | string) => Promise<BusinessDayValidationResult>;
  getNextBusinessDay: (date: Date | string) => Date;
  isWeekend: (date: Date | string) => boolean;
  isKnownHoliday: (date: Date | string) => { isHoliday: boolean; name?: string };
  calendar: Calendar;
  isVerifying: boolean;
  invalidateCache: () => void;
} {
  const {
    calendar = 'WEEKEND_ONLY',
    apiEndpoint = '/api/v1/calendar/validate-business-day',
  } = options;

  const queryClient = useQueryClient();

  /**
   * Parse date input to Date object
   */
  const parseDate = useCallback((date: Date | string): Date => {
    if (date instanceof Date) {
      return date;
    }
    const parsed = new Date(date);
    if (isNaN(parsed.getTime())) {
      throw new Error(`Invalid date: ${date}`);
    }
    return parsed;
  }, []);

  /**
   * Check if a date is a weekend
   */
  const isWeekend = useCallback(
    (date: Date | string): boolean => {
      const d = parseDate(date);
      const day = d.getDay();
      return day === 0 || day === 6;
    },
    [parseDate]
  );

  /**
   * Check if a date is a known holiday (client-side)
   */
  const isKnownHoliday = useCallback(
    (date: Date | string): { isHoliday: boolean; name?: string } => {
      const d = parseDate(date);
      const month = d.getMonth() + 1;
      const day = d.getDate();

      const holidays = COMMON_HOLIDAYS[calendar] || [];
      const matchingHoliday = holidays.find((h) => h.month === month && h.day === day);

      if (matchingHoliday) {
        return { isHoliday: true, name: matchingHoliday.name };
      }

      return { isHoliday: false };
    },
    [calendar, parseDate]
  );

  /**
   * Get the next business day from a given date
   */
  const getNextBusinessDay = useCallback(
    (date: Date | string): Date => {
      let nextDay = parseDate(date);
      nextDay = new Date(nextDay.getTime() + 24 * 60 * 60 * 1000);

      let iterations = 0;
      const maxIterations = 14; // Safety limit (2 weeks)

      while (iterations < maxIterations) {
        if (!isWeekend(nextDay)) {
          const { isHoliday } = isKnownHoliday(nextDay);
          if (!isHoliday) {
            return nextDay;
          }
        }
        nextDay = new Date(nextDay.getTime() + 24 * 60 * 60 * 1000);
        iterations++;
      }

      return nextDay;
    },
    [parseDate, isWeekend, isKnownHoliday]
  );

  /**
   * Format date for display
   */
  const formatDateDisplay = useCallback((date: Date): string => {
    return date.toLocaleDateString('en-US', {
      weekday: 'short',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }, []);

  /**
   * Validate a date client-side (instant)
   */
  const validateDate = useCallback(
    (date: Date | string): BusinessDayValidationResult => {
      try {
        const d = parseDate(date);
        const weekend = isWeekend(d);
        const holiday = isKnownHoliday(d);

        if (weekend) {
          const nextBizDay = getNextBusinessDay(d);
          return {
            isValid: false,
            message: `${formatDateDisplay(d)} falls on a weekend`,
            suggestedDate: nextBizDay,
            suggestedDateFormatted: formatDateDisplay(nextBizDay),
            calendar,
            isWeekend: true,
            isHoliday: false,
          };
        }

        if (holiday.isHoliday) {
          const nextBizDay = getNextBusinessDay(d);
          return {
            isValid: false,
            message: `${formatDateDisplay(d)} is a holiday${holiday.name ? ` (${holiday.name})` : ''}`,
            suggestedDate: nextBizDay,
            suggestedDateFormatted: formatDateDisplay(nextBizDay),
            calendar,
            isWeekend: false,
            isHoliday: true,
            holidayName: holiday.name,
          };
        }

        return {
          isValid: true,
          message: 'Date is a valid business day',
          calendar,
          isWeekend: false,
          isHoliday: false,
        };
      } catch (error) {
        return {
          isValid: false,
          message: error instanceof Error ? error.message : 'Invalid date',
          calendar,
        };
      }
    },
    [parseDate, isWeekend, isKnownHoliday, getNextBusinessDay, formatDateDisplay, calendar]
  );

  /**
   * Verify a date with server (lazy query)
   */
  const verifyWithServer = useCallback(
    async (date: Date | string): Promise<BusinessDayValidationResult> => {
      const d = parseDate(date);
      const dateStr = d.toISOString().split('T')[0];

      // Build cache key
      const cacheKey = businessDayKeys.verification(dateStr, calendar);

      try {
        // Check for cached result
        const cachedData = queryClient.getQueryData<BusinessDayValidationResult>(cacheKey);
        const queryState = queryClient.getQueryState(cacheKey);

        const now = Date.now();
        const isCacheFresh =
          queryState?.dataUpdatedAt && now - queryState.dataUpdatedAt < BUSINESS_DAY_STALE_TIME;

        if (cachedData && isCacheFresh) {
          return cachedData;
        }

        // Fetch from server
        const params = new URLSearchParams({
          date: dateStr,
          calendar,
        });

        const response = await fetch(`${apiEndpoint}?${params}`);

        if (!response.ok) {
          throw new Error(`Server verification failed: ${response.status}`);
        }

        const serverData = await response.json();
        const result: BusinessDayValidationResult = {
          isValid: serverData.is_valid,
          message: serverData.message,
          calendar,
          isWeekend: serverData.is_weekend,
          isHoliday: serverData.is_holiday,
          holidayName: serverData.holiday_name,
        };

        // Cache the result
        queryClient.setQueryData(cacheKey, result);

        return result;
      } catch (error) {
        // Fallback to client-side validation
        console.warn('Server verification failed, using client-side result:', error);
        return validateDate(date);
      }
    },
    [parseDate, calendar, queryClient, apiEndpoint, validateDate]
  );

  /**
   * Invalidate cached results
   */
  const invalidateCache = useCallback(() => {
    queryClient.invalidateQueries({ queryKey: businessDayKeys.all });
  }, [queryClient]);

  /**
   * Track verification state
   */
  const isVerifying = queryClient.isFetching({ queryKey: businessDayKeys.all }) > 0;

  return {
    validateDate,
    verifyWithServer,
    getNextBusinessDay,
    isWeekend,
    isKnownHoliday,
    calendar,
    isVerifying,
    invalidateCache,
  };
}

// ============================================================================
// Combined ContactPerson Validation Hook
// ============================================================================

/**
 * Options for the useContactPersonValidation hook
 */
export interface UseContactPersonValidationOptions {
  /** Calendar for business day validation */
  calendar?: Calendar;
  /** Currency for calendar derivation */
  currency?: string;
}

/**
 * ContactPerson form values for validation
 */
export type ContactPersonFormValues = Partial<ContactPersonCreateRequest> & {
  id?: string;
};

/**
 * Combined validation hook for ContactPerson forms
 *
 * Provides all validation functions needed for ContactPerson forms,
 * combining business day, crossfield, and currency validation as applicable.
 *
 * @example
 * ```typescript
 * const { validate, validateField, errors, isValid } =
 *   useContactPersonValidation({ calendar: 'US' });
 *
 * // Validate entire form
 * const result = validate(formValues);
 * if (!result.isValid) {
 *   console.log('Errors:', result.errors);
 * }
 *
 * // Validate single field
 * const fieldResult = validateField('settlementDate', formValues.settlementDate);
 * ```
 */
export function useContactPersonValidation(
options: UseContactPersonValidationOptions = {}
): {
  /** Validate entire form */
  validate: (values: ContactPersonFormValues) => ValidationResult;
  /** Validate single field */
  validateField: (field: keyof ContactPersonFormValues, value: unknown, allValues?: ContactPersonFormValues) => ValidationError | null;
  /** Business day validation functions */
  businessDay: ReturnType<typeof useBusinessDayValidation>;
} {
  const businessDay = useBusinessDayValidation({
    calendar: options.calendar,
    currency: options.currency,
  });



  /**
   * Validate a single field
   */
  const validateField = useCallback(
    (
      _field: keyof ContactPersonFormValues,
      _value: unknown,
      _allValues?: ContactPersonFormValues
    ): ValidationError | null => {
      // Date field validation


      return null;
    },
    [businessDay]
  );

  /**
   * Validate entire form
   */
  const validate = useCallback(
    (values: ContactPersonFormValues): ValidationResult => {
      const errors: ValidationError[] = [];

      // Validate each field
      for (const [field, value] of Object.entries(values)) {
        const error = validateField(
          field as keyof ContactPersonFormValues,
          value,
          values
        );
        if (error) {
          errors.push(error);
        }
      }


      // Remove duplicate errors (same field and message)
      const uniqueErrors = errors.filter(
        (error, index, self) =>
          index === self.findIndex((e) => e.field === error.field && e.message === error.message)
      );

      return {
        isValid: uniqueErrors.filter((e) => e.severity === 'error').length === 0,
        errors: uniqueErrors,
      };
    },
    [validateField]
  );

  return {
    validate,
    validateField,
    businessDay,
  };
}

export default useContactPersonValidation;
