"""PastInvestment DTO Schemas - Generated by Code Generator v1.0.0

This module defines Pydantic schemas for PastInvestment API operations:
    - PastInvestmentBase: Base schema with common fields
    - PastInvestmentCreate: Schema for creating new PastInvestments
    - PastInvestmentUpdate: Schema for updating existing PastInvestments
    - PastInvestmentResponse: Schema for API responses

All schemas include OpenAPI examples for better Swagger UI documentation.
"""

from pydantic import BaseModel, Field, ConfigDict
from datetime import datetime
from typing import Any, Optional, List, Annotated
from uuid import UUID


class PastInvestmentBase(BaseModel):
    """
    Base schema for PastInvestment.

    Contains all common fields shared between create, update, and response schemas.
    This schema is used as a base class and should not be used directly in API operations.
    """

    title: str = Field(
        max_length=255, description="Company name", json_schema_extra={"example": "example_title"}
    )
    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "title": "example_title",
            }
        },
    )


class PastInvestmentCreate(BaseModel):
    """
    Schema for creating PastInvestment.

    Contains only required and optional user-provided fields.
    Auto-generated fields (id, created_at, updated_at) are excluded.

    Example:
        ```python
        data = PastInvestmentCreate(            title="example_title",        )
        ```
    """

    title: str = Field(
        max_length=255, description="Company name", json_schema_extra={"example": "example_title"}
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "title": "example_title",
            }
        },
    )


class PastInvestmentUpdate(BaseModel):
    """
    Schema for updating PastInvestment.

    All fields are optional. Only include fields you want to update.
    Fields set to None will be ignored (not updated). To clear a field,
    use an explicit null value if the field is nullable.

    Example:
        ```python
        # Partial update - only update specific fields
        data = PastInvestmentUpdate(title="example_title")
        ```
    """

    title: Optional[str] = Field(
        default=None, description="Company name", json_schema_extra={"example": "example_title"}
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "title": "example_title",
            }
        },
    )


class PastInvestmentResponse(PastInvestmentBase):
    """
    Schema for PastInvestment API responses.

    Extends PastInvestmentBase with auto-generated fields (id, timestamps).
    This is the schema returned by all GET, POST, and PUT operations.
    """

    id: str = Field(
        ...,
        description="Unique identifier for the PastInvestment",
        json_schema_extra={"example": "550e8400-e29b-41d4-a716-446655440000"},
    )
    created_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the PastInvestment was created",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when the PastInvestment was last updated",
        json_schema_extra={"example": "2024-01-01T12:00:00Z"},
    )

    model_config = ConfigDict(
        from_attributes=True,
        json_schema_extra={
            "example": {
                "id": "550e8400-e29b-41d4-a716-446655440000",
                "title": "example_title",
                "created_at": "2024-01-01T12:00:00Z",
                "updated_at": "2024-01-01T12:00:00Z",
            }
        },
    )
