"""Session Application Service - Generated by Code Generator v1.0.0"""

from typing import List, Optional
from uuid import UUID
import structlog

from auth_service.infrastructure.repositories.session_repository import SessionRepository
from auth_service.infrastructure.orm.session import Session
from auth_service.schemas.session import SessionCreate, SessionUpdate, SessionResponse
from auth_service.integrations.events import event_publisher
from auth_service.integrations.metrics import entity_operations_total

logger = structlog.get_logger(__name__)


class SessionService:
    """Application service for Session use cases."""

    def __init__(self, session=None):
        """Initialize service with repository."""
        self.repository = SessionRepository(session)

    async def create_session(self, data: SessionCreate, tenant_id: str = None) -> SessionResponse:
        """Create new Session."""
        try:
            data_dict = data.model_dump()
            if tenant_id:
                data_dict["tenant_id"] = tenant_id

            # BaseModel.create() returns the created instance directly
            created = await self.repository.create(**data_dict)

            # Publish event
            await event_publisher.publish(
                entity_name="session",
                action="created",
                data=created.to_dict(),
                tenant_id=tenant_id,
            )

            # Track metric
            entity_operations_total.labels(
                entity="session", operation="create", status="success"
            ).inc()

            # Convert BaseModel to dict for response
            return SessionResponse(**created.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="session", operation="create", status="error"
            ).inc()
            logger.error("create_session_failed", error=str(e))
            raise

    async def get_session(self, id: UUID) -> Optional[SessionResponse]:
        """Get Session by ID."""
        orm_obj = await self.repository.get_by_id(id)
        return SessionResponse(**orm_obj.to_dict()) if orm_obj else None

    async def list_sessions(self, skip: int = 0, limit: int = 100) -> List[SessionResponse]:
        """List Sessions with pagination."""
        orm_objs = await self.repository.get_all(skip, limit)
        return [SessionResponse(**obj.to_dict()) for obj in orm_objs]

    async def update_session(self, id: UUID, data: SessionUpdate) -> Optional[SessionResponse]:
        """Update Session."""
        try:
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return None

            # Update fields from DTO
            for key, value in data.model_dump(exclude_unset=True).items():
                setattr(orm_obj, key, value)

            # BaseModel.save() returns self
            updated = await self.repository.update(orm_obj)

            # Publish event
            await event_publisher.publish(
                entity_name="session",
                action="updated",
                data=updated.to_dict(),
                tenant_id=getattr(updated, "tenant_id", None),
            )

            # Track metric
            entity_operations_total.labels(
                entity="session", operation="update", status="success"
            ).inc()

            return SessionResponse(**updated.to_dict())

        except Exception as e:
            entity_operations_total.labels(
                entity="session", operation="update", status="error"
            ).inc()
            logger.error("update_session_failed", id=str(id), error=str(e))
            raise

    async def delete_session(self, id: UUID) -> bool:
        """Delete Session."""
        try:
            # Get entity before deletion
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return False

            entity_data = orm_obj.to_dict()

            # Delete
            deleted = await self.repository.delete(id)

            if deleted:
                # Publish event
                await event_publisher.publish(
                    entity_name="session",
                    action="deleted",
                    data=entity_data,
                    tenant_id=entity_data.get("tenant_id"),
                )

                # Track metric
                entity_operations_total.labels(
                    entity="session", operation="delete", status="success"
                ).inc()

            return deleted

        except Exception as e:
            entity_operations_total.labels(
                entity="session", operation="delete", status="error"
            ).inc()
            logger.error("delete_session_failed", id=str(id), error=str(e))
            raise

    async def search_sessions(
        self, domain: list = None, skip: int = 0, limit: int = 100
    ) -> List[SessionResponse]:
        """
        Search Sessions with domain filtering.

        Args:
            domain: domain filter (e.g., [('field', '=', 'value')])
            skip: Offset for pagination
            limit: Maximum records to return

        Returns:
            List of matching Session instances
        """
        orm_objs = await self.repository.search(domain, skip, limit)
        return [SessionResponse(**obj.to_dict()) for obj in orm_objs]

    async def count_sessions(self, domain: list = None) -> int:
        """
        Count Sessions matching domain.

        Args:
            domain: Optional domain filter

        Returns:
            Number of matching records
        """
        return await self.repository.count(domain)

    async def bulk_create_sessions(
        self, records_data: List[SessionCreate]
    ) -> List[SessionResponse]:
        """
        Create multiple Sessions efficiently.

        Args:
            records_data: List of create DTOs

        Returns:
            List of created Session instances
        """
        # Convert DTOs to dicts
        data_dicts = [record.model_dump() for record in records_data]

        # Bulk create
        created_objs = await self.repository.bulk_create(data_dicts)

        return [SessionResponse(**obj.to_dict()) for obj in created_objs]
