"""User Application Service - Generated by Code Generator v1.0.0"""

from typing import List, Optional
from uuid import UUID
import structlog

from auth_service.infrastructure.repositories.user_repository import UserRepository
from auth_service.infrastructure.orm.user import User
from auth_service.schemas.user import UserCreate, UserUpdate, UserResponse
from auth_service.integrations.events import event_publisher
from auth_service.integrations.metrics import entity_operations_total

logger = structlog.get_logger(__name__)


class UserService:
    """Application service for User use cases."""

    def __init__(self, session=None):
        """Initialize service with repository."""
        self.repository = UserRepository(session)

    async def create_user(self, data: UserCreate, tenant_id: str = None) -> UserResponse:
        """Create new User."""
        try:
            data_dict = data.model_dump()
            if tenant_id:
                data_dict["tenant_id"] = tenant_id

            # BaseModel.create() returns the created instance directly
            created = await self.repository.create(**data_dict)

            # Publish event
            await event_publisher.publish(
                entity_name="user",
                action="created",
                data=created.to_dict(),
                tenant_id=tenant_id,
            )

            # Track metric
            entity_operations_total.labels(
                entity="user", operation="create", status="success"
            ).inc()

            # Convert BaseModel to dict for response
            return UserResponse(**created.to_dict())

        except Exception as e:
            entity_operations_total.labels(entity="user", operation="create", status="error").inc()
            logger.error("create_user_failed", error=str(e))
            raise

    async def get_user(self, id: UUID) -> Optional[UserResponse]:
        """Get User by ID."""
        orm_obj = await self.repository.get_by_id(id)
        return UserResponse(**orm_obj.to_dict()) if orm_obj else None

    async def list_users(self, skip: int = 0, limit: int = 100) -> List[UserResponse]:
        """List Users with pagination."""
        orm_objs = await self.repository.get_all(skip, limit)
        return [UserResponse(**obj.to_dict()) for obj in orm_objs]

    async def update_user(self, id: UUID, data: UserUpdate) -> Optional[UserResponse]:
        """Update User."""
        try:
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return None

            # Update fields from DTO
            for key, value in data.model_dump(exclude_unset=True).items():
                setattr(orm_obj, key, value)

            # BaseModel.save() returns self
            updated = await self.repository.update(orm_obj)

            # Publish event
            await event_publisher.publish(
                entity_name="user",
                action="updated",
                data=updated.to_dict(),
                tenant_id=getattr(updated, "tenant_id", None),
            )

            # Track metric
            entity_operations_total.labels(
                entity="user", operation="update", status="success"
            ).inc()

            return UserResponse(**updated.to_dict())

        except Exception as e:
            entity_operations_total.labels(entity="user", operation="update", status="error").inc()
            logger.error("update_user_failed", id=str(id), error=str(e))
            raise

    async def delete_user(self, id: UUID) -> bool:
        """Soft-delete User (sets deleted_at)."""
        try:
            orm_obj = await self.repository.get_by_id(id)
            if not orm_obj:
                return False
            entity_data = orm_obj.to_dict()
            deleted = await self.repository.delete(id)
            if deleted:
                await event_publisher.publish(
                    entity_name="user",
                    action="soft_deleted",
                    data=entity_data,
                    tenant_id=entity_data.get("tenant_id"),
                )
                entity_operations_total.labels(
                    entity="user", operation="soft_delete", status="success"
                ).inc()
            return deleted
        except Exception as e:
            entity_operations_total.labels(
                entity="user", operation="soft_delete", status="error"
            ).inc()
            logger.error("soft_delete_user_failed", id=str(id), error=str(e))
            raise

    async def restore_user(self, id: UUID) -> Optional[UserResponse]:
        """Restore soft-deleted User."""
        try:
            restored = await self.repository.restore(id)
            if restored:
                await event_publisher.publish(
                    entity_name="user",
                    action="restored",
                    data=restored.to_dict(),
                    tenant_id=getattr(restored, "tenant_id", None),
                )
                entity_operations_total.labels(
                    entity="user", operation="restore", status="success"
                ).inc()
                return UserResponse(**restored.to_dict())
            return None
        except Exception as e:
            entity_operations_total.labels(entity="user", operation="restore", status="error").inc()
            logger.error("restore_user_failed", id=str(id), error=str(e))
            raise

    async def hard_delete_user(self, id: UUID) -> bool:
        """Permanently delete User. Admin only."""
        try:
            orm_obj = await self.repository.get_by_id_with_deleted(id)
            if not orm_obj:
                return False
            entity_data = orm_obj.to_dict()
            deleted = await self.repository.hard_delete(id)
            if deleted:
                await event_publisher.publish(
                    entity_name="user",
                    action="deleted",
                    data=entity_data,
                    tenant_id=entity_data.get("tenant_id"),
                )
                entity_operations_total.labels(
                    entity="user", operation="hard_delete", status="success"
                ).inc()
            return deleted
        except Exception as e:
            entity_operations_total.labels(
                entity="user", operation="hard_delete", status="error"
            ).inc()
            logger.error("hard_delete_user_failed", id=str(id), error=str(e))
            raise

    async def search_users(
        self, domain: list = None, skip: int = 0, limit: int = 100
    ) -> List[UserResponse]:
        """
        Search Users with domain filtering.

        Args:
            domain: domain filter (e.g., [('field', '=', 'value')])
            skip: Offset for pagination
            limit: Maximum records to return

        Returns:
            List of matching User instances
        """
        orm_objs = await self.repository.search(domain, skip, limit)
        return [UserResponse(**obj.to_dict()) for obj in orm_objs]

    async def count_users(self, domain: list = None) -> int:
        """
        Count Users matching domain.

        Args:
            domain: Optional domain filter

        Returns:
            Number of matching records
        """
        return await self.repository.count(domain)

    async def bulk_create_users(self, records_data: List[UserCreate]) -> List[UserResponse]:
        """
        Create multiple Users efficiently.

        Args:
            records_data: List of create DTOs

        Returns:
            List of created User instances
        """
        # Convert DTOs to dicts
        data_dicts = [record.model_dump() for record in records_data]

        # Bulk create
        created_objs = await self.repository.bulk_create(data_dicts)

        return [UserResponse(**obj.to_dict()) for obj in created_objs]
