/**
 * useUsers Hooks
 *
 * React Query hooks for User CRUD operations with automatic caching
 * and cache invalidation.
 *
 * Hooks provided:
 * - useUsers: List users with optional filters
 * - useUser: Get single user by ID
 * - useUsersDropdown: Get users formatted for dropdown selection
 * - useCreateUser: Create new user
 * - useUpdateUser: Update existing user
 * - useDeleteUser: Delete user
 *
 * Features:
 * - Automatic caching with configurable stale/gc times
 * - Cache invalidation on mutations
 * - Loading and error states
 * - Request deduplication
 * - Retry with exponential backoff
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-02-20T17:11:23.023814Z
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseQueryResult,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMemo } from 'react';
import { userService } from '../services/user.service';
import { userKeys } from './userKeys';
import type {
  User,
  UserCreateRequest,
  UserUpdateRequest,
  UserFilterOptions,
} from '../types/user.types';

/**
 * Cache timing constants (in milliseconds)
 * Configurable via entity definition or defaults
 */
const USER_STALE_TIME = 300000; // 5 minutes
const USER_GC_TIME = 1800000; // 30 minutes

/**
 * Retry configuration
 * - 3 retries with exponential backoff
 * - Delays: 1s, 2s, 4s (2^attemptIndex * 1000)
 */
const RETRY_COUNT = 3;
const retryDelay = (attemptIndex: number) =>
  Math.min(1000 * 2 ** attemptIndex, 30000);

/**
 * Options for the useUsers hook
 */
export interface UseUsersOptions {
  /**
   * Filter to only return active users
   * @default true
   */
  activeOnly?: boolean;

  /**
   * Additional filter options for the query
   */
  filters?: Omit<UserFilterOptions, 'is_active'>;

  /**
   * Whether to enable the query
   * @default true
   */
  enabled?: boolean;
}

/**
 * Return type for the useUsers hook
 */
export interface UseUsersResult
  extends Omit<UseQueryResult<User[], Error>, 'data'> {
  /** Array of user data */
  data: User[] | undefined;

  /** Convenience alias for data */
  users: User[] | undefined;
}

/**
 * Hook to fetch users with React Query caching
 *
 * Provides user data with optimized caching:
 * - staleTime: 5 minutes - Data is fresh for this period
 * - gcTime: 30 minutes - Unused cache entries are collected after this period
 *
 * @param options - Hook options including active filter and additional filters
 * @returns Query result with user data, loading, error states, and refetch function
 *
 * @example
 * ```typescript
 * import { useUsers } from './hooks/useUsers';
 *
 * function UserList() {
 *   const { data, isLoading, error, refetch } = useUsers();
 *
 *   if (isLoading) return <Skeleton />;
 *   if (error) return <Error message={error.message} onRetry={refetch} />;
 *
 *   return (
 *     <List>
 *       {data?.map(item => <ListItem key={item.id}>{item.username}</ListItem>)}
 *     </List>
 *   );
 * }
 *
 * // With filters
 * const { data } = useUsers({ activeOnly: false, filters: { search: 'test' } });
 * ```
 */
export function useUsers(
  options: UseUsersOptions = {}
): UseUsersResult {
  const { activeOnly = true, filters = {}, enabled = true } = options;

  // Build the filter options combining activeOnly with other filters
  const filterOptions: UserFilterOptions = {
    ...filters,
    is_active: activeOnly ? true : undefined,
  };

  const queryResult = useQuery<User[], Error>({
    queryKey: userKeys.list(filterOptions),
    queryFn: async () => {
      const items = await userService.getAll(filterOptions);
      return items;
    },
    staleTime: USER_STALE_TIME,
    gcTime: USER_GC_TIME,
    enabled,
    retry: RETRY_COUNT,
    retryDelay,
  });

  return {
    ...queryResult,
    users: queryResult.data,
  };
}

/**
 * Hook to fetch a single user by ID
 *
 * @param id - User ID (UUID)
 * @param options - Optional React Query options
 * @returns Query result with user data
 *
 * @example
 * ```typescript
 * const { data: user, isLoading } = useUser('uuid-here');
 * ```
 */
export function useUser(
  id: string,
  options?: Omit<UseQueryOptions<User | null, Error>, 'queryKey' | 'queryFn'>
): UseQueryResult<User | null, Error> {
  return useQuery<User | null, Error>({
    queryKey: userKeys.detail(id),
    queryFn: () => userService.getById(id),
    staleTime: USER_STALE_TIME,
    gcTime: USER_GC_TIME,
    enabled: !!id,
    retry: RETRY_COUNT,
    retryDelay,
    ...options,
  });
}

/**
 * Dropdown option type for user select components
 */
export interface UserDropdownOption {
  value: string;
  label: string;
  data: User;
}

/**
 * Hook to fetch users formatted for dropdown selection
 *
 * Returns memoized options with { value, label, data } structure.
 *
 * @param activeOnly - Only include active users (default: true)
 * @returns Query result with dropdown options
 *
 * @example
 * ```typescript
 * const { data: options, isLoading } = useUsersDropdown();
 *
 * <Select options={options} isLoading={isLoading} />
 * ```
 */
export function useUsersDropdown(activeOnly: boolean = true) {
  const queryResult = useQuery<UserDropdownOption[], Error>({
    queryKey: userKeys.dropdown(activeOnly),
    queryFn: () => userService.getForDropdown(!activeOnly),
    staleTime: USER_STALE_TIME,
    gcTime: USER_GC_TIME,
    retry: RETRY_COUNT,
    retryDelay,
  });

  // Memoize the options transformation
  const options = useMemo(() => queryResult.data ?? [], [queryResult.data]);

  return {
    ...queryResult,
    options,
  };
}

/**
 * Hook to create a new user
 *
 * Automatically invalidates user list queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: createUser, isPending } = useCreateUser();
 *
 * createUser({
 *   username: 'New User',
 *   // ... other fields
 * });
 * ```
 */
export function useCreateUser(): UseMutationResult<
  User,
  Error,
  UserCreateRequest,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<User, Error, UserCreateRequest>({
    mutationFn: (data: UserCreateRequest) =>
      userService.create(data),
    onSuccess: () => {
      // Invalidate all user list queries to refetch fresh data
      queryClient.invalidateQueries({ queryKey: userKeys.all });
    },
  });
}

/**
 * Hook to update an existing user
 *
 * Automatically invalidates user list and detail queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: updateUser } = useUpdateUser();
 *
 * updateUser({
 *   id: 'uuid-here',
 *   data: { username: 'Updated Name' }
 * });
 * ```
 */
export function useUpdateUser(): UseMutationResult<
  User,
  Error,
  { id: string; data: UserUpdateRequest },
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<
    User,
    Error,
    { id: string; data: UserUpdateRequest }
  >({
    mutationFn: ({ id, data }) => userService.update(id, data),
    onSuccess: (_, { id }) => {
      // Invalidate all user list queries
      queryClient.invalidateQueries({ queryKey: userKeys.all });
      // Invalidate the specific user detail query
      queryClient.invalidateQueries({ queryKey: userKeys.detail(id) });
    },
  });
}

/**
 * Hook to delete a user
 *
 * Automatically invalidates user queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deleteUser, isPending } = useDeleteUser();
 *
 * deleteUser('uuid-here');
 * ```
 */
export function useDeleteUser(): UseMutationResult<void, Error, string, unknown> {
  const queryClient = useQueryClient();

  return useMutation<void, Error, string>({
    mutationFn: (id: string) => userService.delete(id),
    onSuccess: (_, id) => {
      // Invalidate all user queries
      queryClient.invalidateQueries({ queryKey: userKeys.all });
      // Remove the specific detail query from cache
      queryClient.removeQueries({ queryKey: userKeys.detail(id) });
    },
  });
}

/**
 * Hook to deactivate a user (soft delete)
 *
 * Automatically invalidates user queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deactivateUser } = useDeactivateUser();
 *
 * deactivateUser('uuid-here');
 * ```
 */
export function useDeactivateUser(): UseMutationResult<
  User,
  Error,
  string,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<User, Error, string>({
    mutationFn: (id: string) =>
      userService.update(id, { is_active: false } as UserUpdateRequest),
    onSuccess: (_, id) => {
      // Invalidate all user queries
      queryClient.invalidateQueries({ queryKey: userKeys.all });
      // Invalidate the specific detail query
      queryClient.invalidateQueries({ queryKey: userKeys.detail(id) });
    },
  });
}

// Default export for convenience
export default useUsers;
