"""
ContactPersonRepository - Generated Repository

Generated by Code Generator v1.0.0
"""

from legal_service.infrastructure.orm.contact_person import ContactPerson
from legal_service.infrastructure.repositories.base_repository import BaseRepository


class ContactPersonRepository(BaseRepository[ContactPerson]):
    """Repository for ContactPerson entities."""

    def __init__(self, session=None):
        """Initialize repository with BaseModel ORM class."""
        super().__init__(ContactPerson, session)
