/**
 * InvestorEmail Service
 *
 * Axios-based API client for InvestorEmail entity with authentication,
 * error handling, and optional caching support.
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:10.303790Z
 */

// Vite environment type augmentation
declare global {
  interface ImportMeta {
    env: {
      VITE_API_BASE_URL?: string;
      [key: string]: string | undefined;
    };
  }
}

import axios, { AxiosInstance, AxiosError, InternalAxiosRequestConfig } from 'axios';
import type {
  InvestorEmail,
  InvestorEmailCreateRequest,
  InvestorEmailUpdateRequest,
  InvestorEmailListResponse,
  InvestorEmailFilterOptions,
} from '../types/investor_email.types';

// API Base URL - configurable via environment variable
// Empty string default means requests use relative paths (going through Vite proxy in dev)
const API_BASE_URL =
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE_URL) ||
  '';

// Tenant ID - required by multi-tenant backend
const TENANT_ID =
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_TENANT_ID) ||
  (typeof localStorage !== 'undefined' && localStorage.getItem('tenant_id')) ||
  '00000000-0000-0000-0000-000000000000';

// Default cache TTL in milliseconds (5 minutes)
const DEFAULT_CACHE_TTL_MS = 5 * 60 * 1000;

/**
 * InvestorEmail service error class for typed error handling
 */
export class InvestorEmailServiceError extends Error {
  constructor(
    message: string,
    public statusCode?: number,
    public errorCode?: string
  ) {
    super(message);
    this.name = 'InvestorEmailServiceError';
  }
}

/**
 * Cache entry structure for in-memory caching
 */
interface CacheEntry<T> {
  data: T;
  timestamp: number;
  ttl: number;
}

/**
 * InvestorEmail Service Class
 *
 * Provides CRUD operations for InvestorEmail entities with:
 * - Bearer token authentication
 * - Typed error handling
 * - Optional in-memory caching
 * - Filter support
 */
class InvestorEmailService {
  private client: AxiosInstance;
  private cache: Map<string, CacheEntry<InvestorEmail[]>>;
  private cacheTTL: number;

  constructor(baseURL?: string, cacheTTL: number = DEFAULT_CACHE_TTL_MS) {
    this.client = axios.create({
      baseURL: baseURL || API_BASE_URL,
      headers: {
        'Content-Type': 'application/json',
      },
    });

    this.cache = new Map();
    this.cacheTTL = cacheTTL;

    // Add request interceptor for authentication and tenant context
    this.client.interceptors.request.use(
      (config: InternalAxiosRequestConfig) => {
        const token =
          typeof localStorage !== 'undefined'
            ? localStorage.getItem('access_token')
            : null;

        if (token && config.headers) {
          config.headers.Authorization = `Bearer ${token}`;
        }

        // Always send tenant ID header (required by multi-tenant backend)
        if (config.headers) {
          const tenantId =
            (typeof localStorage !== 'undefined' && localStorage.getItem('tenant_id')) ||
            TENANT_ID;
          config.headers['X-Tenant-ID'] = tenantId;
        }
        return config;
      },
      (error) => Promise.reject(error)
    );

    // Add response interceptor for error handling
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        if (axios.isAxiosError(error) && error.response?.status === 401) {
          console.warn('[InvestorEmailService] Unauthorized — clearing session');
          localStorage.removeItem('access_token');
          localStorage.removeItem('refresh_token');
          localStorage.removeItem('token_expiry');
          if (typeof window !== 'undefined' && !window.location.pathname.startsWith('/login')) {
            window.location.href = '/login';
          }
        }
        return Promise.reject(error);
      }
    );
  }

  /**
   * Check if cache entry is still valid
   */
  private isCacheValid(entry: CacheEntry<InvestorEmail[]> | undefined): boolean {
    if (!entry) return false;
    const now = Date.now();
    return now - entry.timestamp < entry.ttl;
  }

  /**
   * Get cached data if valid
   */
  private getCached(key: string): InvestorEmail[] | null {
    const entry = this.cache.get(key);
    if (this.isCacheValid(entry)) {
      console.debug(`[InvestorEmailService] Cache hit for key: ${key}`);
      return entry!.data;
    }
    return null;
  }

  /**
   * Set cache entry
   */
  private setCache(key: string, data: InvestorEmail[]): void {
    this.cache.set(key, {
      data,
      timestamp: Date.now(),
      ttl: this.cacheTTL,
    });
    console.debug(
      `[InvestorEmailService] Cached ${data.length} items for key: ${key}`
    );
  }

  /**
   * Handle API errors and transform to typed error
   */
  private handleError(error: unknown): InvestorEmailServiceError {
    if (axios.isAxiosError(error)) {
      const axiosError = error as AxiosError<{
        detail?: string;
        message?: string;
        error_code?: string;
      }>;
      const message =
        axiosError.response?.data?.detail ||
        axiosError.response?.data?.message ||
        axiosError.message ||
        'An error occurred';
      const statusCode = axiosError.response?.status;
      const errorCode = axiosError.response?.data?.error_code;
      return new InvestorEmailServiceError(message, statusCode, errorCode);
    }
    return new InvestorEmailServiceError(
      error instanceof Error ? error.message : 'Unknown error'
    );
  }

  /**
   * Fetch all investor_emails with optional filters
   *
   * @param filters - Optional filter options
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of InvestorEmail objects
   * @throws InvestorEmailServiceError on fetch failure
   */
  async getAll(
    filters?: InvestorEmailFilterOptions,
    forceRefresh: boolean = false
  ): Promise<InvestorEmail[]> {
    const cacheKey = `all_investor_emails_${JSON.stringify(filters || {})}`;

    // Check cache first
    if (!forceRefresh) {
      const cached = this.getCached(cacheKey);
      if (cached) {
        return cached;
      }
    }

    const url = '/api/v1/investor-emails/';
    try {
      console.log(`[InvestorEmailService] GET ${url}`, { params: filters });
      const response = await this.client.get<
        InvestorEmail[] | InvestorEmailListResponse
      >(url, {
        params: filters as Record<string, unknown> | undefined,
      });

      // Handle both array response and wrapped response
      const data = response.data;
      const items = Array.isArray(data)
        ? data
        : (data as InvestorEmailListResponse).items ||
          (data as InvestorEmailListResponse).investor_emails ||
          [];

      console.log(`[InvestorEmailService] GET ${url} → ${response.status} OK`, {
        count: items.length,
        firstItem: items[0] ? { id: items[0].id } : null,
      });

      this.setCache(cacheKey, items);
      return items;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[InvestorEmailService] GET ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Get a single investor_email by ID
   *
   * @param id - InvestorEmail ID (UUID)
   * @returns InvestorEmail object
   * @throws InvestorEmailServiceError on fetch failure
   */
  async getById(id: string): Promise<InvestorEmail> {
    const url = `/api/v1/investor-emails/${id}`;
    try {
      console.log(`[InvestorEmailService] GET ${url}`);
      const response = await this.client.get<InvestorEmail>(url);
      console.log(`[InvestorEmailService] GET ${url} → ${response.status} OK`, {
        id: response.data.id,
      });
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[InvestorEmailService] GET ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Create a new investor_email
   *
   * @param data - InvestorEmail creation data
   * @returns Created InvestorEmail object
   * @throws InvestorEmailServiceError on creation failure
   */
  async create(data: InvestorEmailCreateRequest): Promise<InvestorEmail> {
    const url = '/api/v1/investor-emails/';
    try {
      console.log(`[InvestorEmailService] POST ${url}`, { data });
      const response = await this.client.post<InvestorEmail>(url, data);
      console.log(`[InvestorEmailService] POST ${url} → ${response.status} Created`, {
        id: response.data.id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[InvestorEmailService] POST ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Update an existing investor_email
   *
   * @param id - InvestorEmail ID (UUID)
   * @param data - Partial InvestorEmail update data
   * @returns Updated InvestorEmail object
   * @throws InvestorEmailServiceError on update failure
   */
  async update(
    id: string,
    data: InvestorEmailUpdateRequest
  ): Promise<InvestorEmail> {
    const url = `/api/v1/investor-emails/${id}`;
    try {
      console.log(`[InvestorEmailService] PUT ${url}`, { data });
      const response = await this.client.put<InvestorEmail>(url, data);
      console.log(`[InvestorEmailService] PUT ${url} → ${response.status} OK`, {
        id: response.data.id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[InvestorEmailService] PUT ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Delete a investor_email
   *
   * @param id - InvestorEmail ID (UUID)
   * @throws InvestorEmailServiceError on deletion failure
   */
  async delete(id: string): Promise<void> {
    const url = `/api/v1/investor-emails/${id}`;
    try {
      console.log(`[InvestorEmailService] DELETE ${url}`);
      const response = await this.client.delete(url);
      console.log(`[InvestorEmailService] DELETE ${url} → ${response.status} OK`, {
        deletedId: id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[InvestorEmailService] DELETE ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Get active investor_emails only
   *
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of active InvestorEmail objects
   */
  async getActive(forceRefresh: boolean = false): Promise<InvestorEmail[]> {
    const all = await this.getAll(undefined, forceRefresh);
    return all.filter((item) => (item as any).is_active !== false);
  }

  /**
   * Search investor_emails by query string
   *
   * @param query - Search query string
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of matching InvestorEmail objects
   */
  async search(
    query: string,
    forceRefresh: boolean = false
  ): Promise<InvestorEmail[]> {
    return this.getAll({ search: query } as InvestorEmailFilterOptions, forceRefresh);
  }

  /**
   * Clear all cached data
   */
  clearCache(): void {
    this.cache.clear();
    console.debug('[InvestorEmailService] Cache cleared');
  }

  /**
   * Get cache statistics for debugging
   */
  getCacheStats(): { entries: number; keys: string[] } {
    return {
      entries: this.cache.size,
      keys: Array.from(this.cache.keys()),
    };
  }

  /**
   * Set cache TTL (time-to-live)
   *
   * @param ttlMs - TTL in milliseconds
   */
  setCacheTTL(ttlMs: number): void {
    this.cacheTTL = ttlMs;
  }

  /**
   * Format investor_email for dropdown display
   *
   * @param item - InvestorEmail object
   * @returns Formatted string for display
   */
  formatForDropdown(item: InvestorEmail): string {
    // Use code-name pattern if available, otherwise just name or id
    const code = (item as any).code;
    const name = (item as any).name;

    if (code && name) {
      return `${code} - ${name}`;
    }
    if (name) {
      return name;
    }
    return item.id;
  }

  /**
   * Get investor_emails formatted for dropdown selection
   *
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of { value, label, data } objects for dropdown
   */
  async getForDropdown(
    forceRefresh: boolean = false
  ): Promise<Array<{ value: string; label: string; data: InvestorEmail }>> {
    const items = await this.getActive(forceRefresh);
    return items.map((item) => ({
      value: item.id,
      label: this.formatForDropdown(item),
      data: item,
    }));
  }
}

// Export singleton instance for convenience
export const investor_emailService = new InvestorEmailService();

// Export the class for testing and custom instantiation
export { InvestorEmailService };

// Default export for convenience
export default investor_emailService;
