/**
 * UsageRecord Service
 *
 * Axios-based API client for UsageRecord entity with authentication,
 * error handling, and optional caching support.
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:44.291688Z
 */

// Vite environment type augmentation
declare global {
  interface ImportMeta {
    env: {
      VITE_API_BASE_URL?: string;
      [key: string]: string | undefined;
    };
  }
}

import axios, { AxiosInstance, AxiosError, InternalAxiosRequestConfig } from 'axios';
import type {
  UsageRecord,
  UsageRecordCreateRequest,
  UsageRecordUpdateRequest,
  UsageRecordListResponse,
  UsageRecordFilterOptions,
} from '../types/usage_record.types';

// API Base URL - configurable via environment variable
// Empty string default means requests use relative paths (going through Vite proxy in dev)
const API_BASE_URL =
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE_URL) ||
  '';

// Tenant ID - required by multi-tenant backend
const TENANT_ID =
  (typeof import.meta !== 'undefined' && import.meta.env?.VITE_TENANT_ID) ||
  (typeof localStorage !== 'undefined' && localStorage.getItem('tenant_id')) ||
  '00000000-0000-0000-0000-000000000000';

// Default cache TTL in milliseconds (5 minutes)
const DEFAULT_CACHE_TTL_MS = 5 * 60 * 1000;

/**
 * UsageRecord service error class for typed error handling
 */
export class UsageRecordServiceError extends Error {
  constructor(
    message: string,
    public statusCode?: number,
    public errorCode?: string
  ) {
    super(message);
    this.name = 'UsageRecordServiceError';
  }
}

/**
 * Cache entry structure for in-memory caching
 */
interface CacheEntry<T> {
  data: T;
  timestamp: number;
  ttl: number;
}

/**
 * UsageRecord Service Class
 *
 * Provides CRUD operations for UsageRecord entities with:
 * - Bearer token authentication
 * - Typed error handling
 * - Optional in-memory caching
 * - Filter support
 */
class UsageRecordService {
  private client: AxiosInstance;
  private cache: Map<string, CacheEntry<UsageRecord[]>>;
  private cacheTTL: number;

  constructor(baseURL?: string, cacheTTL: number = DEFAULT_CACHE_TTL_MS) {
    this.client = axios.create({
      baseURL: baseURL || API_BASE_URL,
      headers: {
        'Content-Type': 'application/json',
      },
    });

    this.cache = new Map();
    this.cacheTTL = cacheTTL;

    // Add request interceptor for authentication and tenant context
    this.client.interceptors.request.use(
      (config: InternalAxiosRequestConfig) => {
        const token =
          typeof localStorage !== 'undefined'
            ? localStorage.getItem('access_token')
            : null;

        if (token && config.headers) {
          config.headers.Authorization = `Bearer ${token}`;
        }

        // Always send tenant ID header (required by multi-tenant backend)
        if (config.headers) {
          const tenantId =
            (typeof localStorage !== 'undefined' && localStorage.getItem('tenant_id')) ||
            TENANT_ID;
          config.headers['X-Tenant-ID'] = tenantId;
        }
        return config;
      },
      (error) => Promise.reject(error)
    );

    // Add response interceptor for error handling
    this.client.interceptors.response.use(
      (response) => response,
      (error) => {
        if (axios.isAxiosError(error) && error.response?.status === 401) {
          console.warn('[UsageRecordService] Unauthorized — clearing session');
          localStorage.removeItem('access_token');
          localStorage.removeItem('refresh_token');
          localStorage.removeItem('token_expiry');
          if (typeof window !== 'undefined' && !window.location.pathname.startsWith('/login')) {
            window.location.href = '/login';
          }
        }
        return Promise.reject(error);
      }
    );
  }

  /**
   * Check if cache entry is still valid
   */
  private isCacheValid(entry: CacheEntry<UsageRecord[]> | undefined): boolean {
    if (!entry) return false;
    const now = Date.now();
    return now - entry.timestamp < entry.ttl;
  }

  /**
   * Get cached data if valid
   */
  private getCached(key: string): UsageRecord[] | null {
    const entry = this.cache.get(key);
    if (this.isCacheValid(entry)) {
      console.debug(`[UsageRecordService] Cache hit for key: ${key}`);
      return entry!.data;
    }
    return null;
  }

  /**
   * Set cache entry
   */
  private setCache(key: string, data: UsageRecord[]): void {
    this.cache.set(key, {
      data,
      timestamp: Date.now(),
      ttl: this.cacheTTL,
    });
    console.debug(
      `[UsageRecordService] Cached ${data.length} items for key: ${key}`
    );
  }

  /**
   * Handle API errors and transform to typed error
   */
  private handleError(error: unknown): UsageRecordServiceError {
    if (axios.isAxiosError(error)) {
      const axiosError = error as AxiosError<{
        detail?: string;
        message?: string;
        error_code?: string;
      }>;
      const message =
        axiosError.response?.data?.detail ||
        axiosError.response?.data?.message ||
        axiosError.message ||
        'An error occurred';
      const statusCode = axiosError.response?.status;
      const errorCode = axiosError.response?.data?.error_code;
      return new UsageRecordServiceError(message, statusCode, errorCode);
    }
    return new UsageRecordServiceError(
      error instanceof Error ? error.message : 'Unknown error'
    );
  }

  /**
   * Fetch all usage_records with optional filters
   *
   * @param filters - Optional filter options
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of UsageRecord objects
   * @throws UsageRecordServiceError on fetch failure
   */
  async getAll(
    filters?: UsageRecordFilterOptions,
    forceRefresh: boolean = false
  ): Promise<UsageRecord[]> {
    const cacheKey = `all_usage_records_${JSON.stringify(filters || {})}`;

    // Check cache first
    if (!forceRefresh) {
      const cached = this.getCached(cacheKey);
      if (cached) {
        return cached;
      }
    }

    const url = '/api/v1/usage-records/';
    try {
      console.log(`[UsageRecordService] GET ${url}`, { params: filters });
      const response = await this.client.get<
        UsageRecord[] | UsageRecordListResponse
      >(url, {
        params: filters as Record<string, unknown> | undefined,
      });

      // Handle both array response and wrapped response
      const data = response.data;
      const items = Array.isArray(data)
        ? data
        : (data as UsageRecordListResponse).items ||
          (data as UsageRecordListResponse).usage_records ||
          [];

      console.log(`[UsageRecordService] GET ${url} → ${response.status} OK`, {
        count: items.length,
        firstItem: items[0] ? { id: items[0].id } : null,
      });

      this.setCache(cacheKey, items);
      return items;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[UsageRecordService] GET ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Get a single usage_record by ID
   *
   * @param id - UsageRecord ID (UUID)
   * @returns UsageRecord object
   * @throws UsageRecordServiceError on fetch failure
   */
  async getById(id: string): Promise<UsageRecord> {
    const url = `/api/v1/usage-records/${id}`;
    try {
      console.log(`[UsageRecordService] GET ${url}`);
      const response = await this.client.get<UsageRecord>(url);
      console.log(`[UsageRecordService] GET ${url} → ${response.status} OK`, {
        id: response.data.id,
      });
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[UsageRecordService] GET ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Create a new usage_record
   *
   * @param data - UsageRecord creation data
   * @returns Created UsageRecord object
   * @throws UsageRecordServiceError on creation failure
   */
  async create(data: UsageRecordCreateRequest): Promise<UsageRecord> {
    const url = '/api/v1/usage-records/';
    try {
      console.log(`[UsageRecordService] POST ${url}`, { data });
      const response = await this.client.post<UsageRecord>(url, data);
      console.log(`[UsageRecordService] POST ${url} → ${response.status} Created`, {
        id: response.data.id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[UsageRecordService] POST ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Update an existing usage_record
   *
   * @param id - UsageRecord ID (UUID)
   * @param data - Partial UsageRecord update data
   * @returns Updated UsageRecord object
   * @throws UsageRecordServiceError on update failure
   */
  async update(
    id: string,
    data: UsageRecordUpdateRequest
  ): Promise<UsageRecord> {
    const url = `/api/v1/usage-records/${id}`;
    try {
      console.log(`[UsageRecordService] PUT ${url}`, { data });
      const response = await this.client.put<UsageRecord>(url, data);
      console.log(`[UsageRecordService] PUT ${url} → ${response.status} OK`, {
        id: response.data.id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
      return response.data;
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[UsageRecordService] PUT ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Delete a usage_record
   *
   * @param id - UsageRecord ID (UUID)
   * @throws UsageRecordServiceError on deletion failure
   */
  async delete(id: string): Promise<void> {
    const url = `/api/v1/usage-records/${id}`;
    try {
      console.log(`[UsageRecordService] DELETE ${url}`);
      const response = await this.client.delete(url);
      console.log(`[UsageRecordService] DELETE ${url} → ${response.status} OK`, {
        deletedId: id,
      });
      // Invalidate cache on successful mutation
      this.clearCache();
    } catch (error) {
      const serviceError = this.handleError(error);
      console.error(`[UsageRecordService] DELETE ${url} → FAILED`, {
        status: serviceError.statusCode,
        message: serviceError.message,
        errorCode: serviceError.errorCode,
      });
      throw serviceError;
    }
  }

  /**
   * Get active usage_records only
   *
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of active UsageRecord objects
   */
  async getActive(forceRefresh: boolean = false): Promise<UsageRecord[]> {
    const all = await this.getAll(undefined, forceRefresh);
    return all.filter((item) => (item as any).is_active !== false);
  }

  /**
   * Search usage_records by query string
   *
   * @param query - Search query string
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of matching UsageRecord objects
   */
  async search(
    query: string,
    forceRefresh: boolean = false
  ): Promise<UsageRecord[]> {
    return this.getAll({ search: query } as UsageRecordFilterOptions, forceRefresh);
  }

  /**
   * Clear all cached data
   */
  clearCache(): void {
    this.cache.clear();
    console.debug('[UsageRecordService] Cache cleared');
  }

  /**
   * Get cache statistics for debugging
   */
  getCacheStats(): { entries: number; keys: string[] } {
    return {
      entries: this.cache.size,
      keys: Array.from(this.cache.keys()),
    };
  }

  /**
   * Set cache TTL (time-to-live)
   *
   * @param ttlMs - TTL in milliseconds
   */
  setCacheTTL(ttlMs: number): void {
    this.cacheTTL = ttlMs;
  }

  /**
   * Format usage_record for dropdown display
   *
   * @param item - UsageRecord object
   * @returns Formatted string for display
   */
  formatForDropdown(item: UsageRecord): string {
    // Use code-name pattern if available, otherwise just name or id
    const code = (item as any).code;
    const name = (item as any).name;

    if (code && name) {
      return `${code} - ${name}`;
    }
    if (name) {
      return name;
    }
    return item.id;
  }

  /**
   * Get usage_records formatted for dropdown selection
   *
   * @param forceRefresh - Skip cache and fetch fresh data
   * @returns Array of { value, label, data } objects for dropdown
   */
  async getForDropdown(
    forceRefresh: boolean = false
  ): Promise<Array<{ value: string; label: string; data: UsageRecord }>> {
    const items = await this.getActive(forceRefresh);
    return items.map((item) => ({
      value: item.id,
      label: this.formatForDropdown(item),
      data: item,
    }));
  }
}

// Export singleton instance for convenience
export const usage_recordService = new UsageRecordService();

// Export the class for testing and custom instantiation
export { UsageRecordService };

// Default export for convenience
export default usage_recordService;
