/**
 * useShortlists Hooks
 *
 * React Query hooks for Shortlist CRUD operations with automatic caching
 * and cache invalidation.
 *
 * Hooks provided:
 * - useShortlists: List shortlists with optional filters
 * - useShortlist: Get single shortlist by ID
 * - useShortlistsDropdown: Get shortlists formatted for dropdown selection
 * - useCreateShortlist: Create new shortlist
 * - useUpdateShortlist: Update existing shortlist
 * - useDeleteShortlist: Delete shortlist
 *
 * Features:
 * - Automatic caching with configurable stale/gc times
 * - Cache invalidation on mutations
 * - Loading and error states
 * - Request deduplication
 * - Retry with exponential backoff
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:24.730202Z
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseQueryResult,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMemo } from 'react';
import { shortlistService } from '../services/shortlist.service';
import { shortlistKeys } from './shortlistKeys';
import type {
  Shortlist,
  ShortlistCreateRequest,
  ShortlistUpdateRequest,
  ShortlistFilterOptions,
} from '../types/shortlist.types';

/**
 * Cache timing constants (in milliseconds)
 * Configurable via entity definition or defaults
 */
const SHORTLIST_STALE_TIME = 300000; // 5 minutes
const SHORTLIST_GC_TIME = 1800000; // 30 minutes

/**
 * Retry configuration
 * - 3 retries with exponential backoff
 * - Delays: 1s, 2s, 4s (2^attemptIndex * 1000)
 */
const RETRY_COUNT = 3;
const retryDelay = (attemptIndex: number) =>
  Math.min(1000 * 2 ** attemptIndex, 30000);

/**
 * Options for the useShortlists hook
 */
export interface UseShortlistsOptions {
  /**
   * Filter to only return active shortlists
   * @default true
   */
  activeOnly?: boolean;

  /**
   * Additional filter options for the query
   */
  filters?: Omit<ShortlistFilterOptions, 'is_active'>;

  /**
   * Whether to enable the query
   * @default true
   */
  enabled?: boolean;
}

/**
 * Return type for the useShortlists hook
 */
export interface UseShortlistsResult
  extends Omit<UseQueryResult<Shortlist[], Error>, 'data'> {
  /** Array of shortlist data */
  data: Shortlist[] | undefined;

  /** Convenience alias for data */
  shortlists: Shortlist[] | undefined;
}

/**
 * Hook to fetch shortlists with React Query caching
 *
 * Provides shortlist data with optimized caching:
 * - staleTime: 5 minutes - Data is fresh for this period
 * - gcTime: 30 minutes - Unused cache entries are collected after this period
 *
 * @param options - Hook options including active filter and additional filters
 * @returns Query result with shortlist data, loading, error states, and refetch function
 *
 * @example
 * ```typescript
 * import { useShortlists } from './hooks/useShortlists';
 *
 * function ShortlistList() {
 *   const { data, isLoading, error, refetch } = useShortlists();
 *
 *   if (isLoading) return <Skeleton />;
 *   if (error) return <Error message={error.message} onRetry={refetch} />;
 *
 *   return (
 *     <List>
 *       {data?.map(item => <ListItem key={item.id}>{item.user_id}</ListItem>)}
 *     </List>
 *   );
 * }
 *
 * // With filters
 * const { data } = useShortlists({ activeOnly: false, filters: { search: 'test' } });
 * ```
 */
export function useShortlists(
  options: UseShortlistsOptions = {}
): UseShortlistsResult {
  const { activeOnly = true, filters = {}, enabled = true } = options;

  // Build the filter options combining activeOnly with other filters
  const filterOptions: ShortlistFilterOptions = {
    ...filters,
    is_active: activeOnly ? true : undefined,
  };

  const queryResult = useQuery<Shortlist[], Error>({
    queryKey: shortlistKeys.list(filterOptions),
    queryFn: async () => {
      const items = await shortlistService.getAll(filterOptions);
      return items;
    },
    staleTime: SHORTLIST_STALE_TIME,
    gcTime: SHORTLIST_GC_TIME,
    enabled,
    retry: RETRY_COUNT,
    retryDelay,
  });

  return {
    ...queryResult,
    shortlists: queryResult.data,
  };
}

/**
 * Hook to fetch a single shortlist by ID
 *
 * @param id - Shortlist ID (UUID)
 * @param options - Optional React Query options
 * @returns Query result with shortlist data
 *
 * @example
 * ```typescript
 * const { data: shortlist, isLoading } = useShortlist('uuid-here');
 * ```
 */
export function useShortlist(
  id: string,
  options?: Omit<UseQueryOptions<Shortlist | null, Error>, 'queryKey' | 'queryFn'>
): UseQueryResult<Shortlist | null, Error> {
  return useQuery<Shortlist | null, Error>({
    queryKey: shortlistKeys.detail(id),
    queryFn: () => shortlistService.getById(id),
    staleTime: SHORTLIST_STALE_TIME,
    gcTime: SHORTLIST_GC_TIME,
    enabled: !!id,
    retry: RETRY_COUNT,
    retryDelay,
    ...options,
  });
}

/**
 * Dropdown option type for shortlist select components
 */
export interface ShortlistDropdownOption {
  value: string;
  label: string;
  data: Shortlist;
}

/**
 * Hook to fetch shortlists formatted for dropdown selection
 *
 * Returns memoized options with { value, label, data } structure.
 *
 * @param activeOnly - Only include active shortlists (default: true)
 * @returns Query result with dropdown options
 *
 * @example
 * ```typescript
 * const { data: options, isLoading } = useShortlistsDropdown();
 *
 * <Select options={options} isLoading={isLoading} />
 * ```
 */
export function useShortlistsDropdown(activeOnly: boolean = true) {
  const queryResult = useQuery<ShortlistDropdownOption[], Error>({
    queryKey: shortlistKeys.dropdown(activeOnly),
    queryFn: () => shortlistService.getForDropdown(!activeOnly),
    staleTime: SHORTLIST_STALE_TIME,
    gcTime: SHORTLIST_GC_TIME,
    retry: RETRY_COUNT,
    retryDelay,
  });

  // Memoize the options transformation
  const options = useMemo(() => queryResult.data ?? [], [queryResult.data]);

  return {
    ...queryResult,
    options,
  };
}

/**
 * Hook to create a new shortlist
 *
 * Automatically invalidates shortlist list queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: createShortlist, isPending } = useCreateShortlist();
 *
 * createShortlist({
 *   user_id: 'New Shortlist',
 *   // ... other fields
 * });
 * ```
 */
export function useCreateShortlist(): UseMutationResult<
  Shortlist,
  Error,
  ShortlistCreateRequest,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<Shortlist, Error, ShortlistCreateRequest>({
    mutationFn: (data: ShortlistCreateRequest) =>
      shortlistService.create(data),
    onSuccess: () => {
      // Invalidate all shortlist list queries to refetch fresh data
      queryClient.invalidateQueries({ queryKey: shortlistKeys.all });
    },
  });
}

/**
 * Hook to update an existing shortlist
 *
 * Automatically invalidates shortlist list and detail queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: updateShortlist } = useUpdateShortlist();
 *
 * updateShortlist({
 *   id: 'uuid-here',
 *   data: { user_id: 'Updated Name' }
 * });
 * ```
 */
export function useUpdateShortlist(): UseMutationResult<
  Shortlist,
  Error,
  { id: string; data: ShortlistUpdateRequest },
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<
    Shortlist,
    Error,
    { id: string; data: ShortlistUpdateRequest }
  >({
    mutationFn: ({ id, data }) => shortlistService.update(id, data),
    onSuccess: (_, { id }) => {
      // Invalidate all shortlist list queries
      queryClient.invalidateQueries({ queryKey: shortlistKeys.all });
      // Invalidate the specific shortlist detail query
      queryClient.invalidateQueries({ queryKey: shortlistKeys.detail(id) });
    },
  });
}

/**
 * Hook to delete a shortlist
 *
 * Automatically invalidates shortlist queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deleteShortlist, isPending } = useDeleteShortlist();
 *
 * deleteShortlist('uuid-here');
 * ```
 */
export function useDeleteShortlist(): UseMutationResult<void, Error, string, unknown> {
  const queryClient = useQueryClient();

  return useMutation<void, Error, string>({
    mutationFn: (id: string) => shortlistService.delete(id),
    onSuccess: (_, id) => {
      // Invalidate all shortlist queries
      queryClient.invalidateQueries({ queryKey: shortlistKeys.all });
      // Remove the specific detail query from cache
      queryClient.removeQueries({ queryKey: shortlistKeys.detail(id) });
    },
  });
}

/**
 * Hook to deactivate a shortlist (soft delete)
 *
 * Automatically invalidates shortlist queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deactivateShortlist } = useDeactivateShortlist();
 *
 * deactivateShortlist('uuid-here');
 * ```
 */
export function useDeactivateShortlist(): UseMutationResult<
  Shortlist,
  Error,
  string,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<Shortlist, Error, string>({
    mutationFn: (id: string) =>
      shortlistService.update(id, { is_active: false } as ShortlistUpdateRequest),
    onSuccess: (_, id) => {
      // Invalidate all shortlist queries
      queryClient.invalidateQueries({ queryKey: shortlistKeys.all });
      // Invalidate the specific detail query
      queryClient.invalidateQueries({ queryKey: shortlistKeys.detail(id) });
    },
  });
}

// Default export for convenience
export default useShortlists;
