/**
 * EquityGrant Test Fixtures
 *
 * Test data fixtures for EquityGrant E2E and unit tests.
 * Provides predefined test data and factory functions for generating
 * test equity_grants.
 *
 * Fixture patterns:
 * - minimal: Only required fields with minimal valid values
 * - complete: All fields with realistic test values
 * - invalid: Invalid data for validation testing
 * - unique: Unique values using timestamps for test isolation
 *
 * Cap table entry — equity holding in a legal entity with share class and valuation
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:52.564348Z
 */

import type { EquityGrantCreateRequest } from '../../types/equity_grant.types';

// ============================================================================
// Types
// ============================================================================

/**
 * Test data pattern types
 *
 * @description
 * - minimal: Only required fields with minimal valid values
 * - complete: All fields populated with realistic test data
 * - invalid: Data that should fail validation
 * - unique: Data with timestamps for test isolation
 */
export type TestDataPattern = 'minimal' | 'complete' | 'invalid' | 'unique';

/**
 * EquityGrant test fixture containing all test data patterns
 */
export interface EquityGrantTestFixtures {
  /** Minimal valid equity_grant with only required fields */
  minimal: EquityGrantCreateRequest;
  /** Complete equity_grant with all fields populated */
  complete: EquityGrantCreateRequest;
  /** Invalid equity_grant for testing validation errors */
  invalid: Partial<EquityGrantCreateRequest>;
  /** Unique equity_grant with timestamp-based values */
  unique: EquityGrantCreateRequest;
  /** Multiple equity_grants for list testing */
  list: EquityGrantCreateRequest[];
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generate a unique identifier based on current timestamp
 * Useful for creating unique test data that won't conflict
 *
 * @param prefix - Optional prefix for the identifier
 * @returns Unique string identifier
 */
function generateUniqueId(prefix = ''): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  return prefix ? `${prefix}-${timestamp}-${random}` : `${timestamp}-${random}`;
}

/**
 * Generate a random string of specified length
 *
 * @param length - Length of the string to generate
 * @param charset - Character set to use (default: alphanumeric)
 * @returns Random string
 */
function randomString(
  length: number,
  charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
): string {
  let result = '';
  for (let i = 0; i < length; i++) {
    result += charset.charAt(Math.floor(Math.random() * charset.length));
  }
  return result;
}

/**
 * Generate a random integer between min and max (inclusive)
 *
 * @param min - Minimum value
 * @param max - Maximum value
 * @returns Random integer
 */
function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Generate a random decimal with specified precision
 *
 * @param min - Minimum value
 * @param max - Maximum value
 * @param precision - Number of decimal places
 * @returns Random decimal number
 */
function randomDecimal(min: number, max: number, precision = 2): number {
  const value = Math.random() * (max - min) + min;
  const factor = Math.pow(10, precision);
  return Math.round(value * factor) / factor;
}

/**
 * Generate a random date within a range
 *
 * @param startDate - Start of the range
 * @param endDate - End of the range
 * @returns Random date as ISO string
 */
function randomDate(startDate: Date, endDate: Date): string {
  const start = startDate.getTime();
  const end = endDate.getTime();
  const randomTime = start + Math.random() * (end - start);
  return new Date(randomTime).toISOString().split('T')[0];
}

/**
 * Pick a random element from an array
 *
 * @param array - Array to pick from
 * @returns Random element
 */
function randomPick<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

// ============================================================================
// Static Test Data
// ============================================================================


/**
 * Sample equity_grant names for generating realistic test data
 */
const SAMPLE_NAMES = [
  'Test EquityGrant Alpha',
  'Test EquityGrant Beta',
  'Test EquityGrant Gamma',
  'Sample EquityGrant One',
  'Sample EquityGrant Two',
  'Demo EquityGrant',
  'Example EquityGrant',
];

/**
 * Sample codes for generating realistic test data
 */
const SAMPLE_CODES = [
  'TST001',
  'TST002',
  'TST003',
  'DEMO01',
  'DEMO02',
  'SMPL01',
  'SMPL02',
];

/**
 * Sample descriptions for generating realistic test data
 */
const SAMPLE_DESCRIPTIONS = [
  'This is a test equity_grant for automated testing.',
  'Sample equity_grant created for E2E tests.',
  'Demo equity_grant with all fields populated.',
  'Example equity_grant for validation testing.',
  'Test data fixture for equity_grant operations.',
];

// ============================================================================
// Predefined Fixtures
// ============================================================================

/**
 * Minimal valid equity_grant fixture
 *
 * Contains only required fields with minimal valid values.
 * Use this when testing that minimal data is accepted.
 */
export const minimalEquityGrantFixture: EquityGrantCreateRequest = {
};

/**
 * Complete equity_grant fixture
 *
 * Contains all fields with realistic test values.
 * Use this when testing full CRUD operations.
 */
export const completeEquityGrantFixture: EquityGrantCreateRequest = {
  legal_entity_id: 'Test Legal Entity Id',
  holder_person_id: 'Test Holder Person Id',
  holder_entity_id: 'Test Holder Entity Id',
  holder_type: 'Test Holder Type',
  share_class: 'Test Share Class',
  number_of_shares: 42,
  percentage: 50.0,
  valuation: 42,
  issue_date: 'Test Issue Date',
  source_document_id: 'Test Source Document Id',
};

/**
 * Unique equity_grant fixture
 *
 * Contains all fields with timestamp-based unique values.
 * Use this when testing to ensure data isolation between test runs.
 * Each field that needs uniqueness includes a timestamp/random component.
 */
export const uniqueEquityGrantFixture: EquityGrantCreateRequest = {
  legal_entity_id: `Legal Entity Id ${generateUniqueId()}`,
  holder_person_id: `Holder Person Id ${generateUniqueId()}`,
  holder_entity_id: `Holder Entity Id ${generateUniqueId()}`,
  holder_type: `Holder Type ${generateUniqueId()}`,
  share_class: `Share Class ${generateUniqueId()}`,
  number_of_shares: Math.floor(Math.random() * 1000),
  percentage: parseFloat((Math.random() * 100).toFixed(2)),
  valuation: Math.floor(Math.random() * 1000),
  issue_date: `Issue Date ${generateUniqueId()}`,
  source_document_id: `Source Document Id ${generateUniqueId()}`,
};

/**
 * Invalid equity_grant fixture
 *
 * Contains invalid data that should fail validation.
 * Use this when testing validation error handling.
 * Covers: empty required fields, values out of range, invalid formats.
 */
export const invalidEquityGrantFixture: Partial<EquityGrantCreateRequest> = {
};

/**
 * Invalid data patterns for comprehensive validation testing
 *
 * Contains various invalid data scenarios:
 * - emptyRequired: All required fields left empty
 * - tooShort: String fields below minimum length
 * - tooLong: String fields exceeding maximum length
 * - outOfRangeMin: Numeric fields below minimum value
 * - outOfRangeMax: Numeric fields above maximum value
 * - wrongType: Fields with incorrect data types (as strings for type coercion testing)
 * - specialChars: Fields with potentially problematic characters
 */
export const equityGrantInvalidPatterns = {
  /** All required string fields empty */
  emptyRequired: {
  } as Partial<EquityGrantCreateRequest>,


  /** String fields exceeding maximum length */
  tooLong: {
    holder_type: 'x'.repeat(60), // max: 10
    share_class: 'x'.repeat(80), // max: 30
  } as Partial<EquityGrantCreateRequest>,



  /** Fields with SQL injection attempts (for security testing) */
  sqlInjection: {
  } as Partial<EquityGrantCreateRequest>,

  /** Fields with XSS attempts (for security testing) */
  xssAttempts: {
  } as Partial<EquityGrantCreateRequest>,

  /** Fields with null values (for nullable field testing) */
  nullValues: {
    holder_person_id: null,
    holder_entity_id: null,
    valuation: null,
    source_document_id: null,
  } as Partial<EquityGrantCreateRequest>,

  /** Fields with undefined values (for missing field testing) */
  undefinedValues: {
    // Intentionally empty - represents missing fields
  } as Partial<EquityGrantCreateRequest>,
};

/**
 * Collection of equity_grant fixtures for list testing
 *
 * Contains multiple equity_grants for testing list operations,
 * pagination, filtering, and sorting.
 */
export const equityGrantListFixtures: EquityGrantCreateRequest[] = [
  {
    legal_entity_id: 'Legal Entity Id 1',
    holder_person_id: 'Holder Person Id 1',
    holder_entity_id: 'Holder Entity Id 1',
    holder_type: 'Holder Type 1',
    share_class: 'Share Class 1',
    number_of_shares: 10,
    percentage: 10,
    valuation: 10,
    issue_date: 'Issue Date 1',
    source_document_id: 'Source Document Id 1',
  },
  {
    legal_entity_id: 'Legal Entity Id 2',
    holder_person_id: 'Holder Person Id 2',
    holder_entity_id: 'Holder Entity Id 2',
    holder_type: 'Holder Type 2',
    share_class: 'Share Class 2',
    number_of_shares: 20,
    percentage: 20,
    valuation: 20,
    issue_date: 'Issue Date 2',
    source_document_id: 'Source Document Id 2',
  },
  {
    legal_entity_id: 'Legal Entity Id 3',
    holder_person_id: 'Holder Person Id 3',
    holder_entity_id: 'Holder Entity Id 3',
    holder_type: 'Holder Type 3',
    share_class: 'Share Class 3',
    number_of_shares: 30,
    percentage: 30,
    valuation: 30,
    issue_date: 'Issue Date 3',
    source_document_id: 'Source Document Id 3',
  },
  {
    legal_entity_id: 'Legal Entity Id 4',
    holder_person_id: 'Holder Person Id 4',
    holder_entity_id: 'Holder Entity Id 4',
    holder_type: 'Holder Type 4',
    share_class: 'Share Class 4',
    number_of_shares: 40,
    percentage: 40,
    valuation: 40,
    issue_date: 'Issue Date 4',
    source_document_id: 'Source Document Id 4',
  },
  {
    legal_entity_id: 'Legal Entity Id 5',
    holder_person_id: 'Holder Person Id 5',
    holder_entity_id: 'Holder Entity Id 5',
    holder_type: 'Holder Type 5',
    share_class: 'Share Class 5',
    number_of_shares: 50,
    percentage: 50,
    valuation: 50,
    issue_date: 'Issue Date 5',
    source_document_id: 'Source Document Id 5',
  },
];

// ============================================================================
// Fixture Collection
// ============================================================================

/**
 * All equity_grant test fixtures
 *
 * @example
 * ```typescript
 * import { equityGrantFixtures } from '../fixtures/equity_grantFixtures';
 *
 * // Use minimal fixture
 * const minData = equityGrantFixtures.minimal;
 *
 * // Use complete fixture
 * const fullData = equityGrantFixtures.complete;
 *
 * // Use unique fixture (with timestamp)
 * const uniqueData = generateEquityGrantTestData('unique');
 * ```
 */
export const equityGrantFixtures: EquityGrantTestFixtures = {
  minimal: minimalEquityGrantFixture,
  complete: completeEquityGrantFixture,
  invalid: invalidEquityGrantFixture as EquityGrantCreateRequest,
  unique: uniqueEquityGrantFixture,
  list: equityGrantListFixtures,
};

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Generate equity_grant test data based on pattern
 *
 * @param pattern - The test data pattern to generate
 * @param overrides - Optional field overrides
 * @returns Generated test data
 *
 * @example
 * ```typescript
 * // Generate complete test data
 * const data = generateEquityGrantTestData('complete');
 *
 * // Generate unique test data with overrides
 * const customData = generateEquityGrantTestData('unique', {
 *   is_active: false,
 * });
 * ```
 */
export function generateEquityGrantTestData(
  pattern: TestDataPattern = 'complete',
  overrides: Partial<EquityGrantCreateRequest> = {}
): EquityGrantCreateRequest {
  let baseData: EquityGrantCreateRequest;

  switch (pattern) {
    case 'minimal':
      baseData = { ...minimalEquityGrantFixture };
      break;

    case 'complete':
      baseData = { ...completeEquityGrantFixture };
      break;

    case 'invalid':
      // Return invalid data (caller should handle validation failure)
      baseData = { ...invalidEquityGrantFixture } as EquityGrantCreateRequest;
      break;

    case 'unique':
      // Generate fresh unique values for each call
      baseData = {
        ...uniqueEquityGrantFixture,
      };
      break;

    default:
      baseData = { ...completeEquityGrantFixture };
  }

  return { ...baseData, ...overrides };
}

/**
 * Generate multiple equity_grant fixtures
 *
 * @param count - Number of fixtures to generate
 * @param pattern - The test data pattern to use as base
 * @param modifier - Optional function to modify each fixture
 * @returns Array of generated test data
 *
 * @example
 * ```typescript
 * // Generate 5 unique fixtures
 * const fixtures = generateMultipleEquityGrantFixtures(5, 'unique');
 *
 * // Generate fixtures with sequential numbering
 * const numbered = generateMultipleEquityGrantFixtures(3, 'complete', (data, index) => ({
 *   ...data,
 *   name: `EquityGrant #${index + 1}`,
 * }));
 * ```
 */
export function generateMultipleEquityGrantFixtures(
  count: number,
  pattern: TestDataPattern = 'unique',
  modifier?: (data: EquityGrantCreateRequest, index: number) => EquityGrantCreateRequest
): EquityGrantCreateRequest[] {
  const fixtures: EquityGrantCreateRequest[] = [];

  for (let i = 0; i < count; i++) {
    let fixture = generateEquityGrantTestData(pattern);

    if (modifier) {
      fixture = modifier(fixture, i);
    } else if (pattern === 'unique') {
      // Add index to ensure uniqueness even with same timestamp
    }

    fixtures.push(fixture);
  }

  return fixtures;
}

/**
 * Generate random equity_grant test data
 *
 * Creates test data with randomized values within valid ranges.
 * Useful for fuzz testing and edge case discovery.
 *
 * @param overrides - Optional field overrides
 * @returns Randomly generated test data
 *
 * @example
 * ```typescript
 * // Generate random test data
 * const randomData = generateRandomEquityGrantData();
 *
 * // Generate random data with specific field
 * const customRandom = generateRandomEquityGrantData({
 *   is_active: true,
 * });
 * ```
 */
export function generateRandomEquityGrantData(
  overrides: Partial<EquityGrantCreateRequest> = {}
): EquityGrantCreateRequest {
  const data: EquityGrantCreateRequest = {
    legal_entity_id: randomString(randomInt(None, Math.min(None, 50))),
    holder_person_id: randomString(randomInt(None, Math.min(None, 50))),
    holder_entity_id: randomString(randomInt(None, Math.min(None, 50))),
    holder_type: randomString(randomInt(None, Math.min(10, 50))),
    share_class: randomString(randomInt(None, Math.min(30, 50))),
    number_of_shares: randomInt(0, 1000),
    percentage: randomDecimal(0, 100),
    valuation: randomInt(0, 1000),
    issue_date: randomString(randomInt(None, Math.min(None, 50))),
    source_document_id: randomString(randomInt(None, Math.min(None, 50))),
  };

  return { ...data, ...overrides };
}

// ============================================================================
// Validation Test Data
// ============================================================================

/**
 * Edge case test data for boundary testing
 *
 * Contains values at the boundaries of valid ranges.
 */
export const equityGrantEdgeCases = {
  /** holder_type at maximum length (10 chars) */
  holder_typeMaxLength: 'x'.repeat(10),
  /** share_class at maximum length (30 chars) */
  share_classMaxLength: 'x'.repeat(30),
};

/**
 * Special character test data for input sanitization testing
 */
export const equityGrantSpecialCharacterData: Partial<EquityGrantCreateRequest> = {
};

/**
 * Whitespace test data for trimming validation
 */
export const equityGrantWhitespaceData: Partial<EquityGrantCreateRequest> = {
};

// ============================================================================
// Exports
// ============================================================================

// Default export - main fixture collection
export default equityGrantFixtures;
