"""ShortlistTag API Endpoints - Generated by Code Generator v1.0.0

This module provides RESTful API endpoints for ShortlistTag CRUD operations.

Endpoints:
    - POST /api/v1/shortlist_tags/ - Create a new ShortlistTag
    - GET /api/v1/shortlist_tags/{id} - Get ShortlistTag by ID
    - GET /api/v1/shortlist_tags/ - List ShortlistTags with pagination
    - PUT /api/v1/shortlist_tags/{id} - Update ShortlistTag
    - DELETE /api/v1/shortlist_tags/{id} - Delete ShortlistTag
"""

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import JSONResponse
from sqlalchemy.ext.asyncio import AsyncSession
from typing import List, Optional
from uuid import UUID
from crm_service.core.database import get_session
from crm_service.application.services.shortlist_tag_service import ShortlistTagService
from crm_service.schemas.shortlist_tag import (
    ShortlistTagCreate,
    ShortlistTagUpdate,
    ShortlistTagResponse,
)

# OpenAPI tag metadata for this router
TAGS_METADATA = [
    {
        "name": "ShortlistTags",
        "description": "Operations for managing ShortlistTag resources. Supports full CRUD operations with pagination.",
    }
]

router = APIRouter(tags=["ShortlistTags"])


# Response examples for OpenAPI documentation
EXAMPLE_RESPONSE = {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "shortlist_id": "550e8400-e29b-41d4-a716-446655440000",
    "tag_id": "550e8400-e29b-41d4-a716-446655440000",
    "created_at": "2024-01-01T12:00:00Z",
    "updated_at": "2024-01-01T12:00:00Z",
}


@router.post(
    "",
    response_model=ShortlistTagResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Create ShortlistTag",
    description="Create a new ShortlistTag with the provided data.",
    responses={
        201: {
            "description": "ShortlistTag created successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        400: {
            "description": "Invalid request body",
            "content": {"application/json": {"example": {"detail": "Invalid request body"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "field required",
                                "type": "value_error.missing",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.post(
    "/",
    response_model=ShortlistTagResponse,
    status_code=status.HTTP_201_CREATED,
    include_in_schema=False,
)
async def create_shortlist_tag(
    data: ShortlistTagCreate, request: Request, session: AsyncSession = Depends(get_session)
) -> ShortlistTagResponse:
    """
    Create a new ShortlistTag.

    Creates a new ShortlistTag record with the provided data. All required fields
    must be included in the request body. Auto-generated fields (id, created_at,
    updated_at) will be set automatically.

    Args:
        data: ShortlistTagCreate schema with the ShortlistTag data.
        request: FastAPI Request (for tenant context).
        session: Database session (injected).

    Returns:
        ShortlistTagResponse: The created ShortlistTag with all fields including auto-generated ones.

    Raises:
        HTTPException: 400 if request body is invalid, 422 if validation fails.
    """
    tenant_id = getattr(request.state, "tenant_id", None)
    service = ShortlistTagService(session)
    return await service.create_shortlist_tag(data, tenant_id=tenant_id)


@router.get(
    "/{id}",
    response_model=ShortlistTagResponse,
    summary="Get ShortlistTag by ID",
    description="Retrieve a single ShortlistTag by its unique identifier.",
    responses={
        200: {
            "description": "ShortlistTag found",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "ShortlistTag not found",
            "content": {"application/json": {"example": {"detail": "ShortlistTag not found"}}},
        },
    },
)
@router.get("/{id}/", response_model=ShortlistTagResponse, include_in_schema=False)
async def get_shortlist_tag(
    id: UUID, session: AsyncSession = Depends(get_session)
) -> ShortlistTagResponse:
    """
    Get ShortlistTag by ID.

    Retrieves a single ShortlistTag record by its unique identifier (UUID).

    Args:
        id: The unique identifier (UUID) of the ShortlistTag to retrieve.
        session: Database session (injected).

    Returns:
        ShortlistTagResponse: The ShortlistTag data if found.

    Raises:
        HTTPException: 404 if ShortlistTag with the given ID is not found.
    """
    service = ShortlistTagService(session)
    result = await service.get_shortlist_tag(id)
    if not result:
        raise HTTPException(status_code=404, detail="ShortlistTag not found")
    return result


@router.get(
    "",
    response_model=List[ShortlistTagResponse],
    summary="List ShortlistTags",
    description="Retrieve a paginated list of ShortlistTags. Supports both page-based and offset-based pagination.",
    responses={
        200: {
            "description": "List of ShortlistTags",
            "content": {"application/json": {"example": [EXAMPLE_RESPONSE]}},
        },
    },
)
@router.get("/", response_model=List[ShortlistTagResponse], include_in_schema=False)
async def list_shortlist_tags(
    page: int = Query(
        default=1,
        ge=1,
        description="Page number (1-indexed). Used for page-based pagination.",
        example=1,
    ),
    page_size: int = Query(
        default=50,
        ge=1,
        le=200,
        description="Number of items per page (1-200).",
        example=50,
    ),
    skip: Optional[int] = Query(
        default=None,
        ge=0,
        description="Number of items to skip. Used for offset-based pagination. Overrides page if provided.",
        example=0,
    ),
    limit: Optional[int] = Query(
        default=None,
        ge=1,
        le=200,
        description="Maximum number of items to return (1-200). Used with skip for offset-based pagination.",
        example=100,
    ),
    session: AsyncSession = Depends(get_session),
) -> List[ShortlistTagResponse]:
    """
    List ShortlistTags with pagination.

    Retrieves a paginated list of ShortlistTag records. Supports two pagination styles:

    **Page-based pagination** (default):
    - Use `page` (1-indexed) and `page_size` parameters
    - Example: `?page=2&page_size=25` returns items 26-50

    **Offset-based pagination**:
    - Use `skip` and `limit` parameters
    - Example: `?skip=20&limit=10` returns items 21-30

    If both styles are provided, offset-based (`skip`/`limit`) takes precedence.

    Args:
        page: Page number (1-indexed, default: 1).
        page_size: Items per page (default: 50, max: 200).
        skip: Items to skip (offset-based pagination).
        limit: Max items to return (offset-based pagination).
        session: Database session (injected).

    Returns:
        List[ShortlistTagResponse]: List of ShortlistTags. Empty list if no records found.
    """
    # Convert page-based to offset-based pagination
    if skip is None and limit is None:
        # Use page/page_size (default)
        skip = (page - 1) * page_size if page > 0 else 0
        limit = page_size
    elif limit is None:
        limit = 100

    service = ShortlistTagService(session)
    return await service.list_shortlist_tags(skip, limit)


@router.put(
    "/{id}",
    response_model=ShortlistTagResponse,
    summary="Update ShortlistTag",
    description="Update an existing ShortlistTag by ID. All fields in the request body are optional; only provided fields will be updated.",
    responses={
        200: {
            "description": "ShortlistTag updated successfully",
            "content": {"application/json": {"example": EXAMPLE_RESPONSE}},
        },
        404: {
            "description": "ShortlistTag not found",
            "content": {"application/json": {"example": {"detail": "ShortlistTag not found"}}},
        },
        422: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "example": {
                        "detail": [
                            {
                                "loc": ["body", "field_name"],
                                "msg": "invalid value",
                                "type": "value_error",
                            }
                        ]
                    }
                }
            },
        },
    },
)
@router.put("/{id}/", response_model=ShortlistTagResponse, include_in_schema=False)
async def update_shortlist_tag(
    id: UUID, data: ShortlistTagUpdate, session: AsyncSession = Depends(get_session)
) -> ShortlistTagResponse:
    """
    Update ShortlistTag.

    Updates an existing ShortlistTag record with the provided data. This is a partial
    update (PATCH-like behavior) - only fields included in the request body will be updated.
    Fields set to `null` will clear the existing value (if nullable).

    The `updated_at` timestamp will be automatically set to the current time.

    Args:
        id: The unique identifier (UUID) of the ShortlistTag to update.
        data: ShortlistTagUpdate schema with fields to update (all fields optional).
        session: Database session (injected).

    Returns:
        ShortlistTagResponse: The updated ShortlistTag with all current values.

    Raises:
        HTTPException: 404 if ShortlistTag not found, 422 if validation fails.
    """
    service = ShortlistTagService(session)
    result = await service.update_shortlist_tag(id, data)
    if not result:
        raise HTTPException(status_code=404, detail="ShortlistTag not found")
    return result


@router.delete(
    "/{id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete ShortlistTag",
    description="Delete a ShortlistTag by ID. This operation is permanent and cannot be undone.",
    responses={
        204: {
            "description": "ShortlistTag deleted successfully (no content returned)",
        },
        404: {
            "description": "ShortlistTag not found",
            "content": {"application/json": {"example": {"detail": "ShortlistTag not found"}}},
        },
    },
)
@router.delete("/{id}/", status_code=status.HTTP_204_NO_CONTENT, include_in_schema=False)
async def delete_shortlist_tag(id: UUID, session: AsyncSession = Depends(get_session)) -> None:
    """
    Delete ShortlistTag.

    Permanently deletes a ShortlistTag record by its unique identifier.
    This operation cannot be undone.

    Args:
        id: The unique identifier (UUID) of the ShortlistTag to delete.
        session: Database session (injected).

    Returns:
        None: Returns HTTP 204 No Content on success.

    Raises:
        HTTPException: 404 if ShortlistTag with the given ID is not found.
    """
    service = ShortlistTagService(session)
    deleted = await service.delete_shortlist_tag(id)
    if not deleted:
        raise HTTPException(status_code=404, detail="ShortlistTag not found")
