/**
 * InvestorPastInvestmentDetail Component
 *
 * Displays detailed information about a investor_past_investment in a structured layout.
 * Organized into sections:
 * - Basic Information (all entity fields)
 * - Status (active/inactive indicator)
 * - Audit Trail (created/updated timestamps)
 *
 * Features:
 * - React Query integration for data fetching
 * - Material UI Grid layout for responsive design
 * - Loading skeleton states
 * - Error handling with Alert component
 * - Not found state handling
 * - Edit/Delete action buttons
 * - Back navigation
 * - Status badge indicators (active/inactive)
 * - Formatted dates and numbers
 * - Accessibility support (WCAG 2.1 Level AA)
 *
 * Many-to-many junction between investors and their past investments
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:11.404234Z
 */

import React, { useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Box,
  Paper,
  Grid,
  Typography,
  Alert as MuiAlert,
  Skeleton,
  IconButton,
  Button,
  Chip,
  Divider,
  Tooltip,
} from '@mui/material';
import {
  ArrowBack as ArrowBackIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';
import { useInvestorPastInvestment} from '../hooks/useInvestorPastInvestments';
import type { InvestorPastInvestment} from '../types/investor_past_investment.types';

// ============================================================================
// Types
// ============================================================================

/**
 * Props for InvestorPastInvestmentDetail component
 */
interface InvestorPastInvestmentDetailProps {
  /** Entity ID to display (optional, can be read from URL params) */
  id?: string;
  /** Whether to show the back button */
  showBackButton?: boolean;
  /** Whether to show edit button */
  showEditButton?: boolean;
  /** Whether to show delete button */
  showDeleteButton?: boolean;
  /** Callback when edit button is clicked */
  onEdit?: (investorPastInvestment: InvestorPastInvestment) => void;
  /** Callback when delete button is clicked */
  onDelete?: (investorPastInvestment: InvestorPastInvestment) => void;
  /** Custom className for the container */
  className?: string;
}

// ============================================================================
// Helper Components
// ============================================================================

/**
 * Field component for displaying label-value pairs
 */
const DetailField: React.FC<{
  label: string;
  value: string | React.ReactNode;
  testId: string;
}> = ({ label, value, testId }) => (
  <div data-testid={testId}>
    <label>
      <Typography variant="body2" color="text.secondary" component="span">
        {label}
      </Typography>
    </label>
    <span>
      <Typography variant="body1" component="span">
        {value}
      </Typography>
    </span>
  </div>
);

/**
 * Loading skeleton for the detail view
 */
const DetailSkeleton: React.FC = () => (
  <Box data-testid="investor_past_investment-detail-skeleton">
    <Box display="flex" alignItems="center" gap={2} mb={3}>
      <Skeleton variant="circular" width={40} height={40} />
      <Skeleton variant="text" width={200} height={32} />
    </Box>
    <Paper sx={{ p: 3 }}>
      <Skeleton variant="text" width={150} height={28} sx={{ mb: 2 }} />
      {Array.from({ length: 6 }).map((_, index) => (
        <Box key={index} sx={{ mb: 2 }}>
          <Skeleton variant="text" width={100} height={16} />
          <Skeleton variant="text" width={250} height={24} />
        </Box>
      ))}
    </Paper>
  </Box>
);

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Format a date string for display
 */
function formatDate(value: string | undefined | null): string {
  if (!value) return '-';
  try {
    return new Date(value).toLocaleString();
  } catch {
    return value;
  }
}


/**
 * Display a value with fallback for empty/null values
 */
function displayValue(value: string | number | boolean | undefined | null): string {
  if (value === null || value === undefined) return '-';
  if (typeof value === 'string') {
    return value.trim() !== '' ? value : '-';
  }
  if (typeof value === 'boolean') {
    return value ? 'Yes' : 'No';
  }
  return String(value);
}

// ============================================================================
// Component
// ============================================================================

/**
 * InvestorPastInvestmentDetail Component
 *
 * Renders comprehensive investor_past_investment information in a structured grid layout.
 *
 * @example
 * ```tsx
 * // Using URL params (in a route like /investor_past_investments/:id)
 * <InvestorPastInvestmentDetail />
 *
 * // With explicit ID
 * <InvestorPastInvestmentDetail id="123" />
 *
 * // With custom handlers
 * <InvestorPastInvestmentDetail
 *   onEdit={(entity) => navigate(`/investor_past_investments/${entity.id}/edit`)}
 *   onDelete={(entity) => handleDelete(entity.id)}
 * />
 * ```
 */
export function InvestorPastInvestmentDetail({
  id: propId,
  showBackButton = true,
  showEditButton = true,
  showDeleteButton = true,
  onEdit,
  onDelete,
  className = '',
}: InvestorPastInvestmentDetailProps): React.ReactElement {
  const navigate = useNavigate();
  const params = useParams<{ id: string }>();

  // Use prop ID if provided, otherwise get from URL params
  const id = propId ?? params.id;

  // -------------------------------------------------------------------------
  // Data Fetching
  // -------------------------------------------------------------------------

  const {
    data: investorPastInvestment,
    isLoading,
    isError,
    error,
    refetch,
  } = useInvestorPastInvestment(id ?? '', {
    enabled: Boolean(id),
  });

  // -------------------------------------------------------------------------
  // Handlers
  // -------------------------------------------------------------------------

  /** Handle back button click */
  const handleBack = useCallback(() => {
    navigate('/investor_past_investments');
  }, [navigate]);

  /** Handle edit button click */
  const handleEdit = useCallback(() => {
    if (investorPastInvestment) {
      if (onEdit) {
        onEdit(investorPastInvestment);
      } else {
        navigate(`/investor_past_investments/${investorPastInvestment.id}/edit`);
      }
    }
  }, [navigate, investorPastInvestment, onEdit]);

  /** Handle delete button click */
  const handleDelete = useCallback(() => {
    if (investorPastInvestment && onDelete) {
      onDelete(investorPastInvestment);
    }
  }, [investorPastInvestment, onDelete]);

  /** Handle refresh button click */
  const handleRefresh = useCallback(() => {
    refetch();
  }, [refetch]);

  // -------------------------------------------------------------------------
  // Render States
  // -------------------------------------------------------------------------

  // Loading state
  if (isLoading) {
    return (
      <Box className={className}>
        <DetailSkeleton />
      </Box>
    );
  }

  // Error state
  if (isError) {
    return (
      <Box className={className} p={3}>
        <MuiAlert
          severity="error"
          action={
            <IconButton color="inherit" size="small" onClick={handleRefresh}>
              <RefreshIcon />
            </IconButton>
          }
        >
          Error loading investor_past_investment: {(error as Error)?.message || 'Unknown error'}
        </MuiAlert>
      </Box>
    );
  }

  // Not found state
  if (!investorPastInvestment) {
    return (
      <Box className={className} p={3}>
        <MuiAlert severity="warning">
          InvestorPastInvestment not found
        </MuiAlert>
        {showBackButton && (
          <Box mt={2}>
            <Button
              startIcon={<ArrowBackIcon />}
              onClick={handleBack}
              variant="outlined"
            >
              Back to InvestorPastInvestments
            </Button>
          </Box>
        )}
      </Box>
    );
  }

  // -------------------------------------------------------------------------
  // Main Render
  // -------------------------------------------------------------------------

  return (
    <div data-testid="investor_past_investment-detail" className={className}>
      {/* Header */}
      <Box
        display="flex"
        justifyContent="space-between"
        alignItems="center"
        mb={3}
      >
        <Box display="flex" alignItems="center" gap={2}>
          {showBackButton && (
            <Tooltip title="Back to InvestorPastInvestments">
              <IconButton onClick={handleBack}>
                <ArrowBackIcon />
              </IconButton>
            </Tooltip>
          )}
          <Typography variant="h5" component="h1">
            InvestorPastInvestment Details
          </Typography>
{investorPastInvestment.is_active !== undefined && (
            <Chip
              size="small"
              label={investorPastInvestment.is_active ? 'Active' : 'Inactive'}
              color={investorPastInvestment.is_active ? 'success' : 'default'}
              variant="outlined"
            />
          )}
        </Box>

        <Box display="flex" gap={1}>
          <Tooltip title="Refresh">
            <span>
              <IconButton onClick={handleRefresh} disabled={isLoading}>
                <RefreshIcon />
              </IconButton>
            </span>
          </Tooltip>

          {showEditButton && (
            <Tooltip title="Edit InvestorPastInvestment">
              <IconButton onClick={handleEdit} color="primary">
                <EditIcon />
              </IconButton>
            </Tooltip>
          )}

          {showDeleteButton && onDelete && (
            <Tooltip title="Delete InvestorPastInvestment">
              <IconButton onClick={handleDelete} color="error">
                <DeleteIcon />
              </IconButton>
            </Tooltip>
          )}
        </Box>
      </Box>

      {/* Detail Content */}
      <Paper sx={{ p: 3 }}>
        <Grid container spacing={3}>
          {/* Basic Information Section */}
          <Grid size={12}>
            <section data-testid="basic-info-section" aria-label="Basic Information">
              <Typography variant="h6" component="h2" gutterBottom>
                Basic Information
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                {/* ID field */}
                <DetailField
                  label="ID:"
                  value={investorPastInvestment.id}
                  testId="field-id"
                />

                {/* Investor Id field */}
                <DetailField
                  label="Investor Id:"
                  value={displayValue(investorPastInvestment.investor_id)}
                  testId="field-investor-id"
                />

                {/* Past Investment Id field */}
                <DetailField
                  label="Past Investment Id:"
                  value={displayValue(investorPastInvestment.past_investment_id)}
                  testId="field-past-investment-id"
                />

              </Box>
            </section>
          </Grid>

          {/* Status Section */}
          <Grid size={12}>
            <Divider sx={{ my: 2 }} />
            <section data-testid="status-section" aria-label="Status">
              <Typography variant="h6" component="h2" gutterBottom>
                Status
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <div data-testid="field-status">
                  <label>
                    <Typography variant="body2" color="text.secondary" component="span">
                      Status:
                    </Typography>
                  </label>
                  <span className={investorPastInvestment.is_active ? 'active-badge' : 'inactive-badge'}>
                    <Typography variant="body1" component="span">
                      {investorPastInvestment.is_active ? 'Active' : 'Inactive'}
                    </Typography>
                  </span>
                </div>
              </Box>
            </section>
          </Grid>

          {/* Audit Trail Section */}
          <Grid size={12}>
            <Divider sx={{ my: 2 }} />
            <section data-testid="audit-trail-section" aria-label="Audit Trail">
              <Typography variant="h6" component="h2" gutterBottom>
                Audit Trail
              </Typography>

              <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
                <DetailField
                  label="Created At:"
                  value={formatDate(investorPastInvestment.created_at)}
                  testId="field-created-at"
                />

                <DetailField
                  label="Updated At:"
                  value={formatDate(investorPastInvestment.updated_at)}
                  testId="field-updated-at"
                />

              </Box>
            </section>
          </Grid>
        </Grid>
      </Paper>
    </div>
  );
}

// Default export for convenience
export default InvestorPastInvestmentDetail;
