/**
 * ContactPerson Query Key Factory
 *
 * Centralized query key factory for React Query cache management.
 * Provides consistent, type-safe query keys for all contact_person queries.
 *
 * Query keys follow a hierarchical structure for efficient cache invalidation:
 * - ['contactpersons'] - All contact_person queries
 * - ['contactpersons', 'list'] - All list queries
 * - ['contactpersons', 'list', { filters }] - Specific filtered list
 * - ['contactpersons', 'detail', id] - Specific contact_person by ID
 *
 * @example
 * ```typescript
 * import { contact_personKeys } from './queryKeys';
 *
 * // Use in useQuery
 * const { data } = useQuery({
 *   queryKey: contact_personKeys.list({ is_active: true }),
 *   queryFn: () => contact_personService.getAll({ is_active: true }),
 * });
 *
 * // Invalidate all contact_person queries
 * queryClient.invalidateQueries({ queryKey: contact_personKeys.all });
 *
 * // Invalidate specific contact_person
 * queryClient.invalidateQueries({ queryKey: contact_personKeys.detail('uuid') });
 * ```
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:50.270907Z
 */

import type { ContactPersonFilterOptions } from '../types/contact_person.types';

/**
 * Root query key for ContactPerson entity
 * Used as namespace prefix for all contact_person queries
 */
const CONTACT_PERSON_ROOT = 'contactpersons' as const;

/**
 * ContactPerson Query Keys
 *
 * Hierarchical query key factory for contact_person queries:
 * - all: Base key for all contact_person queries
 * - lists: All list queries (for bulk invalidation)
 * - list(filters): Specific filtered list
 * - details: All detail queries
 * - detail(id): Specific contact_person by ID
 * - dropdown(activeOnly): Dropdown options query
 *
 * @example
 * ```typescript
 * // List with filters
 * const key = contact_personKeys.list({ is_active: true });
 * // Result: ['contactpersons', 'list', { is_active: true }]
 *
 * // Detail by ID
 * const key = contact_personKeys.detail('uuid-here');
 * // Result: ['contactpersons', 'detail', 'uuid-here']
 *
 * // Invalidate all contact_person data
 * queryClient.invalidateQueries({ queryKey: contact_personKeys.all });
 * ```
 */
export const contact_personKeys = {
  /**
   * Base key for all contact_person queries
   * Use this to invalidate all contact_person-related queries at once
   *
   * @example
   * ```typescript
   * // Invalidate everything after a major change
   * queryClient.invalidateQueries({ queryKey: contact_personKeys.all });
   * ```
   */
  all: [CONTACT_PERSON_ROOT] as const,

  /**
   * Key for all list queries
   * Use this to invalidate all list queries without affecting detail queries
   *
   * @returns Query key tuple for list namespace
   *
   * @example
   * ```typescript
   * // Invalidate all list queries
   * queryClient.invalidateQueries({ queryKey: contact_personKeys.lists() });
   * ```
   */
  lists: () => [...contact_personKeys.all, 'list'] as const,

  /**
   * Key for a specific filtered list query
   * Include filters in the key to enable automatic re-fetching when filters change
   *
   * @param filters - Optional filter options for the query
   * @returns Query key tuple including filters
   *
   * @example
   * ```typescript
   * // List all active
   * const key = contact_personKeys.list({ is_active: true });
   *
   * // List with search
   * const key = contact_personKeys.list({ search: 'test' });
   *
   * // Unfiltered list
   * const key = contact_personKeys.list();
   * ```
   */
  list: (filters?: ContactPersonFilterOptions) =>
    [...contact_personKeys.lists(), filters ?? {}] as const,

  /**
   * Key for all detail queries
   * Use this to invalidate all detail queries without affecting list queries
   *
   * @returns Query key tuple for detail namespace
   *
   * @example
   * ```typescript
   * // Invalidate all detail queries
   * queryClient.invalidateQueries({ queryKey: contact_personKeys.details() });
   * ```
   */
  details: () => [...contact_personKeys.all, 'detail'] as const,

  /**
   * Key for a specific contact_person by ID
   * Use this for fetching and invalidating individual contact_person records
   *
   * @param id - ContactPerson ID (UUID)
   * @returns Query key tuple for specific contact_person
   *
   * @example
   * ```typescript
   * // Fetch specific contact_person
   * const { data } = useQuery({
   *   queryKey: contact_personKeys.detail('uuid-here'),
   *   queryFn: () => contact_personService.getById('uuid-here'),
   * });
   *
   * // Invalidate after update
   * queryClient.invalidateQueries({
   *   queryKey: contact_personKeys.detail('uuid-here')
   * });
   * ```
   */
  detail: (id: string) => [...contact_personKeys.details(), id] as const,

  /**
   * Key for dropdown options query
   * Separate key allows independent caching of dropdown data
   *
   * @param activeOnly - Whether to include only active contact_persons (default: true)
   * @returns Query key tuple for dropdown query
   *
   * @example
   * ```typescript
   * // Active items only (default)
   * const key = contact_personKeys.dropdown();
   *
   * // Include inactive items
   * const key = contact_personKeys.dropdown(false);
   * ```
   */
  dropdown: (activeOnly: boolean = true) =>
    [...contact_personKeys.all, 'dropdown', { activeOnly }] as const,

  /**
   * ContactPersons filtered by user ID
   *
   * @param userId - User ID (UUID)
   * @returns Query key tuple
   */
  byUser: (userId: string) =>
    [...contact_personKeys.all, 'by-user', userId] as const,

  /**
   * ContactPersons filtered by legal entity ID
   *
   * @param legalEntityId - LegalEntity ID (UUID)
   * @returns Query key tuple
   */
  byLegalEntity: (legalEntityId: string) =>
    [...contact_personKeys.all, 'by-legal-entity', legalEntityId] as const,

  /**
   * ContactPersons filtered by residential address ID
   *
   * @param residentialAddressId - ResidentialAddress ID (UUID)
   * @returns Query key tuple
   */
  byResidentialAddress: (residentialAddressId: string) =>
    [...contact_personKeys.all, 'by-residential-address', residentialAddressId] as const,
} as const;

/**
 * Type representing any valid ContactPerson query key
 * Useful for typing query key arrays in generic contexts
 */
export type ContactPersonQueryKey =
  | typeof contact_personKeys.all
  | ReturnType<typeof contact_personKeys.lists>
  | ReturnType<typeof contact_personKeys.list>
  | ReturnType<typeof contact_personKeys.details>
  | ReturnType<typeof contact_personKeys.detail>
  | ReturnType<typeof contact_personKeys.dropdown>
;

/**
 * Default export for convenience
 */
export default contact_personKeys;
