/**
 * LegalDocument Query Key Factory
 *
 * Centralized query key factory for React Query cache management.
 * Provides consistent, type-safe query keys for all legal_document queries.
 *
 * Query keys follow a hierarchical structure for efficient cache invalidation:
 * - ['legaldocuments'] - All legal_document queries
 * - ['legaldocuments', 'list'] - All list queries
 * - ['legaldocuments', 'list', { filters }] - Specific filtered list
 * - ['legaldocuments', 'detail', id] - Specific legal_document by ID
 *
 * @example
 * ```typescript
 * import { legal_documentKeys } from './queryKeys';
 *
 * // Use in useQuery
 * const { data } = useQuery({
 *   queryKey: legal_documentKeys.list({ is_active: true }),
 *   queryFn: () => legal_documentService.getAll({ is_active: true }),
 * });
 *
 * // Invalidate all legal_document queries
 * queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
 *
 * // Invalidate specific legal_document
 * queryClient.invalidateQueries({ queryKey: legal_documentKeys.detail('uuid') });
 * ```
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:54.004558Z
 */

import type { LegalDocumentFilterOptions } from '../types/legal_document.types';

/**
 * Root query key for LegalDocument entity
 * Used as namespace prefix for all legal_document queries
 */
const LEGAL_DOCUMENT_ROOT = 'legaldocuments' as const;

/**
 * LegalDocument Query Keys
 *
 * Hierarchical query key factory for legal_document queries:
 * - all: Base key for all legal_document queries
 * - lists: All list queries (for bulk invalidation)
 * - list(filters): Specific filtered list
 * - details: All detail queries
 * - detail(id): Specific legal_document by ID
 * - dropdown(activeOnly): Dropdown options query
 *
 * @example
 * ```typescript
 * // List with filters
 * const key = legal_documentKeys.list({ is_active: true });
 * // Result: ['legaldocuments', 'list', { is_active: true }]
 *
 * // Detail by ID
 * const key = legal_documentKeys.detail('uuid-here');
 * // Result: ['legaldocuments', 'detail', 'uuid-here']
 *
 * // Invalidate all legal_document data
 * queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
 * ```
 */
export const legal_documentKeys = {
  /**
   * Base key for all legal_document queries
   * Use this to invalidate all legal_document-related queries at once
   *
   * @example
   * ```typescript
   * // Invalidate everything after a major change
   * queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
   * ```
   */
  all: [LEGAL_DOCUMENT_ROOT] as const,

  /**
   * Key for all list queries
   * Use this to invalidate all list queries without affecting detail queries
   *
   * @returns Query key tuple for list namespace
   *
   * @example
   * ```typescript
   * // Invalidate all list queries
   * queryClient.invalidateQueries({ queryKey: legal_documentKeys.lists() });
   * ```
   */
  lists: () => [...legal_documentKeys.all, 'list'] as const,

  /**
   * Key for a specific filtered list query
   * Include filters in the key to enable automatic re-fetching when filters change
   *
   * @param filters - Optional filter options for the query
   * @returns Query key tuple including filters
   *
   * @example
   * ```typescript
   * // List all active
   * const key = legal_documentKeys.list({ is_active: true });
   *
   * // List with search
   * const key = legal_documentKeys.list({ search: 'test' });
   *
   * // Unfiltered list
   * const key = legal_documentKeys.list();
   * ```
   */
  list: (filters?: LegalDocumentFilterOptions) =>
    [...legal_documentKeys.lists(), filters ?? {}] as const,

  /**
   * Key for all detail queries
   * Use this to invalidate all detail queries without affecting list queries
   *
   * @returns Query key tuple for detail namespace
   *
   * @example
   * ```typescript
   * // Invalidate all detail queries
   * queryClient.invalidateQueries({ queryKey: legal_documentKeys.details() });
   * ```
   */
  details: () => [...legal_documentKeys.all, 'detail'] as const,

  /**
   * Key for a specific legal_document by ID
   * Use this for fetching and invalidating individual legal_document records
   *
   * @param id - LegalDocument ID (UUID)
   * @returns Query key tuple for specific legal_document
   *
   * @example
   * ```typescript
   * // Fetch specific legal_document
   * const { data } = useQuery({
   *   queryKey: legal_documentKeys.detail('uuid-here'),
   *   queryFn: () => legal_documentService.getById('uuid-here'),
   * });
   *
   * // Invalidate after update
   * queryClient.invalidateQueries({
   *   queryKey: legal_documentKeys.detail('uuid-here')
   * });
   * ```
   */
  detail: (id: string) => [...legal_documentKeys.details(), id] as const,

  /**
   * Key for dropdown options query
   * Separate key allows independent caching of dropdown data
   *
   * @param activeOnly - Whether to include only active legal_documents (default: true)
   * @returns Query key tuple for dropdown query
   *
   * @example
   * ```typescript
   * // Active items only (default)
   * const key = legal_documentKeys.dropdown();
   *
   * // Include inactive items
   * const key = legal_documentKeys.dropdown(false);
   * ```
   */
  dropdown: (activeOnly: boolean = true) =>
    [...legal_documentKeys.all, 'dropdown', { activeOnly }] as const,

  /**
   * LegalDocuments filtered by user ID
   *
   * @param userId - User ID (UUID)
   * @returns Query key tuple
   */
  byUser: (userId: string) =>
    [...legal_documentKeys.all, 'by-user', userId] as const,

  /**
   * LegalDocuments filtered by template ID
   *
   * @param templateId - Template ID (UUID)
   * @returns Query key tuple
   */
  byTemplate: (templateId: string) =>
    [...legal_documentKeys.all, 'by-template', templateId] as const,

  /**
   * LegalDocuments filtered by investor ID
   *
   * @param investorId - Investor ID (UUID)
   * @returns Query key tuple
   */
  byInvestor: (investorId: string) =>
    [...legal_documentKeys.all, 'by-investor', investorId] as const,

  /**
   * LegalDocuments filtered by status
   *
   * @param status - Status value
   * @returns Query key tuple
   */
  byStatus: (status: string) =>
    [...legal_documentKeys.all, 'by-status', status] as const,
} as const;

/**
 * Type representing any valid LegalDocument query key
 * Useful for typing query key arrays in generic contexts
 */
export type LegalDocumentQueryKey =
  | typeof legal_documentKeys.all
  | ReturnType<typeof legal_documentKeys.lists>
  | ReturnType<typeof legal_documentKeys.list>
  | ReturnType<typeof legal_documentKeys.details>
  | ReturnType<typeof legal_documentKeys.detail>
  | ReturnType<typeof legal_documentKeys.dropdown>
;

/**
 * Default export for convenience
 */
export default legal_documentKeys;
