/**
 * useLegalDocuments Hooks
 *
 * React Query hooks for LegalDocument CRUD operations with automatic caching
 * and cache invalidation.
 *
 * Hooks provided:
 * - useLegalDocuments: List legal_documents with optional filters
 * - useLegalDocument: Get single legal_document by ID
 * - useLegalDocumentsDropdown: Get legal_documents formatted for dropdown selection
 * - useCreateLegalDocument: Create new legal_document
 * - useUpdateLegalDocument: Update existing legal_document
 * - useDeleteLegalDocument: Delete legal_document
 *
 * Features:
 * - Automatic caching with configurable stale/gc times
 * - Cache invalidation on mutations
 * - Loading and error states
 * - Request deduplication
 * - Retry with exponential backoff
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T20:43:54.021211Z
 */

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseQueryResult,
  UseMutationResult,
} from '@tanstack/react-query';
import { useMemo } from 'react';
import { legal_documentService } from '../services/legal_document.service';
import { legal_documentKeys } from './legal_documentKeys';
import type {
  LegalDocument,
  LegalDocumentCreateRequest,
  LegalDocumentUpdateRequest,
  LegalDocumentFilterOptions,
} from '../types/legal_document.types';

/**
 * Cache timing constants (in milliseconds)
 * Configurable via entity definition or defaults
 */
const LEGAL_DOCUMENT_STALE_TIME = 300000; // 5 minutes
const LEGAL_DOCUMENT_GC_TIME = 1800000; // 30 minutes

/**
 * Retry configuration
 * - 3 retries with exponential backoff
 * - Delays: 1s, 2s, 4s (2^attemptIndex * 1000)
 */
const RETRY_COUNT = 3;
const retryDelay = (attemptIndex: number) =>
  Math.min(1000 * 2 ** attemptIndex, 30000);

/**
 * Options for the useLegalDocuments hook
 */
export interface UseLegalDocumentsOptions {
  /**
   * Filter to only return active legal_documents
   * @default true
   */
  activeOnly?: boolean;

  /**
   * Additional filter options for the query
   */
  filters?: Omit<LegalDocumentFilterOptions, 'is_active'>;

  /**
   * Whether to enable the query
   * @default true
   */
  enabled?: boolean;
}

/**
 * Return type for the useLegalDocuments hook
 */
export interface UseLegalDocumentsResult
  extends Omit<UseQueryResult<LegalDocument[], Error>, 'data'> {
  /** Array of legal_document data */
  data: LegalDocument[] | undefined;

  /** Convenience alias for data */
  legalDocuments: LegalDocument[] | undefined;
}

/**
 * Hook to fetch legal_documents with React Query caching
 *
 * Provides legal_document data with optimized caching:
 * - staleTime: 5 minutes - Data is fresh for this period
 * - gcTime: 30 minutes - Unused cache entries are collected after this period
 *
 * @param options - Hook options including active filter and additional filters
 * @returns Query result with legal_document data, loading, error states, and refetch function
 *
 * @example
 * ```typescript
 * import { useLegalDocuments } from './hooks/useLegalDocuments';
 *
 * function LegalDocumentList() {
 *   const { data, isLoading, error, refetch } = useLegalDocuments();
 *
 *   if (isLoading) return <Skeleton />;
 *   if (error) return <Error message={error.message} onRetry={refetch} />;
 *
 *   return (
 *     <List>
 *       {data?.map(item => <ListItem key={item.id}>{item.title}</ListItem>)}
 *     </List>
 *   );
 * }
 *
 * // With filters
 * const { data } = useLegalDocuments({ activeOnly: false, filters: { search: 'test' } });
 * ```
 */
export function useLegalDocuments(
  options: UseLegalDocumentsOptions = {}
): UseLegalDocumentsResult {
  const { activeOnly = true, filters = {}, enabled = true } = options;

  // Build the filter options combining activeOnly with other filters
  const filterOptions: LegalDocumentFilterOptions = {
    ...filters,
    is_active: activeOnly ? true : undefined,
  };

  const queryResult = useQuery<LegalDocument[], Error>({
    queryKey: legal_documentKeys.list(filterOptions),
    queryFn: async () => {
      const items = await legal_documentService.getAll(filterOptions);
      return items;
    },
    staleTime: LEGAL_DOCUMENT_STALE_TIME,
    gcTime: LEGAL_DOCUMENT_GC_TIME,
    enabled,
    retry: RETRY_COUNT,
    retryDelay,
  });

  return {
    ...queryResult,
    legalDocuments: queryResult.data,
  };
}

/**
 * Hook to fetch a single legal_document by ID
 *
 * @param id - LegalDocument ID (UUID)
 * @param options - Optional React Query options
 * @returns Query result with legal_document data
 *
 * @example
 * ```typescript
 * const { data: legalDocument, isLoading } = useLegalDocument('uuid-here');
 * ```
 */
export function useLegalDocument(
  id: string,
  options?: Omit<UseQueryOptions<LegalDocument | null, Error>, 'queryKey' | 'queryFn'>
): UseQueryResult<LegalDocument | null, Error> {
  return useQuery<LegalDocument | null, Error>({
    queryKey: legal_documentKeys.detail(id),
    queryFn: () => legal_documentService.getById(id),
    staleTime: LEGAL_DOCUMENT_STALE_TIME,
    gcTime: LEGAL_DOCUMENT_GC_TIME,
    enabled: !!id,
    retry: RETRY_COUNT,
    retryDelay,
    ...options,
  });
}

/**
 * Dropdown option type for legal_document select components
 */
export interface LegalDocumentDropdownOption {
  value: string;
  label: string;
  data: LegalDocument;
}

/**
 * Hook to fetch legal_documents formatted for dropdown selection
 *
 * Returns memoized options with { value, label, data } structure.
 *
 * @param activeOnly - Only include active legal_documents (default: true)
 * @returns Query result with dropdown options
 *
 * @example
 * ```typescript
 * const { data: options, isLoading } = useLegalDocumentsDropdown();
 *
 * <Select options={options} isLoading={isLoading} />
 * ```
 */
export function useLegalDocumentsDropdown(activeOnly: boolean = true) {
  const queryResult = useQuery<LegalDocumentDropdownOption[], Error>({
    queryKey: legal_documentKeys.dropdown(activeOnly),
    queryFn: () => legal_documentService.getForDropdown(!activeOnly),
    staleTime: LEGAL_DOCUMENT_STALE_TIME,
    gcTime: LEGAL_DOCUMENT_GC_TIME,
    retry: RETRY_COUNT,
    retryDelay,
  });

  // Memoize the options transformation
  const options = useMemo(() => queryResult.data ?? [], [queryResult.data]);

  return {
    ...queryResult,
    options,
  };
}

/**
 * Hook to create a new legal_document
 *
 * Automatically invalidates legal_document list queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: createLegalDocument, isPending } = useCreateLegalDocument();
 *
 * createLegalDocument({
 *   title: 'New LegalDocument',
 *   // ... other fields
 * });
 * ```
 */
export function useCreateLegalDocument(): UseMutationResult<
  LegalDocument,
  Error,
  LegalDocumentCreateRequest,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<LegalDocument, Error, LegalDocumentCreateRequest>({
    mutationFn: (data: LegalDocumentCreateRequest) =>
      legal_documentService.create(data),
    onSuccess: () => {
      // Invalidate all legal_document list queries to refetch fresh data
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
    },
  });
}

/**
 * Hook to update an existing legal_document
 *
 * Automatically invalidates legal_document list and detail queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: updateLegalDocument } = useUpdateLegalDocument();
 *
 * updateLegalDocument({
 *   id: 'uuid-here',
 *   data: { title: 'Updated Name' }
 * });
 * ```
 */
export function useUpdateLegalDocument(): UseMutationResult<
  LegalDocument,
  Error,
  { id: string; data: LegalDocumentUpdateRequest },
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<
    LegalDocument,
    Error,
    { id: string; data: LegalDocumentUpdateRequest }
  >({
    mutationFn: ({ id, data }) => legal_documentService.update(id, data),
    onSuccess: (_, { id }) => {
      // Invalidate all legal_document list queries
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
      // Invalidate the specific legal_document detail query
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.detail(id) });
    },
  });
}

/**
 * Hook to delete a legal_document
 *
 * Automatically invalidates legal_document queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deleteLegalDocument, isPending } = useDeleteLegalDocument();
 *
 * deleteLegalDocument('uuid-here');
 * ```
 */
export function useDeleteLegalDocument(): UseMutationResult<void, Error, string, unknown> {
  const queryClient = useQueryClient();

  return useMutation<void, Error, string>({
    mutationFn: (id: string) => legal_documentService.delete(id),
    onSuccess: (_, id) => {
      // Invalidate all legal_document queries
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
      // Remove the specific detail query from cache
      queryClient.removeQueries({ queryKey: legal_documentKeys.detail(id) });
    },
  });
}

/**
 * Hook to deactivate a legal_document (soft delete)
 *
 * Automatically invalidates legal_document queries on success.
 *
 * @returns Mutation result with mutate function
 *
 * @example
 * ```typescript
 * const { mutate: deactivateLegalDocument } = useDeactivateLegalDocument();
 *
 * deactivateLegalDocument('uuid-here');
 * ```
 */
export function useDeactivateLegalDocument(): UseMutationResult<
  LegalDocument,
  Error,
  string,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation<LegalDocument, Error, string>({
    mutationFn: (id: string) =>
      legal_documentService.update(id, { is_active: false } as LegalDocumentUpdateRequest),
    onSuccess: (_, id) => {
      // Invalidate all legal_document queries
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.all });
      // Invalidate the specific detail query
      queryClient.invalidateQueries({ queryKey: legal_documentKeys.detail(id) });
    },
  });
}

// Default export for convenience
export default useLegalDocuments;
