/**
 * EmailAccount Test Fixtures
 *
 * Test data fixtures for EmailAccount E2E and unit tests.
 * Provides predefined test data and factory functions for generating
 * test email_accounts.
 *
 * Fixture patterns:
 * - minimal: Only required fields with minimal valid values
 * - complete: All fields with realistic test values
 * - invalid: Invalid data for validation testing
 * - unique: Unique values using timestamps for test isolation
 *
 * OAuth email account for sending via Gmail, Microsoft, or SendGrid
 *
 * Generated by CodeGen OS v1.0.0
 * Generated at: 2026-03-10T13:09:39.938466Z
 */

import type { EmailAccountCreateRequest } from '../../types/email_account.types';

// ============================================================================
// Types
// ============================================================================

/**
 * Test data pattern types
 *
 * @description
 * - minimal: Only required fields with minimal valid values
 * - complete: All fields populated with realistic test data
 * - invalid: Data that should fail validation
 * - unique: Data with timestamps for test isolation
 */
export type TestDataPattern = 'minimal' | 'complete' | 'invalid' | 'unique';

/**
 * EmailAccount test fixture containing all test data patterns
 */
export interface EmailAccountTestFixtures {
  /** Minimal valid email_account with only required fields */
  minimal: EmailAccountCreateRequest;
  /** Complete email_account with all fields populated */
  complete: EmailAccountCreateRequest;
  /** Invalid email_account for testing validation errors */
  invalid: Partial<EmailAccountCreateRequest>;
  /** Unique email_account with timestamp-based values */
  unique: EmailAccountCreateRequest;
  /** Multiple email_accounts for list testing */
  list: EmailAccountCreateRequest[];
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Generate a unique identifier based on current timestamp
 * Useful for creating unique test data that won't conflict
 *
 * @param prefix - Optional prefix for the identifier
 * @returns Unique string identifier
 */
function generateUniqueId(prefix = ''): string {
  const timestamp = Date.now();
  const random = Math.random().toString(36).substring(2, 8);
  return prefix ? `${prefix}-${timestamp}-${random}` : `${timestamp}-${random}`;
}

/**
 * Generate a random string of specified length
 *
 * @param length - Length of the string to generate
 * @param charset - Character set to use (default: alphanumeric)
 * @returns Random string
 */
function randomString(
  length: number,
  charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
): string {
  let result = '';
  for (let i = 0; i < length; i++) {
    result += charset.charAt(Math.floor(Math.random() * charset.length));
  }
  return result;
}

/**
 * Generate a random integer between min and max (inclusive)
 *
 * @param min - Minimum value
 * @param max - Maximum value
 * @returns Random integer
 */
function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Generate a random decimal with specified precision
 *
 * @param min - Minimum value
 * @param max - Maximum value
 * @param precision - Number of decimal places
 * @returns Random decimal number
 */
function randomDecimal(min: number, max: number, precision = 2): number {
  const value = Math.random() * (max - min) + min;
  const factor = Math.pow(10, precision);
  return Math.round(value * factor) / factor;
}

/**
 * Generate a random date within a range
 *
 * @param startDate - Start of the range
 * @param endDate - End of the range
 * @returns Random date as ISO string
 */
function randomDate(startDate: Date, endDate: Date): string {
  const start = startDate.getTime();
  const end = endDate.getTime();
  const randomTime = start + Math.random() * (end - start);
  return new Date(randomTime).toISOString().split('T')[0];
}

/**
 * Pick a random element from an array
 *
 * @param array - Array to pick from
 * @returns Random element
 */
function randomPick<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

// ============================================================================
// Static Test Data
// ============================================================================


/**
 * Sample email_account names for generating realistic test data
 */
const SAMPLE_NAMES = [
  'Test EmailAccount Alpha',
  'Test EmailAccount Beta',
  'Test EmailAccount Gamma',
  'Sample EmailAccount One',
  'Sample EmailAccount Two',
  'Demo EmailAccount',
  'Example EmailAccount',
];

/**
 * Sample codes for generating realistic test data
 */
const SAMPLE_CODES = [
  'TST001',
  'TST002',
  'TST003',
  'DEMO01',
  'DEMO02',
  'SMPL01',
  'SMPL02',
];

/**
 * Sample descriptions for generating realistic test data
 */
const SAMPLE_DESCRIPTIONS = [
  'This is a test email_account for automated testing.',
  'Sample email_account created for E2E tests.',
  'Demo email_account with all fields populated.',
  'Example email_account for validation testing.',
  'Test data fixture for email_account operations.',
];

// ============================================================================
// Predefined Fixtures
// ============================================================================

/**
 * Minimal valid email_account fixture
 *
 * Contains only required fields with minimal valid values.
 * Use this when testing that minimal data is accepted.
 */
export const minimalEmailAccountFixture: EmailAccountCreateRequest = {
  is_active: true,
};

/**
 * Complete email_account fixture
 *
 * Contains all fields with realistic test values.
 * Use this when testing full CRUD operations.
 */
export const completeEmailAccountFixture: EmailAccountCreateRequest = {
  user_id: 'Test User Id',
  provider: 'Test Provider',
  email_address: 'Test Email Address',
  access_token: 'Test Access Token',
  refresh_token: 'Test Refresh Token',
  token_expires_at: 'Test Token Expires At',
  watch_history_id: 'Test Watch History Id',
  is_active: true,
};

/**
 * Unique email_account fixture
 *
 * Contains all fields with timestamp-based unique values.
 * Use this when testing to ensure data isolation between test runs.
 * Each field that needs uniqueness includes a timestamp/random component.
 */
export const uniqueEmailAccountFixture: EmailAccountCreateRequest = {
  user_id: `User Id ${generateUniqueId()}`,
  provider: `Provider ${generateUniqueId()}`,
  email_address: `Email Address ${generateUniqueId()}`,
  access_token: `Access Token ${generateUniqueId()}`,
  refresh_token: `Refresh Token ${generateUniqueId()}`,
  token_expires_at: `Token Expires At ${generateUniqueId()}`,
  watch_history_id: `Watch History Id ${generateUniqueId()}`,
  is_active: true,
};

/**
 * Invalid email_account fixture
 *
 * Contains invalid data that should fail validation.
 * Use this when testing validation error handling.
 * Covers: empty required fields, values out of range, invalid formats.
 */
export const invalidEmailAccountFixture: Partial<EmailAccountCreateRequest> = {
};

/**
 * Invalid data patterns for comprehensive validation testing
 *
 * Contains various invalid data scenarios:
 * - emptyRequired: All required fields left empty
 * - tooShort: String fields below minimum length
 * - tooLong: String fields exceeding maximum length
 * - outOfRangeMin: Numeric fields below minimum value
 * - outOfRangeMax: Numeric fields above maximum value
 * - wrongType: Fields with incorrect data types (as strings for type coercion testing)
 * - specialChars: Fields with potentially problematic characters
 */
export const emailAccountInvalidPatterns = {
  /** All required string fields empty */
  emptyRequired: {
  } as Partial<EmailAccountCreateRequest>,


  /** String fields exceeding maximum length */
  tooLong: {
    user_id: 'x'.repeat(150), // max: 100
    provider: 'x'.repeat(80), // max: 30
    email_address: 'x'.repeat(305), // max: 255
    watch_history_id: 'x'.repeat(150), // max: 100
  } as Partial<EmailAccountCreateRequest>,



  /** Fields with SQL injection attempts (for security testing) */
  sqlInjection: {
  } as Partial<EmailAccountCreateRequest>,

  /** Fields with XSS attempts (for security testing) */
  xssAttempts: {
  } as Partial<EmailAccountCreateRequest>,

  /** Fields with null values (for nullable field testing) */
  nullValues: {
    access_token: null,
    refresh_token: null,
    token_expires_at: null,
    watch_history_id: null,
  } as Partial<EmailAccountCreateRequest>,

  /** Fields with undefined values (for missing field testing) */
  undefinedValues: {
    // Intentionally empty - represents missing fields
  } as Partial<EmailAccountCreateRequest>,
};

/**
 * Collection of email_account fixtures for list testing
 *
 * Contains multiple email_accounts for testing list operations,
 * pagination, filtering, and sorting.
 */
export const emailAccountListFixtures: EmailAccountCreateRequest[] = [
  {
    user_id: 'User Id 1',
    provider: 'Provider 1',
    email_address: 'Email Address 1',
    access_token: 'Access Token 1',
    refresh_token: 'Refresh Token 1',
    token_expires_at: 'Token Expires At 1',
    watch_history_id: 'Watch History Id 1',
    is_active: true,
  },
  {
    user_id: 'User Id 2',
    provider: 'Provider 2',
    email_address: 'Email Address 2',
    access_token: 'Access Token 2',
    refresh_token: 'Refresh Token 2',
    token_expires_at: 'Token Expires At 2',
    watch_history_id: 'Watch History Id 2',
    is_active: true,
  },
  {
    user_id: 'User Id 3',
    provider: 'Provider 3',
    email_address: 'Email Address 3',
    access_token: 'Access Token 3',
    refresh_token: 'Refresh Token 3',
    token_expires_at: 'Token Expires At 3',
    watch_history_id: 'Watch History Id 3',
    is_active: true,
  },
  {
    user_id: 'User Id 4',
    provider: 'Provider 4',
    email_address: 'Email Address 4',
    access_token: 'Access Token 4',
    refresh_token: 'Refresh Token 4',
    token_expires_at: 'Token Expires At 4',
    watch_history_id: 'Watch History Id 4',
    is_active: true,
  },
  {
    user_id: 'User Id 5',
    provider: 'Provider 5',
    email_address: 'Email Address 5',
    access_token: 'Access Token 5',
    refresh_token: 'Refresh Token 5',
    token_expires_at: 'Token Expires At 5',
    watch_history_id: 'Watch History Id 5',
    is_active: false,
  },
];

// ============================================================================
// Fixture Collection
// ============================================================================

/**
 * All email_account test fixtures
 *
 * @example
 * ```typescript
 * import { emailAccountFixtures } from '../fixtures/email_accountFixtures';
 *
 * // Use minimal fixture
 * const minData = emailAccountFixtures.minimal;
 *
 * // Use complete fixture
 * const fullData = emailAccountFixtures.complete;
 *
 * // Use unique fixture (with timestamp)
 * const uniqueData = generateEmailAccountTestData('unique');
 * ```
 */
export const emailAccountFixtures: EmailAccountTestFixtures = {
  minimal: minimalEmailAccountFixture,
  complete: completeEmailAccountFixture,
  invalid: invalidEmailAccountFixture as EmailAccountCreateRequest,
  unique: uniqueEmailAccountFixture,
  list: emailAccountListFixtures,
};

// ============================================================================
// Factory Functions
// ============================================================================

/**
 * Generate email_account test data based on pattern
 *
 * @param pattern - The test data pattern to generate
 * @param overrides - Optional field overrides
 * @returns Generated test data
 *
 * @example
 * ```typescript
 * // Generate complete test data
 * const data = generateEmailAccountTestData('complete');
 *
 * // Generate unique test data with overrides
 * const customData = generateEmailAccountTestData('unique', {
 *   is_active: false,
 * });
 * ```
 */
export function generateEmailAccountTestData(
  pattern: TestDataPattern = 'complete',
  overrides: Partial<EmailAccountCreateRequest> = {}
): EmailAccountCreateRequest {
  let baseData: EmailAccountCreateRequest;

  switch (pattern) {
    case 'minimal':
      baseData = { ...minimalEmailAccountFixture };
      break;

    case 'complete':
      baseData = { ...completeEmailAccountFixture };
      break;

    case 'invalid':
      // Return invalid data (caller should handle validation failure)
      baseData = { ...invalidEmailAccountFixture } as EmailAccountCreateRequest;
      break;

    case 'unique':
      // Generate fresh unique values for each call
      baseData = {
        ...uniqueEmailAccountFixture,
      };
      break;

    default:
      baseData = { ...completeEmailAccountFixture };
  }

  return { ...baseData, ...overrides };
}

/**
 * Generate multiple email_account fixtures
 *
 * @param count - Number of fixtures to generate
 * @param pattern - The test data pattern to use as base
 * @param modifier - Optional function to modify each fixture
 * @returns Array of generated test data
 *
 * @example
 * ```typescript
 * // Generate 5 unique fixtures
 * const fixtures = generateMultipleEmailAccountFixtures(5, 'unique');
 *
 * // Generate fixtures with sequential numbering
 * const numbered = generateMultipleEmailAccountFixtures(3, 'complete', (data, index) => ({
 *   ...data,
 *   name: `EmailAccount #${index + 1}`,
 * }));
 * ```
 */
export function generateMultipleEmailAccountFixtures(
  count: number,
  pattern: TestDataPattern = 'unique',
  modifier?: (data: EmailAccountCreateRequest, index: number) => EmailAccountCreateRequest
): EmailAccountCreateRequest[] {
  const fixtures: EmailAccountCreateRequest[] = [];

  for (let i = 0; i < count; i++) {
    let fixture = generateEmailAccountTestData(pattern);

    if (modifier) {
      fixture = modifier(fixture, i);
    } else if (pattern === 'unique') {
      // Add index to ensure uniqueness even with same timestamp
    }

    fixtures.push(fixture);
  }

  return fixtures;
}

/**
 * Generate random email_account test data
 *
 * Creates test data with randomized values within valid ranges.
 * Useful for fuzz testing and edge case discovery.
 *
 * @param overrides - Optional field overrides
 * @returns Randomly generated test data
 *
 * @example
 * ```typescript
 * // Generate random test data
 * const randomData = generateRandomEmailAccountData();
 *
 * // Generate random data with specific field
 * const customRandom = generateRandomEmailAccountData({
 *   is_active: true,
 * });
 * ```
 */
export function generateRandomEmailAccountData(
  overrides: Partial<EmailAccountCreateRequest> = {}
): EmailAccountCreateRequest {
  const data: EmailAccountCreateRequest = {
    user_id: randomString(randomInt(None, Math.min(100, 50))),
    provider: randomString(randomInt(None, Math.min(30, 50))),
    email_address: randomString(randomInt(None, Math.min(255, 50))),
    access_token: randomString(randomInt(None, Math.min(None, 50))),
    refresh_token: randomString(randomInt(None, Math.min(None, 50))),
    token_expires_at: randomString(randomInt(None, Math.min(None, 50))),
    watch_history_id: randomString(randomInt(None, Math.min(100, 50))),
    is_active: Math.random() > 0.2, // 80% chance of being active
  };

  return { ...data, ...overrides };
}

// ============================================================================
// Validation Test Data
// ============================================================================

/**
 * Edge case test data for boundary testing
 *
 * Contains values at the boundaries of valid ranges.
 */
export const emailAccountEdgeCases = {
  /** user_id at maximum length (100 chars) */
  user_idMaxLength: 'x'.repeat(100),
  /** provider at maximum length (30 chars) */
  providerMaxLength: 'x'.repeat(30),
  /** email_address at maximum length (255 chars) */
  email_addressMaxLength: 'x'.repeat(255),
  /** watch_history_id at maximum length (100 chars) */
  watch_history_idMaxLength: 'x'.repeat(100),
};

/**
 * Special character test data for input sanitization testing
 */
export const emailAccountSpecialCharacterData: Partial<EmailAccountCreateRequest> = {
};

/**
 * Whitespace test data for trimming validation
 */
export const emailAccountWhitespaceData: Partial<EmailAccountCreateRequest> = {
};

// ============================================================================
// Exports
// ============================================================================

// Default export - main fixture collection
export default emailAccountFixtures;
